src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#75739](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75739)
=> Correção do bug 75739

src/SME.SR.Data/Models/NotaConceitoBimestreComponente.cs, src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#63152](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63152)
=> Correção do bug 63152 - Task 75615

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs
Ajuste na consulta para obter o componentes curriculares, verificando se a lista de turmas etsá preenchida.
=> Bug: 69378

src/SME.SR.Application/Queries/ComponenteCurricular/ObterDadosPedagogicosComponenteCurriculares/ObterDadosPedagogicosComponenteCurricularesQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterDadosPedagogicosComponenteCurricularesSeparacaoDiarioBordo/ObterDadosPedagogicosComponenteCurricularesSeparacaoDiarioBordoQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterDadosPedagogicosTurma/ObterDadosPedagogicosTurmaQueryHandler.cs
[AB#75478](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75478)
=> fix/75478 -> r2

src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs, src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
Ajuste nas consultas para obter as notas desconsiderando a flag de excluido da tabela de fechamento_turma_disciplina e considerando a última nota válida no boletim detalhado e ata final/bimestral e os registros consolidados para o boletim.
=> Bug: 76052

src/SME.SR.Application/Queries/ComponenteCurricular/ObterDadosPedagogicosComponenteCurriculares/ObterDadosPedagogicosComponenteCurricularesQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterDadosPedagogicosComponenteCurricularesSeparacaoDiarioBordo/ObterDadosPedagogicosComponenteCurricularesSeparacaoDiarioBordoQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterDadosPedagogicosTurma/ObterDadosPedagogicosTurmaQueryHandler.cs
[AB#75478](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75478)
=> Fix/75478 -> master

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#74923](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74923)
=> Correção do bug 74923

src/SME.SR.Application/UseCases/RelatorioAcompanhamentoRegistrosPedagogicosUseCase.cs
[AB#74919](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74919)
=> Fix/74919 -> r2

src/SME.SR.Application/UseCases/RelatorioAcompanhamentoRegistrosPedagogicosUseCase.cs
[AB#74919](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74919)
=> fix/74919 -> master

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesEolPorIds/ObterComponentesCurricularesEolPorIdsQueryHandler.cs
[AB#64370](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64370)
=> Fix/64370 -> release-r2

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#76103](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76103)
=> fix/76103 -> r2

src/SME.SR.Application/Queries/ConselhoClasse/ObterRecomendacoesPorAlunosTurmas/ObterRecomendacoesPorAlunosTurmasQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseAlunoRepository.cs, src/SME.SR.Data/Models/RecomendacaoConselhoClasseAluno.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseAlunoRepository.cs
[AB#76157](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76157)
=> Correção do bug 76157

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesEolPorIds/ObterComponentesCurricularesEolPorIdsQueryHandler.cs
[AB#64370](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64370)
=> fix/64370 -> master SR

src/SME.SR.Application/Queries/AcompanhamentoFechamento/ObterRelatorioAcompanhamentoFechamento/ObterRelatorioAcompanhamentoFechamentoQueryHandler.cs, src/SME.SR.Application/Queries/Fechamento/ObterFechamentoConsolidadoPorTurmasBimestre/ObterFechamentoConsolidadoPorTurmasQuery.cs, src/SME.SR.Application/Queries/Fechamento/ObterFechamentoConsolidadoPorTurmasBimestre/ObterFechamentoConsolidadoPorTurmasQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IFechamentoConsolidadoRepository.cs, src/SME.SR.Data/Repositories/Sgp/FechamentoConsolidadoRepository.cs
[AB#76083](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76083)
=> bug 76083 -> master SR

src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoEscolaAqui/ObterDadosMensagemEscolaAquiQueryHendler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioBoletim/ObterFrequenciasRelatorioBoletimQuery.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioBoletim/ObterFrequenciasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQuery.cs, src/SME.SR.Application/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterTurmaItinerarioEnsinoMedio/ObterTurmaItinerarioEnsinoMedioQuery.cs, src/SME.SR.Application/Queries/Turma/ObterTurmaItinerarioEnsinoMedio/ObterTurmaItinerarioEnsinoMedioQueryHandler.cs, src/SME.SR.Data/Interfaces/Eol/ITurmaEolRepository.cs, src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs, src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs, src/SME.SR.Data/Models/Turma.cs, src/SME.SR.Data/Repositories/Eol/TurmaEolRepository.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs, src/SME.SR.Infra/Dtos/Turma/TurmaItinerarioEnsinoMedioDto.cs
[AB#75703](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75703)
=> Fix/75703 -> r2

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#76103](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76103)
=> fix/76103 -> master

src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#76517](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76517)
=> Correção do bug 76517

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
Ajuste na consulta para obter as notas considerando registros sem período escolar. Ajuste na definição de notas dos bimestres tratando quando não há período escolar atrelado.
=> Bug: 76266

src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioBoletim/ObterNotasRelatorioBoletimQueryHandler.cs
[AB#75703](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75703)
=> fix/75703 -> r2 (pt.2)

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#75503](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75503)
=> Fix/75503 -> r2

src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoEscolaAqui/ObterDadosMensagemEscolaAquiQueryHendler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioBoletim/ObterFrequenciasRelatorioBoletimQuery.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioBoletim/ObterFrequenciasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioBoletim/ObterNotasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQuery.cs, src/SME.SR.Application/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterTurmaItinerarioEnsinoMedio/ObterTurmaItinerarioEnsinoMedioQuery.cs, src/SME.SR.Application/Queries/Turma/ObterTurmaItinerarioEnsinoMedio/ObterTurmaItinerarioEnsinoMedioQueryHandler.cs, src/SME.SR.Data/Interfaces/Eol/ITurmaEolRepository.cs, src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs, src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs, src/SME.SR.Data/Models/Turma.cs, src/SME.SR.Data/Repositories/Eol/TurmaEolRepository.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs, src/SME.SR.Infra/Dtos/Turma/TurmaItinerarioEnsinoMedioDto.cs
[AB#75703](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75703)
=> Fix/75703 -> master

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#75503](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75503)
=> fix/75503 -> master

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#76471](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76471)
=> Correção do bug 76471

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#76754](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76754)
=> Fix/76754 -> r2

src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IRelatorioSondagemComponentePorTurmaRepository.cs, src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
[AB#75938](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75938)
=> 75938 - Ajuste nas consultas de questões por bimestre

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Data/Models/NotaConceitoBimestreComponente.cs
[AB#76248](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76248)
=> Fix/76248-master -> r2

src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/FechamentoPendencias/RelatorioPendenciasQueryRetornoDto.cs
[AB#77156](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77156)
=> Correção do bug 77156

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Data/Models/NotaConceitoBimestreComponente.cs
[AB#76248](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76248)
=> fix76248 -> master

src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs, src/SME.SR.Application/Queries/RelatorioAcompanhamentoFrequência/ObterFrequenciaAlunoDiaria/ObterFrequenciaAlunoDiariaQuery.cs, src/SME.SR.Application/Queries/RelatorioAcompanhamentoFrequência/ObterFrequenciaAlunoDiaria/ObterFrequenciaAlunoDiariaQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FiltroAcompanhamentoFrequenciaJustificativaDto.cs, src/SME.SR.Infra/Dtos/Relatorios/FrequenciaIndividual/RelatorioFrequenciaIndividualBimestresDto.cs
[AB#65257](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65257)
=> 65257 - Alterar consulta do relatório de frequência

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQuery.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#77227](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77227)
=> Fix/77227 ->r2

src/SME.SR.Application/Commands/AlteracaoNotas/ObterDadosRelatorioAlteracaoNotas/ObterDadosRelatorioAlteracaoNotasCommandHandler.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/ObterAlunosETurmasHistoricoEscolar/ObterAlunosETurmasHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/ObterAlunosETurmasHistoricoEscolarTransferencia/ObterAlunosETurmasHistoricoEscolarTransferenciaQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterTurmasComplementaresEdFisica/ObterTurmasComplementaresEdFisicaQuery.cs, src/SME.SR.Application/Queries/Turma/ObterTurmasComplementaresEdFisica/ObterTurmasComplementaresEdFisicaQueryHandler.cs, src/SME.SR.Data/Models/Turma.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/RegistroFrequenciaRepository.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs, src/SME.SR.Infra/Dtos/Turma/AlunosTurmasCodigosDto.cs, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
[AB#69378](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69378)
=> Fix/69378 -> master

src/SME.SR.Infra/RelatorioPaginado/Coluna.cs, src/SME.SR.Infra/RelatorioPaginado/Interfaces/IColuna.cs, src/SME.SR.Infra/RelatorioPaginado/ParametroRelatorioPaginadoPorColuna.cs, src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoSondagemPorTurmaMatematica.cs, src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginado.cs, src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoColuna.cs, src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoPorColuna.cs, src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoQuantitativo.cs, src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoSondagemTurma.cs
[AB#77419](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77419)
=> 77419 - Ajustando a altura da pagina automatico

src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
[AB#77449](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77449)
=> 77449 - Correção da ordenação das respostas

src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs
[AB#77194](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77194)
=> fix/77194 -> r2

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseRepository.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseRepository.cs, src/SME.SR.Infra/Dtos/Aula/TotalAulasTurmaDisciplinaDto.cs
[AB#77521](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77521)
=> Bug 77521 -> r2

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#77426](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77426)
=> Fix/77426 -> master

src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs
[AB#77194](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77194)
=> fix/77194 -> master

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseRepository.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseRepository.cs, src/SME.SR.Infra/Dtos/Aula/TotalAulasTurmaDisciplinaDto.cs
[AB#77521](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77521)
=> Bug 77521 -> master

src/SME.SR.Data/Repositories/Sgp/DevolutivaRepository.cs, src/SME.SR.Data/Repositories/Sgp/DiarioBordoRepository.cs
[AB#77606](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77606)
=> 77606 - Filtro diario bordo não excluido

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
[AB#77963](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77963)
=> bug 77963 -> release-r2

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#77859](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77859)
=> fix/77859 -> master

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
[AB#77963](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77963)
=> fix/77963 -> master

src/SME.SR.Data/Extensions/StringExtension.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#78034](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78034)
=> 78034 - Ajuste performance consulta de quantitativo de alunos

src/SME.SR.Workers.SGP/Views/RelatorioFrequenciaIndividualNovo.cshtml
[AB#78067](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78067)
=> 78067 Corrigido Titulo do Relatório

src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
[AB#78071](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78071)
=> 78071 Removido Bimestre vazio quando selecionado "Todos"

src/SME.SR.Application/Queries/Alunos/ObterTotalAlunosPorUeAnoSondagem/ObterTotalAlunosPorUeAnoSondagemQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterTotalAlunosPorUeAnoSondagem/ObterTotalAlunosPorUeAnoSondagemQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioSondagemMatematicaConsolidadoUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs, src/SME.SR.Data/Interfaces/Sondagem/ISondagemAutoralRepository.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAutoralRepository.cs
[AB#78048](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78048)
=> 78048 - Relatório de consolidado matemática divergente da tela

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAcompanhamentoFrequencia/GerarRelatorioAcompanhamentoFrequenciaCommandHandler.cs, src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/FrequenciaIndividual/RelatorioFrequenciaIndividualBimestresDto.cs, src/SME.SR.MVC/Controllers/RelatoriosController.cs, src/SME.SR.MVC/Views/Relatorios/RelatorioFrequenciaIndividual.cshtml, src/SME.SR.MVC/Views/Relatorios/RelatorioFrequenciaIndividualNovo.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioFrequenciaIndividual.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioFrequenciaIndividualNovo.cshtml
[AB#78077](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78077)
=> 78077 Considerar Header Frequencia Diaria na paginação

src/SME.SR.Workers.SGP/Views/RelatorioFrequenciaIndividualNovo.cshtml
[AB#78101](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78101)
=> Ajustado layout do relatório

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseRepository.cs
[AB#78266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78266)
=> Correção do bug 78266

src/SME.SR.Infra/Dtos/Relatorios/RegistroFrequencia/TurmaComponenteDataAulaQuantidadeDto.cs
=> Bug: 73644

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAcompanhamentoFrequencia/GerarRelatorioAcompanhamentoFrequenciaCommandHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/FrequenciaIndividual/RelatorioFrequenciaIndividualBimestresDto.cs, src/SME.SR.Workers.SGP/Views/RelatorioFrequenciaIndividualNovo.cshtml
[AB#78077](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78077)
=> Correção do layout

src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#77881](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77881)
=> Fix/77881 -> r2

src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#77881](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77881)
=> Fix/77881 -> master

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#78374](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78374)
=> Fix/78374 -> r2

src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs
[AB#78558](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78558)
=> Correção do relatório impresso do bug 78558

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#78374](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78374)
=> fix/78374 -> master

src/SME.SR.Application/Queries/PlanoAEE/ObterQuestionarioIdPlanoAEE/ObterQuestionarioIdPlanoAEEQuery.cs, src/SME.SR.Application/Queries/PlanoAEE/ObterQuestionarioIdPlanoAEE/ObterQuestionarioIdPlanoAEEQueryHandler.cs, src/SME.SR.Application/Queries/PlanoAEE/ObterQuestoesPlanoAEEPorVersaoPlanoId/ObterQuestoesPlanoAEEPorVersaoPlanoIdQuery.cs, src/SME.SR.Application/Queries/PlanoAEE/ObterQuestoesPlanoAEEPorVersaoPlanoId/ObterQuestoesPlanoAEEPorVersaoPlanoIdQueryHandler.cs, src/SME.SR.Application/Queries/PlanoAEE/ObterRespostasPlanoAEEPorVersaoPlanoId/ObterRespostasPlanoAEEPorVersaoPlanoIdQuery.cs, src/SME.SR.Application/Queries/PlanoAEE/ObterRespostasPlanoAEEPorVersaoPlanoId/ObterRespostasPlanoAEEPorVersaoPlanoIdQueryHandler.cs, src/SME.SR.Application/Queries/Questionario/ObterQuestoesPorQuestionarioId/ObterQuestoesPorQuestionarioIdQuery.cs, src/SME.SR.Application/Queries/Questionario/ObterQuestoesPorQuestionarioId/ObterQuestoesPorQuestionarioIdQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IPlanoAeeRespostaRepository.cs, src/SME.SR.Data/Interfaces/Sgp/IQuestionarioRepository.cs, src/SME.SR.Data/Models/OpcaoQuestaoComplementar.cs, src/SME.SR.Data/Models/OpcaoResposta.cs, src/SME.SR.Data/Models/PlanoAeeQuestao.cs, src/SME.SR.Data/Models/PlanoAeeResposta.cs, src/SME.SR.Data/Models/PlanoAeeVersao.cs, src/SME.SR.Data/Models/Questao.cs, src/SME.SR.Data/Models/Questionario.cs, src/SME.SR.Data/Repositories/Sgp/PlanoAeeRespostaRepository.cs, src/SME.SR.Data/Repositories/Sgp/QuestionarioRepository.cs, src/SME.SR.Infra/Dtos/Questionario/OpcaoRespostaDto.cs, src/SME.SR.Infra/Dtos/Questionario/QuestaoDto.cs, src/SME.SR.Infra/Dtos/Questionario/RespostaQuestaoDto.cs, src/SME.SR.Infra/Enumeradores/TipoQuestao.cs, src/SME.SR.Infra/Enumeradores/TipoQuestionario.cs, src/SME.SR.IoC/Dependencias.cs
[AB#77527](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77527)
=> QueryMediator para obter questões e respostas do plano

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFBoletimDetalhadoCommand/GerarRelatorioHtmlPDFBoletimDetalhadoCommandHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQuery.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQuery.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/BoletimEscolarDetalhado/BoletimEscolarDetalhadoAlunoDto.cs, src/SME.SR.Infra/Dtos/Relatorios/BoletimEscolarDetalhado/BoletimEscolarDetalhadoDto.cs, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCorpo.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoEJACorpo.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoLista.cshtml
[AB#77255](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77255)
=> 77255 - relatório detalhado sem recomendações

src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
[AB#77252](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77252)
=> 77252 - Relatório Simples do ensino médio deve emitir 4 boletins

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFPlanoAee/GerarRelatorioHtmlPDFPlanoAeeCommand.cs, src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFPlanoAee/GerarRelatorioHtmlPDFPlanoAeeCommandHandler.cs, src/SME.SR.Workers.SGP/Views/RelatorioPlanoAee.cshtml
[AB#77519](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77519)
=> Criação do layout de plano aee

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFPlanoAee/GerarRelatorioHtmlPDFPlanoAeeCommandHandler.cs, src/SME.SR.Workers.SGP/Views/RelatorioPlanoAee.cshtml
[AB#77519](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77519)
=> Adicionando a situação em uma nova linha

src/SME.SR.Application/Interfaces/UseCases/IRelatorioPlanoAeeUseCase.cs, src/SME.SR.Application/Queries/PeriodoEscolar/ObterPeriodoEscolarPorId/ObterPeriodoEscolarPorIdQuery.cs, src/SME.SR.Application/Queries/PeriodoEscolar/ObterPeriodoEscolarPorId/ObterPeriodoEscolarPorIdQueryHandler.cs, src/SME.SR.Application/Queries/PlanoAEE/ObterPlanoAEEPorVersaoPlanoId/ObterPlanoAEEPorVersaoPlanoIdQuery.cs, src/SME.SR.Application/Queries/PlanoAEE/ObterPlanoAEEPorVersaoPlanoId/ObterPlanoAEEPorVersaoPlanoIdQueryHandler.cs, src/SME.SR.Application/Queries/Questionario/ObterQuestoesPorQuestionarioId/ObterQuestoesPorQuestionarioIdQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioPlanoAeeUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IPeriodoEscolarRepository.cs, src/SME.SR.Data/Interfaces/Sgp/IPlanoAeeVersaoRepository.cs, src/SME.SR.Data/Models/OpcaoQuestaoComplementar.cs, src/SME.SR.Data/Queries/PeriodoEscolarConsultas.cs, src/SME.SR.Data/Repositories/Sgp/DevolutivaRepository.cs, src/SME.SR.Data/Repositories/Sgp/FechamentoConsolidadoRepository.cs, src/SME.SR.Data/Repositories/Sgp/NotaTipoRepository.cs, src/SME.SR.Data/Repositories/Sgp/NotificacaoRepository.cs, src/SME.SR.Data/Repositories/Sgp/PeriodoEscolarRepository.cs, src/SME.SR.Data/Repositories/Sgp/PeriodoFechamentoRepository.cs, src/SME.SR.Data/Repositories/Sgp/PlanoAeeVersaoRepository.cs, src/SME.SR.Data/Repositories/Sgp/QuestionarioRepository.cs, src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs, src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesConsolidadoRepository.cs, src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesPorTurmaRepository.cs, src/SME.SR.Infra/Dtos/PlanoAEE/PlanoAeeDto.cs, src/SME.SR.Infra/Enumeradores/SituacaoPlanoAee.cs, src/SME.SR.Infra/Enumeradores/TipoQuestao.cs, src/SME.SR.IoC/Dependencias.cs, src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs, testes/SME.SR.Testes.QueryHandlers/RelatorioFaltasFrequenciaTeste.cs
[AB#77529](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77529)
[AB#77526](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77526)
=> Mapear Dto

src/SME.SR.MVC/Views/Relatorios/RelatorioRegistroOcorrencias.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioRegistroOcorrencias.cshtml
[AB#78922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78922)
=> fix 78922 Update RelatorioRegistroOcorrencias.cshtml

src/SME.SR.Application/Queries/RelatorioOcorrencias/ObterDadosRelatorioOcorrenciaCommandHandler.cs, src/SME.SR.Data/Repositories/Sgp/OcorrenciaRepository.cs
[AB#78986](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78986)
=> 78986 - Ajuste emissão relatório ocorrenicas pelo grid de ocorrencias

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/BoletimEscolarDetalhado/BoletimEscolarDetalhadoCabecalhoDto.cs, src/SME.SR.Infra/Dtos/Relatorios/BoletimEscolarDetalhado/BoletimEscolarDetalhadoDto.cs
[AB#79048](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79048)
=> 79048 - Ordenação de turma incorreta nas páginas

src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioBoletimSimples/ObterNotasRelatorioBoletimSimplesQueryHandler.cs
[AB#79033](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79033)
=> 79033 - Loop e valores incorretos na busca das notas e alunos

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFBoletimDetalhadoCommand/GerarRelatorioHtmlPDFBoletimDetalhadoCommandHandler.cs
[AB#79202](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79202)
=> 79202 - paginação incorreta

src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiarioInfantilComComponente.cshtml
[AB#78759](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78759)
=> Correção da conversão da data da aula

src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiarioInfantilComComponente.cshtml
[AB#78759](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78759)
=> Ajuste na conversão da data da aula para ordenação em produção.

src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#79385](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79385)
=> Correção do relatório de pendências, para desconsiderar pendências do calendário, fora do período do bimestre selecionado.

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
[AB#79386](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79386)
=> Exibição dos nomes dos componentes do território do saber + experiências

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#79590](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79590)
=> Fix/79590 -> master

src/SME.SR.Application/Commands/AlteracaoNotas/ObterDadosRelatorioAlteracaoNotas/ObterDadosRelatorioAlteracaoNotasCommandHandler.cs, src/SME.SR.Application/Queries/HistoricoAlteracaoNotas/ObterHistoricoNotasConselhoClassePorTurmaId/ObterHistoricoNotasConselhoClassePorTurmaIdQuery.cs, src/SME.SR.Application/Queries/HistoricoAlteracaoNotas/ObterHistoricoNotasConselhoClassePorTurmaId/ObterHistoricoNotasConselhoClassePorTurmaIdQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoAlteracaoNotas/ObterHistoricoNotasFechamentoPorTurmaId/ObterHistoricoNotasFechamentoPorTurmaIdQuery.cs, src/SME.SR.Application/Queries/HistoricoAlteracaoNotas/ObterHistoricoNotasFechamentoPorTurmaId/ObterHistoricoNotasFechamentoPorTurmaIdQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseNotaRepository.cs, src/SME.SR.Data/Interfaces/Sgp/IFechamentoNotaRepository.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseNotaRepository.cs, src/SME.SR.Data/Repositories/Sgp/FechamentoNotaRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/AlteracaoNotas/FiltroRelatorioAlteracaoNotasDto.cs, src/SME.SR.MVC/Views/Relatorios/RelatorioHistoricoAlteracoesNotas.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioHistoricoAlteracoesNotas.cshtml
[AB#50819](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50819)
=> Correção relatório de alteração de notas - Fechamento e por Conselho.

src/SME.SR.MVC/Views/Relatorios/RelatorioHistoricoAlteracoesNotas.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioHistoricoAlteracoesNotas.cshtml
[AB#50819](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50819)
=> Ajuste no tratamento da data

src/SME.SR.Application/Queries/Itinerancia/ObterItinerancias/ObterItineranciasQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/ItineranciaRepository.cs, src/SME.SR.Infra/Dtos/Itinerancia/ItineranciaQuestaoDto.cs, src/SME.SR.Workers.SGP/Views/RelatorioRegistroItinerancia.cshtml
[AB#64612](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64612)
=> Story/64612 - Registro de itinerância  Anexos - Servidor Relatórios 

src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs
[AB#79594](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79594)
=> Fix/79594 ->r2

src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesConsolidadoLeituraQuery.cs, src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesConsolidadoLeituraQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IRelatorioSondagemPortuguesConsolidadoRepository.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesConsolidadoRepository.cs
=> Complemento do bug 78991 - Melhoria na query de planilhas

src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs
[AB#79594](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79594)
=> fix/79594 -> master

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#79853](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79853)
=> Correção no método para obter alunos ativos

src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#79859](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79859)
=> fix/79859 -> r2

src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#79859](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79859)
=> fix/79859 -> master

src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs
=> fix/70496 -> r2 (teste de rotação imagem no ambiente)

src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs
=> fix/70496 pt.3 -> r2

src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs
[AB#80431](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80431)
=> Correção do bug 80431

src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs
=> fix/70496 - teste de ajuste na rotação da imagem 

src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs
=> fix/70496 -> r2

src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs
=> Fix/70496 -> master

src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoAprendizagem.cshtml
RAA - Melhorado controle de quebra de páginas em conteúdos com muitos parágrafos.
[AB#80336](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80336)
Co-authored-by: Cleiton Dias Dutra [cleitondutra2203@gmail.com](mailto:cleitondutra2203@gmail.com)
=> Fix/80336 - Controle de quebras de páginas

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Data/Models/NotaConceitoBimestreComponente.cs
[AB#80494](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80494)
=> Obter última nota relatório ata final

src/SME.SR.Application/Interfaces/UseCases/IRelatorioPlanosAeeUseCase.cs, src/SME.SR.Application/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQuery.cs, src/SME.SR.Application/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioPlanosAeeUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IPlanoAeeVersaoRepository.cs, src/SME.SR.Data/Repositories/Sgp/PlanoAeeVersaoRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/PlanoAEE/AgrupamentoDreUeDto.cs, src/SME.SR.Infra/Dtos/Relatorios/PlanoAEE/CabecalhoPlanosAeeDto.cs, src/SME.SR.Infra/Dtos/Relatorios/PlanoAEE/DetalhePlanosAeeDto.cs, src/SME.SR.Infra/Dtos/Relatorios/PlanoAEE/FiltroRelatorioPlanosAEEDto.cs, src/SME.SR.Infra/Dtos/Relatorios/PlanoAEE/PlanosAeeDto.cs, src/SME.SR.Infra/Dtos/Relatorios/PlanoAEE/RelatorioPlanosAeeDto.cs, src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
[AB#79746](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79746)
=> Estrutura básica do use case e endpoint

src/SME.SR.Workers.SGP/Views/RelatorioPlanosAEE.cshtml
[AB#79740](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79740)
=> 79740 - Layout do relatório em html sem quebras

src/SME.SR.Application/Queries/Arquivos/ObterHtmlComImagensBase64/ObterHtmlComImagensBase64QueryHandler.cs
[AB#80870](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80870)
=> Fix/80870 -> r2

src/SME.SR.Application/Queries/Arquivos/ObterHtmlComImagensBase64/ObterHtmlComImagensBase64QueryHandler.cs
[AB#80870](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80870)
=> fix/80870 - ajuste para validação da imagem ao ser impressa no RAA.

src/SME.SR.Application/Queries/Arquivos/ObterHtmlComImagensBase64/ObterHtmlComImagensBase64QueryHandler.cs
[AB#80870](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80870)
=> Fix/80870 -> master

src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs, src/SME.SR.Application/Queries/Arquivos/ObterHtmlComImagensBase64/ObterHtmlComImagensBase64QueryHandler.cs
[AB#81138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81138)
=> Fix/81138 -> r2

src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs, src/SME.SR.Application/Queries/Arquivos/ObterHtmlComImagensBase64/ObterHtmlComImagensBase64QueryHandler.cs
[AB#81138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81138)
=> fix/81138 -> master

src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaAluno/ObterFrequenciaAlunoQueryHandler.cs
[AB#81177](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81177)
=> fix/81177 -> r2

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#81631](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81631)
=> Fix/81631 -> r2

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#81631](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81631)
=> fix/81631 -> master

src/SME.SR.Application/UseCases/RelatorioPlanosAeeUseCase.cs
[AB#81727](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81727)
=> Mensagem incorreta quando não tem dados a serem gerados

src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoPlanoAee.cs
[AB#81772](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81772)
=> Erro na Quebra de página do relatório 

src/SME.SR.MVC/Views/Relatorios/RelatorioBoletimEscolarSimples.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
[AB#79214](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79214)
=> R2 Fix/79214 - Removendo a página em branco ao imprimir um boletim simples

src/SME.SR.MVC/Views/Relatorios/RelatorioBoletimEscolarSimples.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
[AB#79214](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79214)
=> Fix/79214 - Removendo a página em branco ao imprimir um boletim simples

src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralPorAnoEAlunos/ObterFrequenciasGeralPorAnoEAlunosQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#81813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81813)
=> Fix/81813 ->r2

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoEscolaAqui/ObterDadosMensagemEscolaAquiQueryHendler.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGlobalRelatorioBoletim/ObterFrequenciaGlobalRelatorioBoletimQuery.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGlobalRelatorioBoletim/ObterFrequenciaGlobalRelatorioBoletimQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#82155](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82155)
=> fix/82155 -> r2

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
Ajuste na definição da síntese, tratando para quando o valor fo numérico.
=> Bug: 81561

src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#82837](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82837)
=> Equalizando query de pesquisa por alunos no SR com Sondagem.

src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#83200](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83200)
=> Correção da busca de alunos ativos do Sondagem

src/SME.SR.Application/Interfaces/UseCases/IRelatorioEncaminhamentoAeeUseCase.cs, src/SME.SR.Application/Queries/EncaminhamentoAEE/ObterEncaminhamentoAEE/EncaminhamentoAEEQuery.cs, src/SME.SR.Application/Queries/EncaminhamentoAEE/ObterEncaminhamentoAEE/EncaminhamentoAEEQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioEncaminhamentoAeeUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IEncaminhamentoAeeRepository.cs, src/SME.SR.Data/Repositories/Sgp/EncaminhamentoAeeRepository.cs, src/SME.SR.IoC/Dependencias.cs, src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
[AB#79754](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79754)
=> 79754 - Use case e queryhandler

src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralPorAnoEAlunos/ObterFrequenciasGeralPorAnoEAlunosQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#81813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81813)
=> SR fix/81813 -> r2

src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs
[AB#83236](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83236)
=> Correção da falha ao gerar rel Frequencia

src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralPorAnoEAlunos/ObterFrequenciasGeralPorAnoEAlunosQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#81813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81813)
=> SR fix/81813 -> master

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFEncaminhamentoAee/GerarRelatorioHtmlPDFEncaminhamentoAeeCommand.cs, src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFEncaminhamentoAee/GerarRelatorioHtmlPDFEncaminhamentoAeeCommandHandler.cs, src/SME.SR.Application/Queries/EncaminhamentoAEE/ObterEncaminhamentosAEE/ObterEncaminhamentosAEEQuery.cs, src/SME.SR.Application/Queries/EncaminhamentoAEE/ObterEncaminhamentosAEE/ObterEncaminhamentosAEEQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioEncaminhamentoAeeUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IEncaminhamentoAeeRepository.cs, src/SME.SR.Data/Repositories/Sgp/EncaminhamentoAeeRepository.cs, src/SME.SR.Infra/Enumeradores/SituacaoEncaminhamentoAEE.cs, src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoEncaminhamentoAee.cs, src/SME.SR.Workers.SGP/Views/RelatorioEncaminhamentoAEE.cshtml
[AB#79755](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79755)
=> 79755 - Layout do relatório e quebra

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Infra/Fila/RotasRabbitSGP.cs
[AB#83409](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83409)
=> Boletim não chega a notificação do relatório gerado

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
[AB#83388](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83388)
=> Apresentar componentes que nao tiveram aulas na ata final.

src/SME.SR.Data/Repositories/Sgp/EncaminhamentoAeeRepository.cs
[AB#84035](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84035)
[AB#84038](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84038)
=> 84035 - Relatório não respeita filtro "Trazer encaminhamentos encerrados"

src/SME.SR.Data/Repositories/Sgp/EncaminhamentoAeeRepository.cs
[AB#84120](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84120)
=> 84120 - Relatório não respeita filtro Situação

src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs
Ajuste na funcionalidade de impressão do parecer tratando um possível retorno de objeto nulo em uma função.
=> Bug: 83214

src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs
[AB#84253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84253)
=> Fix/84253 -> master

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#84950](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84950)
=> Obter última nota válida

src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
[AB#79669](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79669)
=> Correção dos filtros do relatório de pendências.

src/SME.SR.Data/Repositories/Sondagem/SondagemAutoralRepository.cs
[AB#85620](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85620)
=> fix/85620 pt.2 -> r2

src/SME.SR.Infra/Enumeradores/TipoEscola.cs
[AB#85769](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85769)
=> 85769 - Erro ao gerar o relatório opção todos

src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAutoralRepository.cs
[AB#85620](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85620)
=> Fix/85620 -> master

src/SME.SR.Application/UseCases/RelatorioEncaminhamentosAeeUseCase.cs, src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoAEE/AgrupamentoEncaminhamentoAeeDreUeDto.cs
[AB#85772](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85772)
=> 85772 - Ordem de apresentação das UEs

src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#85879](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85879)
=> fix/85879 -> master

src/SME.SR.Data/Repositories/Sgp/ParecerConclusivoRepository.cs
[AB#86477](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86477)
=> fix/86477 -> master

src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#86298](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86298)
=> Fix/86298 -> r2

src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#86298](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86298)
=> fix/86298 -> master

src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
[AB#86829](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86829)
=> Fix/86829 -> r2

src/SME.SR.Data/Repositories/Sgp/ParecerConclusivoRepository.cs
Ajuste no relatório de parecer conclusivo, deslocando o filtro de parecer no resultado da consulta para desprezar os registros de parecer repetidos indevidamente.
=> Bug: 88103

src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
[AB#86829](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86829)
=> fix/86829 pt.3 -> r2

src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioSondagemComponentesPorTurmaUseCase.cs
[AB#85360](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85360)
=> 85855 - Ajustes usabilidade do campo semestre ao invés do bimestre

src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AreaDoConhecimentoRepository.cs
=> fix/88601 -> r2

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFHistoricoEscolar/GerarRelatorioHtmlPDFHistoricoEscolarCommandHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/ObterAlunosETurmasHistoricoEscolar/ObterAlunosETurmasHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/ObterAlunosETurmasHistoricoEscolarTransferencia/ObterAlunosETurmasHistoricoEscolarTransferenciaQueryHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/RelatorioPaginadoHistoricoEscolarDto.cs, src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoHistoricoEscolar.cs, src/SME.SR.Workers.SGP/Views/HistoricoEscolar/Assinaturas.cshtml, src/SME.SR.Workers.SGP/Views/HistoricoEscolar/Cabecalho.cshtml, src/SME.SR.Workers.SGP/Views/HistoricoEscolar/Css.cshtml
Ajuste de quebra de pagina e layout do relatório
=> Ajuste de quebra de pagina e layout

src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoNAAPA/EncaminhamentoNAAPASimplesDto.cs
[AB#88773](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88773)
=> Correção da lista de fluxos

src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
[AB#88618](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88618)
=> fix/88618 -> r2

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhado/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhadoCommand.cs, src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhado/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhadoCommandHandler.cs, src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNaapaDetalhadoUseCase.cs, src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoNAAPA/Detalhado/CabecalhoEncaminhamentoNAAPADetalhadoDto.cs, src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoNAAPA/Detalhado/QuestaoEncaminhamentoNAAPADetalhadoDto.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/EncaminhamentoNaapaDetalhadoPagina.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/EncaminhamentoNaapaDetalhadoPaginado.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/NomeComponentesEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoContatoResponsavelEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoContraturnoEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoEnderecoEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoFiliacaoEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoInformacoesEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoItensItineranciaEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoRelatorioEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoRespostaTextoEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoTabelaEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoTituloEncaminhamentoNaapa.cs, src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoTurmaProgramaEncaminhamentoNaapa.cs, src/SME.SR.Workers.SGP/Views/RelatorioEncaminhamentoNaapaDetalhado.cshtml
[AB#87564](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87564)
=> Layout do relatório e Quebra

src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AreaDoConhecimentoRepository.cs
[AB#88601](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88601)
=> Fix/88601 pt.2 -> r2

src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
[AB#88618](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88618)
=> fix/88618 -> master

src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNAAPAUseCase.cs
[AB#88932](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88932)
=> 88932 - Ajuste paginação relatório

src/SME.SR.Data/Repositories/Sgp/EncaminhamentoNAAPARepository.cs
[AB#89031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89031)
=> 89031 - Ajuste agrupamento de consulta lookup Dapper

src/SME.SR.Workers.SGP/Views/RelatorioEncaminhamentosNAAPA.cshtml
[AB#88890](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88890)
=> 88890 - Relatório está quebrando indevidamente em todas as DRE

src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNAAPAUseCase.cs
[AB#89110](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89110)
=> 89110 - As DREs não estão carregando em ordem do código

src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs, src/SME.SR.Data/Models/TipoNotaCicloAno.cs, src/SME.SR.Data/Repositories/Eol/AreaDoConhecimentoRepository.cs
[AB#88601](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88601)
=> Fix/88601 -> master

src/SME.SR.Workers.SGP/Views/RelatorioEncaminhamentosNAAPA.cshtml
[AB#89122](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89122)
=> 89122 - Página em branco no meio do relatório

src/SME.SR.Workers.SGP/Views/RelatorioEncaminhamentoNaapaDetalhado.cshtml
[AB#89160](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89160)
=> 89160 - Ajuste título relatório NAAPA

src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoHistoricoEscolar.cs
[AB#89212](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89212)
=> 89212 - pagina quebrando com obsevacao com uma linha

src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoRelatorioEncaminhamentoNaapa.cs, src/SME.SR.Workers.SGP/Views/RelatorioEncaminhamentoNaapaDetalhado.cshtml
[AB#89185](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89185)
=> 89185 - Não apresentar campos sem respostas.

src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoHistoricoEscolar.cs
[AB#89193](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89193)
=> 89193 - Quebra de seção

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhado/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhadoCommandHandler.cs
[AB#89206](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89206)
=> 89206 - Repetindo paginas

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhado/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhadoCommandHandler.cs, src/SME.SR.Workers.SGP/Views/RelatorioEncaminhamentoNaapaDetalhado.cshtml
[AB#89160](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89160)
=> 89160 - Ajuste nome relatório não citado no bug

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhado/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhadoCommandHandler.cs, src/SME.SR.Workers.SGP/Views/RelatorioEncaminhamentoNaapaDetalhado.cshtml
[AB#88901](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88901)
=> Correção no titulo e rodapé do texto do relatório

src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNAAPAUseCase.cs
[AB#88906](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88906)
=> 88906 - alteração do command

src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/EncaminhamentoNaapaPaginado.cs
[AB#88906](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88906)
=> 88906 - Quebra de pagina

src/SME.SR.Data/Repositories/Sgp/FechamentoNotaRepository.cs
[AB#89325](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89325)
=> Correção do relatório da situação e usuário aprovação quando recusado ou aprovado

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#85572](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85572)
=> Considerar notas da turma selecionada no filtro.

src/SME.SR.Data/Repositories/Sgp/FechamentoNotaRepository.cs
[AB#89389](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89389)
=> Enquanto estiver em aprovação, não deve mostrar ter aprovador

src/SME.SR.Workers.SGP/Views/RelatorioHistoricoAlteracoesNotas.cshtml
[AB#89373](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89373)
=> 89373 - Ajuste apresentação legenda pagina unica ou ultima pagina

src/SME.SR.Workers.SGP/Views/RelatorioHistoricoAlteracoesNotas.cshtml
[AB#89353](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89353)
=> Ajustes na quebra de Pagina do relatório

src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNaapaDetalhadoUseCase.cs
[AB#89307](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89307)
=> 89307 - Questão não apresentada

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAnaliticoDaSondagemExcel/GerarRelatorioAnaliticoDaSondagemExcelCommandHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterRelatorioAnaliticoSondagemExcel/ObterRelatorioAnaliticoSondagemExcelQueryHandler.cs, src/SME.SR.Infra/Excel/Sondagem/GeradorDeTabelaExcelAnaliticoSondagem.cs, src/SME.SR.Infra/Excel/Sondagem/GeradorDeTabelaExcelAnaliticoSondagemCapacidadeDeLeitura.cs, src/SME.SR.Infra/Excel/Sondagem/GeradorDeTabelaExcelAnaliticoSondagemEscrita.cs, src/SME.SR.Infra/Excel/Sondagem/GeradorDeTabelaExcelAnaliticoSondagemLeitura.cs, src/SME.SR.Infra/Excel/Sondagem/GeradorDeTabelaExcelAnaliticoSondagemProducaoDeTexto.cs
[AB#88998](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88998)
=> 88998 - Criar estrutura excel SR - Demais

src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
[AB#90404](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90404)
=> fix/90404 -> r2

src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
[AB#90404](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90404)
=> Fix/90404 -> master

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/NotaConceito/ObterTiposNotaRelatorioBoletim/ObterTiposNotaRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs, src/SME.SR.Application/Queries/Ue/ObterUesConclusao/ObterUesConclusaoQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs, src/SME.SR.Data/Models/TipoCiclo.cs
[AB#90372](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90372)
=> Ajustes para tratar anos alfanuméricos de turmas do EM.

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#90426](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90426)
=> Dados estão vindo incorreto pro ano 2022

src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/Frequencia/Pdf/RelatorioFrequenciaCabecalhoDto.cs, src/SME.SR.Workers.SGP/Views/RelatorioFrequencias.cshtml
[AB#90546](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90546)
=> Remover coluna de compensações quando modelidade infantil

src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioAtaFinal/ObterNotasRelatorioAtaFinalQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/INotaConceitoRepository.cs, src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#90061](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90061)
=> Fix/90061 -> r2

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAnaliticoDaSondagemExcel/GerarRelatorioAnaliticoDaSondagemExcelCommandHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterRelatorioAnaliticoSondagem/ObterRelatorioAnaliticoSondagemQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioAnaliticoSondagemUseCase.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/RelatorioSondagemAnaliticoExcelDto.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/RelatorioSondagemAnaliticoPorDreDto.cs, src/SME.SR.Infra/Excel/Sondagem/GeradorDeTabelaExcelAnaliticoSondagem.cs
Adicionar Ano Letivo e Período no Relatório no relatório impresso no Excel
=> Adicionar Ano Letivo e Período no Relatório

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQuery.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRecomendacoesPorAlunosTurmas/ObterRecomendacoesPorAlunosTurmasQueryHandler.cs
[AB#90445](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90445)
=> fix/90445 -> r2

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQuery.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRecomendacoesPorAlunosTurmas/ObterRecomendacoesPorAlunosTurmasQueryHandler.cs
[AB#90445](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90445)
=> fix/90445 -> master

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#90591](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90591)
=> fix/90591 -> r2

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AreaDoConhecimentoRepository.cs
[AB#90549](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90549)
=> fix/90549 -> r2

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AreaDoConhecimentoRepository.cs
[AB#90549](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90549)
=> fix/90549 -> master

src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioAtaFinal/ObterNotasRelatorioAtaFinalQueryHandler.cs
[AB#90453](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90453)
=> fix/90453 -> master

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#90591](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90591)
=> fix/90591 -> master

src/SME.SR.Infra/Enumeradores/TipoSondagem.cs
[AB#90009](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90009)
=> 90009 - Adição de enum tipos relatórios Sondagem Matemárica

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQuery.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRecomendacoesPorAlunosTurmas/ObterRecomendacoesPorAlunosTurmasQueryHandler.cs, src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioAtaFinal/ObterNotasRelatorioAtaFinalQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AreaDoConhecimentoRepository.cs, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoEJACorpo.cshtml
[AB#90423](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90423)
=> Fix/90423 -> r2

src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoEJACorpo.cshtml
[AB#90423](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90423)
=> fix/90423 -> master

src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
[AB#90495](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90495)
=> fix/90495 -> r2

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#90530](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90530)
=> Corrigir a verificação de alunos com frequencia registrada

src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
[AB#90495](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90495)
=> Fix/90495 -pt.2 -> r2

src/SME.SR.Application/Queries/Sondagem/ObterRelatorioAnaliticoSondagem/ObterRelatorioAnaliticoSondagemQueryHandler.cs, src/SME.SR.Data/Interfaces/Sondagem/ISondagemAnaliticaRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/CabecalhoSondagemAnaliticaDto.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/RelatorioSondagemAnaliticoNumeroIadDto.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/RespostaSondagemAnaliticaDto.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/RespostaSondagemAnaliticaNumeroIadDto.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/SubCabecalhoSondagemAnaliticaDto.cs
[AB#90004](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90004)
=> 90004 - Dtos

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAnaliticoDaSondagemExcel/GerarRelatorioAnaliticoDaSondagemExcelCommandHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterRelatorioAnaliticoSondagemExcel/ObterRelatorioAnaliticoSondagemExcelQueryHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/MergeColunaDto.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/RelatorioSondagemAnaliticoExcelDto.cs, src/SME.SR.Infra/Excel/Sondagem/GeradorDeTabelaExcelAnaliticoSondagem.cs, src/SME.SR.Infra/Excel/Sondagem/GeradorDeTabelaExcelAnaliticoSondagemAditivoMultiplicativo.cs, src/SME.SR.Infra/Excel/Sondagem/GeradorDeTabelaExcelAnaliticoSondagemNumeroIAD.cs
[AB#90004](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90004)
=> 90004 - Criar estrutura excel SR - Demais

src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
[AB#89743](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89743)
=> Fix/89743 -> r2

src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
[AB#89743](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89743)
=> fix/89743 -> master

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#91756](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91756)
=> 91756 - Ajuste nome relatório multiplicativos e IDA

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemRelatorioRepository.cs
[AB#91820](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91820)
=> 91820 - Erro ao gerar relatorio 2022 - IAD

src/SME.SR.Data/Repositories/Sondagem/SondagemRelatorioRepository.cs
[AB#92153](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92153)
[AB#92155](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92155)
=> Erro ao gerar o relatório de capacidade de leitura para todas as DREs

src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#92132](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92132)
=> 92132 - Quando tem mais de uma aula está carregando no relatório os dados diferente da tela

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs
[AB#92201](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92201)
=> verificando se há componentes vazios

src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNAAPAUseCase.cs
[AB#92166](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92166)
=> 92166 - E os registros devem ser ordenados por data de entrada da queixa

src/SME.SR.Workers.SGP/Views/RelatorioFrequenciaIndividualNovo.cshtml
[AB#92130](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92130)
=> 92130 - Não está com arredondamento em duas casas decimais

src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQuery.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs
[AB#92160](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92160)
=> 92160 - Frequência global do estudante está incorreta

src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNAAPAUseCase.cs
[AB#92166](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92166)
=> 92166 - Ordenação por ordem decrescente

src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#92365](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92365)
=> Corrigir join ao buscar dados de turmas históricas.

src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs
[AB#92214](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92214)
=> fix/92214 -> r2

src/SME.SR.Data/Queries/FrequenciaAlunoConsultas.cs, src/SME.SR.Workers.SGP/Views/RelatorioEncaminhamentoAEEDetalhado.cshtml
[AB#92193](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92193)
[AB#92255](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92255)
=> 92193 - Estudantes não tem frequência registrada e está saindo

src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioAtaFinal/ObterNotasRelatorioAtaFinalQueryHandler.cs
[AB#92369](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92369)
=> Obter notas alfabéticas para relatório de ata final.

src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaFinal/ObterDadosComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterNotasFrequenciaComponenteComNotaFinal/ObterNotasFrequenciaComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarTransferencia/MontarHistoricoEscolarTransferenciaQueryHandler.cs, src/SME.SR.Data/Models/ComponenteComNota.cs, src/SME.SR.Data/Models/ComponenteRegenciaComNota.cs
Reverts prefeiturasp/SME-ServidorRelatorios#2669
=> Revert "92162 - Ajuste frequencia aluno nula e não arredondada em 2 casas rel…"

src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaFinal/ObterDadosComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterNotasFrequenciaComponenteComNotaFinal/ObterNotasFrequenciaComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarTransferencia/MontarHistoricoEscolarTransferenciaQueryHandler.cs, src/SME.SR.Data/Models/ComponenteComNota.cs, src/SME.SR.Data/Models/ComponenteRegenciaComNota.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
Reverts prefeiturasp/SME-ServidorRelatorios#2670
=> Revert "Fix/92162"

src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs
[AB#92214](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92214)
=> fix/92214 -> master

src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaFinal/ObterDadosComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteSemNotaBimestre/ObterDadosComponenteSemNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteSemNotaFinal/ObterDadosComponenteSemNotaFinalQueryHandler.cs, src/SME.SR.Data/Models/ComponenteSemNota.cs
Reverts prefeiturasp/SME-ServidorRelatorios#2674
=> Revert "92162 - Removido tratamento de string vazia"

src/SME.SR.Application/Queries/HistoricoEscolar/ObterObservacoesDosAlunosNoHistoricoEscolar/ObterObservacoesDosAlunosNoHistoricoEscolarQuery.cs, src/SME.SR.Application/Queries/HistoricoEscolar/ObterObservacoesDosAlunosNoHistoricoEscolar/ObterObservacoesDosAlunosNoHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IHistoricoEscolarObservacaoRepository.cs, src/SME.SR.Data/Models/FiltroHistoricoEscolarAlunosDto.cs, src/SME.SR.Data/Models/FiltroHistoricoEscolarDto.cs, src/SME.SR.Data/Repositories/Sgp/HistoricoEscolarObservacaoRepository.cs, src/SME.SR.IoC/Dependencias.cs
[AB#92637](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92637)
=> 92637 - Observações gravadas não saem quando emitido histórico de Todos os alunos

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurma/ObterComponentesCurricularesPorCodigosTurmaQuery.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurma/ObterComponentesCurricularesPorCodigosTurmaQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteSemNotaBimestre/ObterDadosComponenteSemNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs, src/SME.SR.Application/Queries/Fechamento/ObterRecomendacoesPorFechamento/ObterRecomendacoesPorFechamentoQueryHandler.cs
[AB#92164](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92164)
=> fix/92164 -> master

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#92253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92253)
=> 92253 - Relatório analítico PT Leitura - Valores totais não batem

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs
Ajuste na impressão do boletim verificando a quantidade por página e se estiver definido como 2, não inclui as recomendações.
=> Bug: 92975

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemRelatorioRepository.cs
[AB#92891](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92891)
=> 92891 - Ajuste tag Sem Preenchimento query 2021 Aditivo

src/SME.SR.Workers.SGP/Views/RelatorioRegistroItinerancia.cshtml
[AB#92886](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92886)
=> 92886 - Ajuste quebra de paginas alunos

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
Correção Total Sem Preenchimento e Total Alunos
[AB#92253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92253)
=> Correção Total Sem Preenchimento e Total Alunos

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#93185](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93185)
=> fix/93185 -> master

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#93338](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93338)
=> 93338 - Valores da tela não tem com os valores do excel

src/SME.SR.Data/Queries/AlunoConsultas.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/TotalAlunosAnoTurmaDto.cs
Ajustes da consulta de obter alunos
=> Ajustes da consulta de obter alunos

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaFinal/ObterDadosComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteSemNotaBimestre/ObterDadosComponenteSemNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteSemNotaFinal/ObterDadosComponenteSemNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterNotasFrequenciaComponenteComNotaFinal/ObterNotasFrequenciaComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarTransferencia/MontarHistoricoEscolarTransferenciaQueryHandler.cs, src/SME.SR.Data/Models/ComponenteComNota.cs, src/SME.SR.Data/Models/ComponenteRegenciaComNota.cs, src/SME.SR.Data/Models/ComponenteSemNota.cs
[AB#93366](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93366)
=> Fix/93366 -> r2

src/SME.SR.Data/Repositories/Sgp/ComponenteCurricularGrupoAreaOrdenacaoRepository.cs
[AB#93717](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93717)
=> fix/93717 -> master

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatoricoControleDeFrequenciaMensalExcel/GerarRelatoricoControleDeFrequenciaMensalExcelCommand.cs, src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatoricoControleDeFrequenciaMensalExcel/GerarRelatoricoControleDeFrequenciaMensalExcelCommandHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterControleFrequenciaMensalParaExcel/ObterControleFrequenciaMensalParaExcelQuery.cs, src/SME.SR.Application/Queries/Frequencia/ObterControleFrequenciaMensalParaExcel/ObterControleFrequenciaMensalParaExcelQueryHandler.cs, src/SME.SR.Infra/Dtos/FrequenciaMensal/ControleFrequenciaPorMesDto.cs, src/SME.SR.Infra/Dtos/FrequenciaMensal/RelatorioControleFrequenciaMensalExcelDto.cs
[AB#89966](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89966)
=> 89966 - Renderizar relatório em Excel

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatoricoControleDeFrequenciaMensalExcel/GerarRelatoricoControleDeFrequenciaMensalExcelCommandHandler.cs, src/SME.SR.Infra/Dtos/FrequenciaMensal/RelatorioControleFrequenciaMensalExcelDto.cs
[AB#89966](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89966)
=> 89966 - Ajuste frequencia global

src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#94109](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94109)
=> Não exibir zeros nas atas bimestrais de componentes que não registram freq.

src/SME.SR.Infra/Dtos/Relatorios/FechamentoPendencias/RelatorioPendenciasPendenciaDto.cs, src/SME.SR.Infra/Dtos/Relatorios/FechamentoPendencias/RelatorioPendenciasQueryRetornoDto.cs, src/SME.SR.Workers.SGP/Views/RelatorioPendencias.cshtml
[AB#91177](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91177)
=> 91177 - Ajustar o layout do relatório

src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/FechamentoPendencias/RelatorioPendenciasQueryRetornoDto.cs
[AB#91190](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91190)
=> 91190 - Alteração de inclusão de campos de quantidade de aulas e dias

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#94137](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94137)
=> fix/94137 -> r2

src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosEscola/ObterDadosAlunosEscolaQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosEscola/ObterDadosAlunosEscolaQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#94321](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94321)
=> 94321 - Ajuste relatório frequencia mensal todas Ues

src/SME.SR.Application/UseCases/RelatorioFrequenciaControleMensalUseCase.cs
[AB#94485](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94485)
=> 94485 - Ordenação

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#94137](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94137)
=> fix/94137 -> master

src/SME.SR.Application/UseCases/RelatorioFrequenciaControleMensalUseCase.cs, src/SME.SR.Infra/Dtos/FrequenciaMensal/ConsultaRelatorioFrequenciaControleMensalDto.cs
[AB#94496](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94496) 
[AB#94500](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94500)
=> 94496 e 94500 - Ajuste quantidade e totais compensações

src/SME.SR.Application/UseCases/RelatorioFrequenciaControleMensalUseCase.cs
[AB#94728](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94728)
[AB#94755](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94755)
=> 94728 - "Frequência do período" e "Frequência global do mês" incorretos

src/SME.SR.Application/UseCases/RelatorioFrequenciaControleMensalUseCase.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs, src/SME.SR.Infra/Dtos/FrequenciaMensal/ConsultaRelatorioFrequenciaControleMensalDto.cs
[AB#94751](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94751)
=> Componentes curriculares não são exibidos no relatório na ordem da tela de conselho de classe

src/SME.SR.Application/Queries/Frequencia/ObterControleFrequenciaMensalParaExcel/ObterControleFrequenciaMensalParaExcelQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioFrequenciaControleMensalUseCase.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#94755](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94755)
=> 94755 - Total de aulas no período considera a quantidade de dias e não de aulas

src/SME.SR.Application/UseCases/RelatorioEncaminhamentoAeeDetalhadoUseCase.cs, src/SME.SR.Application/UseCases/RelatorioPlanoAeeUseCase.cs, src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoAEE/CabecalhoEncaminhamentoAeeDetalhadoDto.cs, src/SME.SR.Infra/Dtos/Relatorios/PlanoAEE/CabecalhoPlanoAeeDto.cs
[AB#90286](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90286)
=> 90286 - Ordenar Impressão do relatório

src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeAnalitico/GerarRelatorioControleGradeAnaliticoCommandHandler.cs, src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeSintetico/GerarRelatorioControleGradeSinteticoCommandHandler.cs, src/SME.SR.Application/Queries/Aula/VerificarAulasNormaisCriadasProfessorRegencia/VerificarAulasNormaisCriadasProfessorRegenciaQuery.cs, src/SME.SR.Application/Queries/Aula/VerificarAulasNormaisCriadasProfessorRegencia/VerificarAulasNormaisCriadasProfessorRegenciaQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IAulaRepository.cs, src/SME.SR.Data/Repositories/Sgp/AulaRepository.cs
[AB#95091](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95091)
=> Corrigindo falha ao gerar relatório controle de grade.

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#93537](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93537)
=> Boletim Simples e Detalhado obtendo as informações do consolidado do conselho de classe

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQuery.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegenciaPorCodigosTurma/ObterComponentesCurricularesRegenciaPorCodigosTurmaQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioBoletim/ObterComponentesCurricularesTurmasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IComponenteCurricularRepository.cs, src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs, src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#95102](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95102)
=> fix/95102 -> r2

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQuery.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegenciaPorCodigosTurma/ObterComponentesCurricularesRegenciaPorCodigosTurmaQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioBoletim/ObterComponentesCurricularesTurmasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IComponenteCurricularRepository.cs, src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs, src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#95102](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95102)
=> Fix/95102 -> master

src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FrequenciaAlunoConsolidadoDto.cs
[AB#95509](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95509)
=> Tratar percentual de frequencia formatado para alunos sem frequência.

src/SME.SR.Application/UseCases/RelatorioDevolutivasUseCase.cs, src/SME.SR.Data/Repositories/Sgp/DevolutivaRepository.cs, src/SME.SR.Data/Repositories/Sgp/UeRepository.cs
[AB#95115](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95115)
=> Correções nos dados do relatório de devolutivas

src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FrequenciaAlunoConsolidadoDto.cs
[AB#95506](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95506)
=> Formatar percentual de frequência com duas casas decimais.

src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#95619](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95619)
[AB#95637](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95637)
=> Erro ao gerar boletim simples ou detalhado para Ensino Médio

src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioAtaFinal/ObterNotasRelatorioAtaFinalQueryHandler.cs
[AB#95699](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95699)
=> 95699 - Ata final de resultados - erro ao gerar para EF

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#95709](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95709)
=> 95709 - Ata final de resultados para 2º ano EM com erro na geração quando visualização for estudante

src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommandHandler.cs
[AB#95801](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95801)
=> Variável não utllizada gerando erro.

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaBimestralHtmlParaPdf/GerarRelatorioAtaBimestralHtmlParaPdfCommandHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Data/Models/NotaConceitoBimestreComponente.cs, src/SME.SR.Infra/Enumeradores/TipoConceito.cs, src/SME.SR.Workers.SGP/wwwroot/templates/RelatorioAtaBimestralComColunaFinal.html
[AB#90272](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90272)
=> 90272 - Ajustar relatório Ata bimestral

src/SME.SR.Application/Queries/ConselhoClasse/ObterRecomendacoesPorAlunosTurmas/ObterRecomendacoesPorAlunosTurmasQueryHandler.cs
[AB#96022](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96022)
=> fix/96022 -> r2

src/SME.SR.Application/Queries/ConselhoClasse/ObterRecomendacoesPorAlunosTurmas/ObterRecomendacoesPorAlunosTurmasQueryHandler.cs
[AB#96022](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96022)
=> fix/96022 -> master

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
[AB#96236](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96236)
=> 96236 - Ata final de resultados não traz todos os componentes curriculares

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs, src/SME.SR.Data/Models/NotaConceitoBimestreComponente.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#90270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90270)
=> 90270 - Ajustar Relatório Boletim Simples

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
[AB#96236](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96236)
=> Fix/96236 

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoEscolaAqui/ObterDadosMensagemEscolaAquiQueryHendler.cs, src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioBoletim/ObterNotasRelatorioBoletimQuery.cs, src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioBoletim/ObterNotasRelatorioBoletimQueryHandler.cs, src/SME.SR.Data/Models/NotaConceitoBimestreComponente.cs
[AB#90305](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90305)
=> 90305 - Ajustar Relatório Boletim Detalhado

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#96628](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96628)
=> fix/96628 -> r2

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCorpo.cshtml
[AB#96276](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96276)
=> fix/96276 -> master

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#95111](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95111)
=> Fix/95111 -> master

src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterTipoTurmaRegularParaEdFisica/ObterTipoTurmaRegularParaEdFisicaQuery.cs, src/SME.SR.Application/Queries/Turma/ObterTipoTurmaRegularParaEdFisica/ObterTipoTurmaRegularParaEdFisicaQueryHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RetornoNotaConceitoBimestreComponenteDto.cs
[AB#90274](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90274)
=> 90274 - Ajustar relatório de notas e conceitos finais

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#96628](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96628)
=> fix/96628 -> master

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#96942](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96942)
=> 96942 - Notas do bimestre 1 lançadas em SF

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#96647](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96647)
=> Fix/96647 -> r2

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs
[AB#97059](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97059)
=> 97059 - Ajustes componentes duplicados por alunos turma

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#96647](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96647)
=> fix/96647 -> master

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalHtmlParaPdf/GerarRelatorioAtaFinalHtmlParaPdfCommandHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioConselhoClasseAtaFinalUseCase.cs, src/SME.SR.Infra/Dtos/Relatorios/ConselhoClasseAtaFinal/ConselhoClasseAtaFinalGrupoDto.cs, src/SME.SR.Infra/Dtos/Relatorios/ConselhoClasseAtaFinal/FiltroConselhoClasseAtaFinalDto.cs, src/SME.SR.Workers.SGP/Views/RelatorioAtasComColunaFinal.cshtml
[AB#61111](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61111)
=> 61111 - justes nas colunas do relatório

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#97275](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97275)
=> Fix/97275 -> r2

src/SME.SR.Workers.SGP/Views/RelatorioAtasComColunaFinal.cshtml
[AB#61108](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61108)
=> 61108 - Data da situação deve ser impressa no campo de parecer 

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#97407](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97407)
=> 97407 - Apoio resolução bug relatório (conflito merge)

src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs
[AB#97407](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97407)
=> 97407 - Relatório de notas e conceito tratamento para chave não encontrada.

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#97070](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97070)
=> fix/97070 -> master

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Infra/Enumeradores/ParecerConclusivo.cs, src/SME.SR.Infra/Enumeradores/SituacaoMatriculaAluno.cs, src/SME.SR.Workers.SGP/Views/RelatorioAtasComColunaFinal.cshtml
[AB#61112](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61112)
=> 61112 - Coluna parecer e legendas

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#97275](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97275)
=> fix/97275 -> master

src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseTurma/ObterRelatorioConselhoClasseTurmaQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseAlunoRepository.cs, src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
[AB#96218](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96218)
=> Fix/96218 > r2

src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseTurma/ObterRelatorioConselhoClasseTurmaQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseAlunoRepository.cs, src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
[AB#96218](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96218)
=> fix/96218 -> master

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#96716](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96716)
=> Fix/96716 -> r2

src/SME.SR.Application/Commands/AlteracaoNotas/ObterDadosRelatorioAlteracaoNotas/ObterDadosRelatorioAlteracaoNotasCommandHandler.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs, src/SME.SR.Infra/Dtos/HistoricoAlteracaoNotas/HistoricoAlteracaoNotasDto.cs
[AB#97946](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97946)
=> 97946 - Relatorio de alteração de notas não está trazendo conceito

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#98022](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98022)
=> 98022 - Boletim ciclo final e complementar incorreto

src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RetornoNotaConceitoBimestreComponenteDto.cs
[AB#98128](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98128)
=> 98128 - Nota saindo incorretamente

src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioAtaBimestral/ObterNotasRelatorioAtaBimestralQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#98138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98138)
=> 98138 - Tratar para obter do consolidado

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#98292](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98292)
=> 98292 - Tratamento ordenação de nome componentes de regencia relatório

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#98249](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98249)
=> 98249 - Aluno inativo antes do ano letivo não deveria exibir na ata

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#98354](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98354)
=> Ordenar alunos em ordem alfabética

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/ConselhoClasseAtaFinal/ConselhoClasseAtaFinalComponenteDto.cs, src/SME.SR.Infra/Dtos/Relatorios/ConselhoClasseAtaFinal/ConselhoClasseAtaFinalGrupoDto.cs
[AB#98237](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98237)
=> 98237 - Ordenação componentes Ata Final pelo nome por grupo

src/SME.SR.Workers.SGP/Views/RelatorioAtasComColunaFinal.cshtml
[AB#98357](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98357)
=> 98357 - Ata gerando página em branco

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalExcelCommand/GerarRelatorioAtaFinalExcelCommandHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalExcel/ObterRelatorioConselhoClasseAtaFinalExcelQueryHandler.cs
[AB#98379](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98379)
=> Ajuste da cor cinza no EXCEL

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Data/Queries/TurmaConsultas.cs
[AB#98090](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98090)
=> Fix/98090 -> master

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#98634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98634)
=> Fix/98634 -> r2

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#98634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98634)
=> ajuste Fix/98634 -> r2

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#96627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96627)
=> Fix/96627 -> r2

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#96627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96627)
=> Complemento Fix/96627 -> r2

src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#98481](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98481)
=> O componente informática não tem atribuição

src/SME.SR.Application/Queries/ConselhoClasse/ObterRecomendacoesPorAlunosTurmas/ObterRecomendacoesPorAlunosTurmasQueryHandler.cs, src/SME.SR.Infra/Utilitarios/UtilHtml.cs
[AB#98506](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98506)
=> 98506 - Boletim exibindo caracteres especiais

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#99031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99031)
=> fix/99031 -> r2

src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs
[AB#95562](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95562)
=> fix/95562 -> r2

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#96627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96627)
=> fix/96627 -> master

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#99031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99031)
=> fix/99031 -> master

src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs, src/SME.SR.Infra/Enumeradores/TipoPendencia.cs
[AB#92332](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92332)
=> 92332 - Adicionar nova pendência na consulta do relatório de pendências

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#99365](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99365)
=> 99365 - Saindo estudantes que ficaram inativos antes do começo do ano

src/SME.SR.Application/Queries/NotaConceito/ObterTiposNotaRelatorioBoletim/ObterTiposNotaRelatorioBoletimQueryHandler.cs
[AB#99749](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99749)
=> fix/99749 -> r2

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioBoletim/ObterFrequenciasRelatorioBoletimQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs, src/SME.SR.Data/Models/ComponenteCurricularPorTurma.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#96281](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96281)
=> Fix/96281 -> pre-prod

src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs
[AB#95562](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95562)
=> fix/95562 -> master

src/SME.SR.Application/Queries/NotaConceito/ObterTiposNotaRelatorioBoletim/ObterTiposNotaRelatorioBoletimQueryHandler.cs
[AB#99749](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99749)
=> fix/99749 -> pre-prod

src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs, src/SME.SR.Application/Queries/Arquivos/ObterHtmlComImagensBase64/ObterHtmlComImagensBase64QueryHandler.cs
[AB#98649](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98649)
=> fix/98649 -> r2

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#98634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98634)
=> Fix/98634 -> master

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#98634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98634)
=> fix/98634 -> pre-prod

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
=> Fix/99709 -> pre-prod

src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#99715](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99715)
=> fix/99715 -> pre-prod

src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs, src/SME.SR.Application/Queries/Arquivos/ObterHtmlComImagensBase64/ObterHtmlComImagensBase64QueryHandler.cs
[AB#98649](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98649)
=> Fix/98649 -> pre-prod

src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
=> fix/98078 -> pre-prod

src/SME.SR.Data/Repositories/Sgp/OcorrenciaRepository.cs
[AB#100854](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100854)
=> Fix/100854 - Ao selecionar todas as UE está dando erro ao gerar relatório.

src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
[AB#95982](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95982)
=> fix/95982 -> r2

src/SME.SR.Application/Queries/AtribuicaoCJ/ObterAtribuicoesCJPorFiltro/ObterAtribuicoesCJPorFiltroQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
[AB#95982](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95982)
=> fix/95982 -> r2 (pt.2)

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Data/Queries/TurmaConsultas.cs
[AB#101133](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101133)
=> Fix/101133 -> r2

src/SME.SR.Application/Queries/AtribuicaoCJ/ObterAtribuicoesCJPorFiltro/ObterAtribuicoesCJPorFiltroQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
[AB#95982](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95982)
=> Fix/95982 -> pre-prod

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#99699](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99699)
=> fix/99699 -> r2

src/SME.SR.Application/Interfaces/UseCases/IRelatorioPlanoAnualUseCase.cs, src/SME.SR.Application/Queries/PlanejamentoAnual/ObterObjetivosAprendizagemPlanejamentoAnual/ObterObjetivosAprendizagemPlanejamentoAnualQuery.cs, src/SME.SR.Application/Queries/PlanejamentoAnual/ObterObjetivosAprendizagemPlanejamentoAnual/ObterObjetivosAprendizagemPlanejamentoAnualQueryHandler.cs, src/SME.SR.Application/Queries/PlanejamentoAnual/ObterPlanejamentoAnual/ObterPlanoAnualQuery.cs, src/SME.SR.Application/Queries/PlanejamentoAnual/ObterPlanejamentoAnual/ObterPlanoAnualQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioPlanoAnualUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IPlanoAnualRepository.cs, src/SME.SR.Data/Repositories/Sgp/PlanoAnualRepository.cs, src/SME.SR.Infra/Dtos/PlanoAnual/BimestreDescricaoObjetivosPlanoAnualDto.cs, src/SME.SR.Infra/Dtos/PlanoAnual/ObjetivoAprendizagemPlanoAnualDto.cs, src/SME.SR.Infra/Dtos/PlanoAnual/PlanoAnualDto.cs, src/SME.SR.IoC/Dependencias.cs, src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
=> Criação do UseCase do relatório

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Data/Queries/TurmaConsultas.cs
=> Fix/101133 -> pre-prod

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs
=> fix/101172 -> r2

src/SME.SR.Workers.SGP/Views/RelatorioListagemOcorrencias.cshtml
=> 101760 - Quebra de caracteres incorreta.

src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/EncaminhamentoNaapaPaginado.cs
=> Fix/101775 -> r2

src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoRegistrosPedagogicos.cshtml
=> ajuste de layout

src/SME.SR.Data/Repositories/Sgp/OcorrenciaRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/ListagemOcorrencias/RelatorioListagemOcorrenciasRegistroDto.cs
[AB#102023](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/102023)
=> Relatório não estava imprimindo quando não tinha turma

src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoRegistrosPedagogicos.cshtml, src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoRegistrosPedagogicosInfantil.cshtml, src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoRegistrosPedagogicosInfantilComponente.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoRegistrosPedagogicosInfantil.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoRegistrosPedagogicosInfantilComponente.cshtml
=> Fix/98935 -> r2

src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralPorAnoEAlunos/ObterFrequenciasGeralPorAnoEAlunosQuery.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralPorAnoEAlunos/ObterFrequenciasGeralPorAnoEAlunosQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
=> fix/97325 -> r2

src/SME.SR.Data/Interfaces/ElasticSearch/Base/IRepositorioElasticBase.cs, src/SME.SR.Data/Interfaces/ElasticSearch/IRepositorioElasticTurma.cs, src/SME.SR.Data/Models/ElasticSearch/IndicesElastic.cs, src/SME.SR.Data/Repositories/ElasticSearch/Base/RepositorioElasticBase.cs, src/SME.SR.Data/Repositories/ElasticSearch/RepositorioElasticTurma.cs, src/SME.SR.Data/SME.SR.Data.csproj, src/SME.SR.Infra/Dtos/ElasticSearch/AlunoNaTurmaDTO.cs, src/SME.SR.Infra/Dtos/ElasticSearch/ComponenteTurmaDto.cs, src/SME.SR.Infra/Dtos/ElasticSearch/DocumentoElastic.cs, src/SME.SR.Infra/Dtos/ElasticSearch/DocumentoElasticTurma.cs, src/SME.SR.Infra/Dtos/ElasticSearch/TurmaComponentesDto.cs, src/SME.SR.Infra/SME.SR.Infra.csproj, src/SME.SR.IoC/ElasticsearchExtension.cs, src/SME.SR.Workers.SGP/Startup.cs
=> Elastic Search em SR

src/SME.SR.Application/Queries/Alunos/ObterInformacoesEscolaresAluno/ObterInformacoesEscolaresAlunoQueryHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralAlunoPorCodigoAnoSemestre/ObterFrequenciasGeralAlunoPorCodigoAnoSemestreQuery.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralAlunoPorCodigoAnoSemestre/ObterFrequenciasGeralAlunoPorCodigoAnoSemestreQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IRegistroFrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/RegistroFrequenciaAlunoRepository.cs
[AB#99649](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99649)
=> fix/99649 -> r2

src/SME.SR.Data/Models/ComponenteCurricularRegenciaApiEol.cs, src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#102058](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102058)
=> 102058 - Ata Final - Erro column "ehcompartilhada" does not exist

src/SME.SR.Data/Queries/TurmaConsultas.cs
[AB#102317](https://dev.azure.com/amcomgov/8217b3ef-9b0e-4b12-a2b0-a4fe910279ea/_workitems/edit/102317)
=> Exibindo o nome social

src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoRegistrosPedagogicos.cshtml, src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoRegistrosPedagogicosInfantil.cshtml, src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoRegistrosPedagogicosInfantilComponente.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoRegistrosPedagogicos.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoRegistrosPedagogicosInfantil.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoRegistrosPedagogicosInfantilComponente.cshtml
=> Fix/98935 -> pre-prod

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs
=> Fix/101774 -> pre-prod

src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/EncaminhamentoNaapaPaginado.cs
=> fix/101775 -> pre-prod

src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs
=> Fix/101172 -> pre-prod

src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#88748](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88748)
=> 88748 - Ajuste para retiradas de números mágicos.

src/SME.SR.Application/Queries/Alunos/ObterInformacoesEscolaresAluno/ObterInformacoesEscolaresAlunoQueryHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralAlunoPorCodigoAnoSemestre/ObterFrequenciasGeralAlunoPorCodigoAnoSemestreQuery.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralAlunoPorCodigoAnoSemestre/ObterFrequenciasGeralAlunoPorCodigoAnoSemestreQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IRegistroFrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/RegistroFrequenciaAlunoRepository.cs
[AB#99649](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99649)
=> fix/99649 -> pre-prod

src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
=> Fix/95288 -> pre-prod

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioCompensacaoAusenciaUseCase.cs
[AB#99661](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99661)
=> Fix/99661 -> r2

src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
[AB#95288](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95288)
=> fix/95288 -> r2

Jenkinsfile
=> master -> preprod

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/AlunoConselhoClasseCadastradoBimestres/AlunoConselhoClasseCadastradoBimestresQuery.cs, src/SME.SR.Application/Queries/ConselhoClasse/AlunoConselhoClasseCadastradoBimestres/AlunoConselhoClasseCadastradoBimestresQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseRepository.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseRepository.cs
[AB#102885](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102885)
=> fix/102885 -> r2

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
=> fix/99699 -> pre-prod

src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/AlunoConselhoClasseCadastradoBimestres/AlunoConselhoClasseCadastradoBimestresQuery.cs, src/SME.SR.Application/Queries/ConselhoClasse/AlunoConselhoClasseCadastradoBimestres/AlunoConselhoClasseCadastradoBimestresQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseRepository.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseRepository.cs
[AB#102885](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102885)
=> fix/102885 -> pre-prod

src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs, src/SME.SR.Data/Queries/AlunoConsultas.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
=> Fix/102979 -> master

src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#96348](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96348)
=> fix/96348 - >r2

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs
=> 103391 - Retirada do adicionar componentes do eja pois ja sendo incluido

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
=> 103371 - Parecer conclusivo incorreto para estudantes inativos

src/SME.SR.Data/Queries/AlunoConsultas.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#104180](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104180)
=> fix/104180 -> r2

src/SME.SR.Data/Queries/AlunoConsultas.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
=> fix/104180 -> master

src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
=> Fix/104406 -> r2

src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoFrequenciaGlobalMensal.cs
=> fix/99676 -> r2

src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoFrequenciaGlobalMensal.cs
[AB#99676](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99676)
=> fix/99676 -> pre-prod

src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#96348](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96348)
=> Fix/96348 -> pre-prod

src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/RegistroFrequenciaAlunoRepository.cs
[AB#99653](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99653)
=> Fix/99653 -> pre-prod

src/SME.SR.Application/UseCases/RelatorioPlanoAeeUseCase.cs
=> fix/104808 -> pre-prod

src/SME.SR.Application/Queries/Alunos/ObterAlunosPorTurmaDataSituacaoMatricula/ObterAlunosPorTurmaDataSituacaoMatriculaQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosPorTurmaDataSituacaoMatricula/ObterAlunosPorTurmaDataSituacaoMatriculaQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesCapLeituraPorTurmaQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterDataPeriodoFimSondagemPorBimestreAnoLetivo/ObterDataPeriodoFimSondagemPorBimestreAnoLetivoQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterPeriodoCompletoSondagemPorBimestre/ObterPeriodoCompletoSondagemPorBimestreQuery.cs, src/SME.SR.Application/Queries/Sondagem/ObterPeriodoCompletoSondagemPorBimestre/ObterPeriodoCompletoSondagemPorBimestreQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterPeriodoCompletoSondagemPorSemestre/ObterPeriodoCompletoSondagemPorSemestreQuery.cs, src/SME.SR.Application/Queries/Sondagem/ObterPeriodoCompletoSondagemPorSemestre/ObterPeriodoCompletoSondagemPorSemestreQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs, src/SME.SR.Data/Interfaces/Sondagem/IPeriodoSondagemRepository.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Data/Repositories/Sondagem/PeriodoSondagemRepository.cs, src/SME.SR.Infra/Dtos/Sondagem/PeriodoCompletoSondagemDto.cs
[AB#105254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105254)
=> fix/105254 -> r2

src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs
=> fix/96348 -> pre-prod (pt.2)

src/SME.SR.Application/Queries/Alunos/ObterAlunosPorTurmaDataSituacaoMatricula/ObterAlunosPorTurmaDataSituacaoMatriculaQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosPorTurmaDataSituacaoMatricula/ObterAlunosPorTurmaDataSituacaoMatriculaQueryHandler.cs, src/SME.SR.Application/Queries/Alunos/ObterTotalAlunosPorUeAnoSondagem/ObterTotalAlunosPorUeAnoSondagemQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterTotalAlunosPorUeAnoSondagem/ObterTotalAlunosPorUeAnoSondagemQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesCapLeituraPorTurmaQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterDataPeriodoFimSondagemPorBimestreAnoLetivo/ObterDataPeriodoFimSondagemPorBimestreAnoLetivoQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterPeriodoCompletoSondagemPorBimestre/ObterPeriodoCompletoSondagemPorBimestreQuery.cs, src/SME.SR.Application/Queries/Sondagem/ObterPeriodoCompletoSondagemPorBimestre/ObterPeriodoCompletoSondagemPorBimestreQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterPeriodoCompletoSondagemPorSemestre/ObterPeriodoCompletoSondagemPorSemestreQuery.cs, src/SME.SR.Application/Queries/Sondagem/ObterPeriodoCompletoSondagemPorSemestre/ObterPeriodoCompletoSondagemPorSemestreQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs, src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs, src/SME.SR.Data/Interfaces/Sondagem/IPeriodoSondagemRepository.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Data/Repositories/Sondagem/PeriodoSondagemRepository.cs, src/SME.SR.Infra/Dtos/Sondagem/PeriodoCompletoSondagemDto.cs
[AB#105254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105254)
=> Fix/105254 -> master

src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNAAPAUseCase.cs, src/SME.SR.Data/Repositories/Sgp/EncaminhamentoNAAPARepository.cs, src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoNAAPA/FiltroRelatorioEncaminhamentoNAAPADto.cs
[AB#102829](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102829)
=> Adicionando filtro de ids

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaBimestralHtmlParaPdf/GerarRelatorioAtaBimestralHtmlParaPdfCommandHandler.cs, src/SME.SR.HtmlPdf/IReportConverter.cs, src/SME.SR.HtmlPdf/PdfGenerator.cs
=> fix/105850 -> pre-prod

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterTurmasComplementaresEdFisica/ObterTurmasComplementaresEdFisicaQueryHandler.cs
=> fix/104962 -> pre-prod

src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoRespostaTextoEncaminhamentoNaapa.cs
[AB#106427](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106427)
=> fix/106427 -> r2

src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoRespostaTextoEncaminhamentoNaapa.cs
[AB#106427](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106427)
=> fix/106427 -> pre-prod

src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs, src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaFinal/ObterDadosComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterNotasFrequenciaComponenteComNotaFinal/ObterNotasFrequenciaComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioFrequenciaControleMensalUseCase.cs, src/SME.SR.Data/Models/FrequenciaAluno.cs, src/SME.SR.Data/Queries/FrequenciaAlunoConsultas.cs, src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FrequenciaAlunoConsolidadoDto.cs
[AB#92183](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92183)
=> Fix/92183 -> r2

src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs, src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaFinal/ObterDadosComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterNotasFrequenciaComponenteComNotaFinal/ObterNotasFrequenciaComponenteComNotaFinalQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs, src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioFrequenciaControleMensalUseCase.cs, src/SME.SR.Data/Models/FrequenciaAluno.cs, src/SME.SR.Data/Queries/FrequenciaAlunoConsultas.cs, src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FrequenciaAlunoConsolidadoDto.cs
=> Fix/92183 -> preprod

src/SME.SR.Data/Repositories/Sgp/ConselhoClasseAlunoRepository.cs
Ajuste na geração do relatório de ata de conselho de classe considerando o primeiro parecer registrado em banco conforme o conselho de classe.
=> Bug: 107925

src/SME.SR.Data/Queries/AlunoConsultas.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#108131](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108131)
=> fix/108131 -> r2

src/SME.SR.Data/Queries/AlunoConsultas.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
=> Fix/108131 -> pre-prod

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
Ajuste na definição do último bimestre em que o aluno inativo esteve na turma.
=> Bug: 107921

src/SME.SR.Data/Models/Turma.cs, src/SME.SR.Infra/Enumeradores/Modalidade.cs, src/SME.SR.Infra/Enumeradores/ModalidadeTipoCalendario.cs
=> 105235 - Modalidade Nova CELP

src/SME.SR.Data/Queries/ConselhoClasseAlunoConsultas.cs
Ajuste ao obter os pareceres conclusivos para ata final conforme o conselho de classe.
=> Bug: 107928

src/SME.SR.Application/Commands/AlteracaoNotas/ObterDadosRelatorioAlteracaoNotas/ObterDadosRelatorioAlteracaoNotasCommandHandler.cs, src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeAnalitico/GerarRelatorioControleGradeAnaliticoCommandHandler.cs, src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeSintetico/GerarRelatorioControleGradeSinteticoCommandHandler.cs, src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs, src/SME.SR.Application/Queries/Alunos/ObterInformacoesEscolaresAluno/ObterInformacoesEscolaresAlunoQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/DiarioBordo/ObterDadosPlanejamentoDiarioBordo/ObterDadosPlanejamentoDiarioBordoQueryHandler.cs, src/SME.SR.Application/Queries/DiarioBordo/ObterDadosPlanejamentoDiarioBordoComComponente/ObterDadosPlanejamentoDiarioBordoComComponenteQueryHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaAlunoGlobalPorComponentesBimestresETurmas/ObterFrequenciaAlunoGlobalPorComponentesBimestresETurmasQueryHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaAlunoGlobalPorComponetnesBimestresETurmas/ObterFrequenciaAlunoGlobalPorComponetnesBimestresETurmasQueryHandler.cs, src/SME.SR.Application/Queries/NotaConceito/ObterTiposNotaRelatorioBoletim/ObterTiposNotaRelatorioBoletimQueryHandler.cs, src/SME.SR.Application/Queries/PlanoAula/ObterPlanejamentoDiario/ObterPlanejamentoDiarioPlanoAulaQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs, src/SME.SR.Application/UseCases/RelatorioPlanoAnualUseCase.cs, src/SME.SR.Data/Repositories/Sgp/ConselhoClasseAlunoRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/Frequencia/FiltroRelatorioFrequenciasDto.cs, src/SME.SR.Infra/Enumeradores/Modalidade.cs, src/SME.SR.Infra/Utilitarios/UtilEnum.cs
=> 105236 - tratar regras para Modalidade e ModalidadeTipoCalendario

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFBoletimDetalhadoCommand/GerarRelatorioHtmlPDFBoletimDetalhadoCommandHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs, src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs, src/SME.SR.Application/Queries/NotaConceito/ObterTiposNotaRelatorioBoletim/ObterTiposNotaRelatorioBoletimQueryHandler.cs, src/SME.SR.Infra/Enumeradores/Modalidade.cs, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCabecalho.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoLista.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
=> 104259 - Tratar emissão de relatório de boletim simples e detalhado

src/SME.SR.Data/Repositories/Sgp/AcompanhamentoAprendizagemRepository.cs
Ajuste na consulta para obter acompanhamento turma desconsiderando registros excluídos ao gerar o RAA.
=> Bug: 109160

src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
=> 109534 - Boletim simples e detalhado está saindo sem a frequência global

src/SME.SR.Application/Queries/Alunos/ObterAlunosMatriculasPorTurmas/ObterAlunosMatriculasPorTurmasQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosMatriculasPorTurmas/ObterAlunosMatriculasPorTurmasQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs, src/SME.SR.Data/Interfaces/ElasticSearch/IRepositorioElasticTurma.cs, src/SME.SR.Data/Models/ElasticSearch/IndicesElastic.cs, src/SME.SR.Data/Repositories/ElasticSearch/RepositorioElasticTurma.cs, src/SME.SR.Infra/Dtos/ElasticSearch/AlunoNaTurmaDTO.cs, src/SME.SR.IoC/Dependencias.cs
=> fix/109041 -> r2

src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs, src/SME.SR.Data/Interfaces/ElasticSearch/IRepositorioElasticTurma.cs, src/SME.SR.Data/Repositories/ElasticSearch/RepositorioElasticTurma.cs
[AB#109313](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109313)
=> fix/109313 -> r2

src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
[AB#109751](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109751)
=> fix/109751 -> r2

src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
[AB#109751](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109751)
=> fix/109751 -> pre-prod

src/SME.SR.Application/Queries/ConselhoClasse/ObterNotaConceitoEducacaoFisicaNaEja/ObterNotaConceitoEducacaoFisicaNaEjaQueryHandler.cs, src/SME.SR.Application/Queries/NotaAluno/ObterTipoNotaPorTurma/ObterTipoNotaPorTurmaQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/FechamentoPendencias/RelatorioPendenciasDto.cs, src/SME.SR.Workers.SGP/Views/RelatorioAtasComColunaFinal.cshtml, src/SME.SR.Workers.SGP/Views/RelatorioPendencias.cshtml
=> 105191 - Tratar relatórios celp

src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosMatriculasPorTurmas/ObterAlunosMatriculasPorTurmasQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterAlunosMatriculasPorTurmas/ObterAlunosMatriculasPorTurmasQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs, src/SME.SR.Data/Interfaces/ElasticSearch/IRepositorioElasticTurma.cs, src/SME.SR.Data/Models/ElasticSearch/IndicesElastic.cs, src/SME.SR.Data/Repositories/ElasticSearch/RepositorioElasticTurma.cs, src/SME.SR.Infra/Dtos/ElasticSearch/AlunoNaTurmaDTO.cs, src/SME.SR.IoC/Dependencias.cs
=> Fix/109041 -> pre-prod

src/SME.SR.Data/Repositories/Sgp/ConselhoClasseNotaRepository.cs
Otimização da consulta para geração do relatório de notas e conceitos finais, com a intenção de um menor tempo de execução.
=> Bug: 110226

src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#109042](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109042)
=> Fix/109042 -> r2

src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/VerificarPercursoTurmaAlunoComImagemBase64/VerificarPercursoTurmaAlunoComImagemBase64Query.cs, src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/VerificarPercursoTurmaAlunoComImagemBase64/VerificarPercursoTurmaAlunoComImagemBase64QueryHandler.cs, src/SME.SR.Application/SME.SR.Application.csproj, src/SME.SR.Application/UseCases/RelatorioAcompanhamentoAprendizagemUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IAcompanhamentoAprendizagemRepository.cs, src/SME.SR.Data/Repositories/Sgp/AcompanhamentoAprendizagemRepository.cs, src/SME.SR.Infra/Dtos/AcompanhamentoAprendizagem/AcompanhamentoTurmaAlunoImagemBase64Dto.cs
Complemento do bug para verificação de imagem com codificação Base64 no RAA para percurso de turma e aluno, validando já a nível de banco de dados para não sobrecarregar a memória do servidor.
=> Bug: 110339

src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteSemNotaFinal/ObterDadosComponenteSemNotaFinalQueryHandler.cs
[AB#110576](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110576)
=> fix/110576 -> r2

src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
=> fix/109042 -> pre-prod

src/SME.SR.Data/Repositories/Sgp/EncaminhamentoNAAPARepository.cs
Incremento na validação da informação de ids no filtro do relatório de encaminhamento NAAPA verificando se a variávél é nula.
=> Bug: 110779

src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteSemNotaFinal/ObterDadosComponenteSemNotaFinalQueryHandler.cs, src/SME.SR.Data/Queries/FrequenciaAlunoConsultas.cs
[AB#110576](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110576)
=> Fix/110576 -> pre-prod

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
=> fix/111018 -> pre-prod

src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteSemNotaFinal/ObterDadosComponenteSemNotaFinalQueryHandler.cs, src/SME.SR.Data/Queries/FrequenciaAlunoConsultas.cs
[AB#110576](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110576)
=> Fix/110576 -> master

src/SME.SR.Infra/RelatorioPaginado/EncaminhamentoNaapa/SecaoRespostaTextoEncaminhamentoNaapa.cs
=> fix/111977 -> r2

src/SME.SR.Data/Queries/AlunoConsultas.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
=> fix/112062 -> master

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurma/ObterComponentesCurricularesPorCodigosTurmaQueryHandler.cs, src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs
Complemento do ajuste para considerar as informações dos componentes de regência quando impresso um bimestre específico.
=> Bug: 111264

src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Infra/Dtos/Turma/TurmaFiltradaUeCicloAnoDto.cs
=> fix/112500 -> master

src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterTurmasPorUeCicloAno/ObterTurmasPorUeCicloAnoQuery.cs, src/SME.SR.Application/Queries/Turma/ObterTurmasPorUeCicloAno/ObterTurmasPorUeCicloAnoQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/FiltroRelatorioParecerConclusivoDto.cs
=> Fix/111148 -> r2

src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs, src/SME.SR.Application/Queries/Turma/ObterTurmasPorUeCicloAno/ObterTurmasPorUeCicloAnoQuery.cs, src/SME.SR.Application/Queries/Turma/ObterTurmasPorUeCicloAno/ObterTurmasPorUeCicloAnoQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/FiltroRelatorioParecerConclusivoDto.cs
=> fix/111148 -> pre-prod

src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosPorCodigos/ObterDadosAlunosPorCodigosQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RelatorioNotasEConceitosFinaisAnoDto.cs, src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RelatorioNotasEConceitosFinaisBimestreDto.cs, src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RelatorioNotasEConceitosFinaisComponenteCurricularDto.cs, src/SME.SR.MVC/Controllers/RelatoriosController.cs
Ajuste na geração do relatório de notas e conceitos aplicando algumas otimizações, como a busca de alunos nos dados do EOL e popular os dados de DREs, UEs, alunos, disciplinas para impressão no relatório.
=> Bug: 113151

src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
=> fix/108315 -> r2

src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
=> fix/108315 -> master

src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesCapLeituraPorTurmaQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs, src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
=> 114021 - Ajuste IAD Portugues Consolidado

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
=> fix/114114 -> r2

src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraFiltroDto.cs
=> fix/113902 -> r2

src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraFiltroDto.cs
=> fix/113902 -> pre-prod

src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraFiltroDto.cs
=> fix/113902 -> master

src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Infra/Dtos/Turma/TotalDeTurmasPorAnoDto.cs
=> Fix/114114 -> pre-prod

src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs, src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Infra/Dtos/Turma/TotalDeTurmasPorAnoDto.cs
=> Fix/114114 -> master

src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs, src/SME.SR.Application/Queries/Ue/ObterUesPorDreSemestreModadalidadeAnoId/ObterUesPorDreSemestreModadalidadeAnoIdQuery.cs, src/SME.SR.Application/Queries/Ue/ObterUesPorDreSemestreModadalidadeAnoId/ObterUesPorDreSemestreModadalidadeAnoIdQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IUeRepository.cs, src/SME.SR.Data/Repositories/Sgp/UeRepository.cs
=> fix/114225 -> r2

src/SME.SR.Data/Repositories/Sgp/PlanoAeeVersaoRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/PlanoAEE/FiltroRelatorioPlanosAEEDto.cs
Ajuste na geração do relatório de plano AEE considerando o ano letivo selecionado no filtro e que é repassada para a rotina.
=> Bug: 113122

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
=> fix/113136 -> r2

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
=> fix/112922 -> r2

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#113136](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/113136)
=> fix/113136 -> pre-prod

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
[AB#112922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112922)
=> fix/112922 -> pre-prod

src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs, src/SME.SR.Application/Queries/Ue/ObterUesPorDreSemestreModadalidadeAnoId/ObterUesPorDreSemestreModadalidadeAnoIdQuery.cs, src/SME.SR.Application/Queries/Ue/ObterUesPorDreSemestreModadalidadeAnoId/ObterUesPorDreSemestreModadalidadeAnoIdQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IUeRepository.cs, src/SME.SR.Data/Repositories/Sgp/UeRepository.cs
=> Fix/114225 -> pre-prod

src/SME.SR.Application/Queries/DiasLetivos/ObterDiasLetivosPorPeriodoEscolares/ObterDiasLetivosPorPeriodoEscolaresQuery.cs, src/SME.SR.Application/Queries/DiasLetivos/ObterDiasLetivosPorPeriodoEscolares/ObterDiasLetivosPorPeriodoEscolaresQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioFrequenciaControleMensalUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IEventoRepository.cs, src/SME.SR.Data/Models/Evento.cs, src/SME.SR.Data/Repositories/Sgp/EventoRepository.cs, src/SME.SR.Infra/Dtos/FrequenciaMensal/ControleFrequenciaPorMesDto.cs, src/SME.SR.Infra/Dtos/FrequenciaMensal/DiaMesDto.cs
[AB#105242](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105242)
=> 105242 - Obter dias de semana com eventos

src/SME.SR.Application/Queries/Frequencia/ObterControleFrequenciaMensalParaExcel/ObterControleFrequenciaMensalParaExcelQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioFrequenciaControleMensalUseCase.cs, src/SME.SR.Infra/Dtos/FrequenciaMensal/ControleFrequenciaPorMesDto.cs
=> 105249 - Ajuste dias nao letivos

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatoricoControleDeFrequenciaMensalExcel/GerarRelatoricoControleDeFrequenciaMensalExcelCommandHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterControleFrequenciaMensalParaExcel/ObterControleFrequenciaMensalParaExcelQueryHandler.cs, src/SME.SR.Infra/Dtos/FrequenciaMensal/RelatorioControleFrequenciaMensalExcelDto.cs
=> 105250 - Ajuste no gerador de excel

src/SME.SR.Application/Queries/DiasLetivos/ObterDiasLetivosPorPeriodoEscolares/ObterDiasLetivosPorPeriodoEscolaresQueryHandler.cs, src/SME.SR.Application/Queries/DiasLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivosQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/EventoRepository.cs, src/SME.SR.Infra/Dtos/DiaLetivo/DiaLetivoDto.cs
=> 105342 - Ajuste em apresentação de dias não letivos em cinza relatório

src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoNAAPA/Detalhado/FiltroRelatorioEncaminhamentoNAAPADetalhadoDto.cs, src/SME.SR.Infra/Enumeradores/ImprimirAnexosNAAPA.cs
=> 112342 - Tratar DTOs geração relatório

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
=> Fix/109110 -> r2

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs, src/SME.SR.Workers.SGP/Views/RelatorioAtasComColunaFinal.cshtml
=> Fix/115011 -> pre-prod

src/SME.SR.HtmlPdf/SME.SR.HtmlPdf.csproj, src/SME.SR.HtmlPdf/UnificadorPdf.cs, src/SME.SR.HtmlPdf/UnificarPdfNAAPA.cs, src/SME.SR.Infra/Enumeradores/TipoArquivo.cs
[AB#112343](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112343)
=> Adicionar Lib PdfSharpCore e Classe de Unificação SR

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhado/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhadoCommand.cs, src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhado/GerarRelatorioHtmlPDFEncaminhamentoNaapaDetalhadoCommandHandler.cs, src/SME.SR.Application/Queries/EncaminhamentoNAAPA/ObterAnexosEncaminhamentoNAAPA/ObterAnexosEncaminhamentoNAAPAQuery.cs, src/SME.SR.Application/Queries/EncaminhamentoNAAPA/ObterAnexosEncaminhamentoNAAPA/ObterAnexosEncaminhamentoNAAPAQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNaapaDetalhadoUseCase.cs, src/SME.SR.Data/Interfaces/Sgp/IEncaminhamentoNAAPARespostaRepository.cs, src/SME.SR.Data/Repositories/Sgp/EncaminhamentoNAAPARespostaRepository.cs, src/SME.SR.HtmlPdf/UnificadorPdf.cs, src/SME.SR.HtmlPdf/UnificarPdfNAAPA.cs, src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoNAAPA/Detalhado/EncaminhamentoNAAPADto.cs, src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoNAAPA/Detalhado/RelatorioEncaminhamentoNAAPADetalhadoDto.cs
[AB#112344](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112344)
=> 112344 - Tratar busca anexos NAAPA e unificação relatório

src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultados/ObterComponentesCurricularesTurmasRelatorioAtaFinalResultadosQueryHandler.cs
=> fix/109110 -> pre-prod

src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoLista.cshtml
=> fix/114289 -> pre-prod

src/SME.SR.Infra/Enumeradores/TipoSondagem.cs
=> 115079 - Renomear os tipos de Sondagem de Lígua Portuguesa

src/SME.SR.Infra/Enumeradores/TipoSondagem.cs
=> 115079 - Alteração Matemática

src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs
=> Fix/116949 -> pre-prod

src/SME.SR.Application/Queries/PlanoAula/ObterPlanejamentoDiario/ObterPlanejamentoDiarioPlanoAulaQueryHandler.cs
=> fix/117095 -> master

src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesCapLeituraPorTurmaQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs, src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs, src/SME.SR.Infra/Enumeradores/GrupoSondagemEnum.cs
=> 117321 - Relatórios sondagem sem IAD

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
=> Fix/116805 -> pre-prod

src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
Ajuste para ata final, aplicando a visualização da situação em caso de inativo mesmo o aluno não possuindo conselho para nenhum bimestre.
=> Bug: 118202

src/SME.SR.Data/Repositories/Sgp/ParecerConclusivoRepository.cs
=> fix/118915 -> pre-prod

src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs, src/SME.SR.Data/Queries/AlunoConsultas.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
Ajuste na consulta para obter alunos ativos por turma e período considerando data de referência de inicio e fim de período com as datas de matrícula e situação dos alunos.
=> Bug: 119550

src/SME.SR.Application/UseCases/RelatorioEncaminhamentosNAAPAUseCase.cs, src/SME.SR.Data/Repositories/Sgp/EncaminhamentoNAAPARepository.cs, src/SME.SR.Infra/Dtos/Relatorios/EncaminhamentoNAAPA/FiltroRelatorioEncaminhamentoNAAPADto.cs
Ajuste na geração do relatório dinamico de encaminhamento NAAPA considerando corretamente os filtros informados.
=> Bug: 120361

src/SME.SR.Application/Interfaces/UseCases/IRelatorioPropostaLaudaDePublicacaoUseCase.cs, src/SME.SR.Application/UseCases/RelatorioPropostaLaudaDePublicacaoUseCase.cs, src/SME.SR.IoC/Dependencias.cs, src/SME.SR.Workers.SGP/Controllers/ConectaController.cs
=> 120077 - Criar endpont

src/SME.SR.Data/Repositories/Sgp/EncaminhamentoNAAPARepository.cs
Ajuste na geração do relatório NAAPA, incluindo tratamento quando o parâmetro de modalidades for nulo.
=> Bug: 120996

src/SME.SR.Application/Commands/Conecta/GerarRelatorioLaudaDePublicacaoDiretaDoc/GerarRelatorioLaudaDePublicacaoDiretaDocCommand.cs, src/SME.SR.Application/Commands/Conecta/GerarRelatorioLaudaDePublicacaoDiretaDoc/GerarRelatorioLaudaDePublicacaoDiretaDocCommandHandler.cs, src/SME.SR.Application/Commands/Conecta/GerarRelatorioLaudaDePublicacaoParceiraDoc/GerarRelatorioLaudaDePublicacaoParceiraDocCommand.cs, src/SME.SR.Application/Commands/Conecta/GerarRelatorioLaudaDePublicacaoParceiraDoc/GerarRelatorioLaudaDePublicacaoParceiraDocCommandHandler.cs, src/SME.SR.Application/UseCases/RelatorioPropostaLaudaDePublicacaoUseCase.cs, src/SME.SR.Data/Models/Conecta/Proposta.cs, src/SME.SR.Data/Models/Conecta/PropostaLocal.cs, src/SME.SR.Data/Repositories/Conecta/PropostaRepository.cs, src/SME.SR.Infra/Extensions/WordExtensions.cs, src/SME.SR.Infra/SME.SR.Infra.csproj, src/SME.SR.Infra/Word/AbstractGeradorArquivoDoc.cs, src/SME.SR.Infra/Word/PropriedadesWord.cs, src/SME.SR.Workers.SGP/Controllers/ConectaDownloadController.cs
=> 120080 - Layout do relatório e estrutura em word

src/SME.SR.Application/Interfaces/UseCases/IRelatorioPropostaLaudaCompletaUseCase.cs, src/SME.SR.Application/SME.SR.Application.csproj, src/SME.SR.Application/UseCases/RelatorioPropostaLaudaCompletaUseCase.cs, src/SME.SR.IoC/Dependencias.cs, src/SME.SR.Workers.SGP/Controllers/ConectaController.cs
=> 120027 - Criar endpont

src/SME.SR.Workers.SGP/Views/RelatorioBuscaAtiva.cshtml
Reverts prefeiturasp/SME-ServidorRelatorios#3378
=> Revert "Teste"

src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatoricoMapeamentosEstudantesExcel/GerarRelatorioMapeamentosEstudantesExcelCommandHandler.cs
=> 121581 - Ajuste colunas relastório para expandir todas

src/SME.SR.Application/UseCases/RelatorioBuscasAtivasUseCase.cs, src/SME.SR.Workers.SGP/Views/RelatorioBuscaAtiva.cshtml
=> 121900 - Ajuste apresentacao de obs apenas com filtro de aluno

src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGlobalPorAluno/ObterFrequenciaGlobalPorAlunoQuery.cs, src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGlobalPorAluno/ObterFrequenciaGlobalPorAlunoQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs, src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
Ajuste na geração do relatório de conselho de classe, incluindo um tratamento de nulo ao executar a consulta de frequência global.
=> Bug: 121682

src/SME.SR.Application/Commands/Conecta/GerarRelatorioLaudaDePublicacaoParceiraDoc/GerarRelatorioLaudaDePublicacaoParceiraDocCommandHandler.cs, src/SME.SR.Infra/Extensions/WordExtensions.cs
=> 122068 - Erro ao inserir url invalida

src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs
=>  Relatório Sondagem Componentes Por Turma

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Infra/Dtos/Ue/UePorDresIdResultDto.cs
Ajuste na geração do relatório analítico considerando UEs e turmas de acordo com o filtro selecionado, mesmo que essas não possuam registros de digitação no sondagem.
=> Bug: 119513

src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs
=> Feature 120343 - Sondagem - Relatório Matemática Consolidado

src/SME.SR.Application/Interfaces/IFabricaDeServicoAnaliticoSondagem.cs, src/SME.SR.Application/Interfaces/IServicoAnaliticoSondagemCapacidadeDeLeitura.cs, src/SME.SR.Application/Interfaces/IServicoAnaliticoSondagemCapacidadeDeLeituraTodosPreenchido.cs, src/SME.SR.Application/Interfaces/IServicoRepositorioAnalitico.cs, src/SME.SR.Application/Queries/Sondagem/ObterRelatorioAnaliticoSondagem/ObterRelatorioAnaliticoSondagemQueryHandler.cs, src/SME.SR.Application/Services/CapacidadeDeLeitura/ServicoAnaliticoSondagemCapacidadeDeLeitura.cs, src/SME.SR.Application/Services/CapacidadeDeLeitura/ServicoAnaliticoSondagemCapacidadeDeLeituraAbstract.cs, src/SME.SR.Application/Services/CapacidadeDeLeitura/ServicoAnaliticoSondagemCapacidadeDeLeituraTodosPreenchido.cs, src/SME.SR.Application/Services/FabricaDeServicoAnaliticoSondagem.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemAbstract.cs, src/SME.SR.Data/Interfaces/Sondagem/ISondagemAnaliticaRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.Infra/Constantes/Sondagem/RespostaDescricaoSondagem.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/ItemRespostaCapacidadeDeLeituraDto.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioAnalitico/RespostaSondagemAnaliticoCapacidadeDeLeituraDto.cs, src/SME.SR.IoC/Dependencias.cs
=> 120260 - SR - Analitico - Tratar relatório capacidade leitura

src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/UtilizarNovaOpcaoRespostaSemPreenchimento/UtilizarNovaOpcaoRespostaSemPreenchimentoQuery.cs, src/SME.SR.Application/Queries/Sondagem/UtilizarNovaOpcaoRespostaSemPreenchimento/UtilizarNovaOpcaoRespostaSemPreenchimentoQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs
=> Relatório Sondagem Português Por Turma

src/SME.SR.Application/Interfaces/IServicoAnaliticoSondagemEscrita.cs, src/SME.SR.Application/Queries/Sondagem/ObterRelatorioAnaliticoSondagem/ObterRelatorioAnaliticoSondagemQueryHandler.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemAbstract.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemEscrita.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemLeitura.cs, src/SME.SR.Data/Interfaces/Sondagem/ISondagemAnaliticaRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.IoC/Dependencias.cs
=> 120264 -  Tratar relatório escrita

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Infra/Dtos/Alunos/DadosAlunosEscolaDto.cs, src/SME.SR.Infra/Extensions/DateTimeMatriculaExtension.cs
Ajuste complementar na geração do relatório de frequência mensal considerando também o ano na verificação se o aluno está ativo no mês selecionado no filtro.
=> Bug: 121884

src/SME.SR.Application/Queries/ProdutividadeFrequencia/ObterProdutividadeFrequenciaPorFiltro/ObterObterProdutividadeFrequenciaPorFiltroQueryHandler.cs, src/SME.SR.Data/Repositories/Sgp/ConsolidacaoProdutividadeFrequenciaRepository.cs
[AB#115933](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115933)
=> 115933 - Ajuste nomes componentes territorio

src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs
[AB#120346](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120346)
=> Feature/120346 - Sondagem - Relatório Português Consolidado

src/SME.SR.Application/Interfaces/IServicoAnaliticoSondagemCampoAditivo.cs, src/SME.SR.Application/Queries/Sondagem/ObterRelatorioAnaliticoSondagem/ObterRelatorioAnaliticoSondagemQueryHandler.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemAbstract.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemCampoAditivo.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemCampoAditivoMutiplicativoAbstract.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemCapacidadeDeLeitura.cs, src/SME.SR.Infra/Constantes/Sondagem/RespostaDescricaoSondagem.cs, src/SME.SR.IoC/Dependencias.cs
[AB#120266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120266)
=> 120266 -  Tratar relatório campo aditivo

src/SME.SR.Application/Interfaces/IServicoAnaliticoSondagemNumeros.cs, src/SME.SR.Application/Queries/Sondagem/ObterRelatorioAnaliticoSondagem/ObterRelatorioAnaliticoSondagemQueryHandler.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemAbstract.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemCampoAditivoMutiplicativoAbstract.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemCapacidadeDeLeitura.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemEscrita.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemIADNumerosAbstract.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemLeitura.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemLeituraVozAlta.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemNumeros.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemProducaoDeTexto.cs, src/SME.SR.IoC/Dependencias.cs
[AB#120268](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120268)
=> 120268 -  Tratar relatório números

src/SME.SR.Application/Interfaces/IServicoAnaliticoSondagemIADMatematica.cs, src/SME.SR.Application/Queries/Sondagem/ObterRelatorioAnaliticoSondagem/ObterRelatorioAnaliticoSondagemQueryHandler.cs, src/SME.SR.Application/Services/ServicoAnaliticoSondagemIADMatematica.cs, src/SME.SR.Data/Interfaces/Sondagem/ISondagemAnaliticaRepository.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs, src/SME.SR.IoC/Dependencias.cs
[AB#120269](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120269)
=> 120269 - Tratar relatório IAD

src/SME.SR.Data/Queries/AlunoConsultas.cs, src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
Ajuste na geração do relatório analítico do sodagem, onde na consulta foram removidas tabelas desnecessárias, acertando os filtros. Tratamento de valor nulo ao tratar a quantidade de turmas no ano turma.
=> Bug: 122379

src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs
[AB#122448](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122448)
=> 122448 - Não está exibindo os dados do sem preenchimentos

src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs
[AB#122469](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122469)
=> 122469 - Não está sendo possível imprimir o relatório

src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#122473](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122473)
=> 122473 - Ajuste nome campo

src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioSondagemComponentesMatematicaNumerosAutoralConsolidadoDto.cs, src/SME.SR.Workers.SGP/Views/RelatorioSondagemComponentesMatematicaNumerosAutoralConsolidado.cshtml
[AB#122472](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122472)
=> 122472 - Total do relatório impresso de matemática

src/SME.SR.Data/Repositories/Sondagem/SondagemAnaliticaRepository.cs
[AB#122497](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122497)
=> 122497 - Dados apresentados no relatório analítico estão divergentes

src/SME.SR.Application/Queries/Sondagem/ObterDataPeriodoFimSondagemPorBimestreAnoLetivo/ObterDataPeriodoFimSondagemPorBimestreAnoLetivoQuery.cs, src/SME.SR.Application/Queries/Sondagem/ObterDataPeriodoFimSondagemPorBimestreAnoLetivo/ObterDataPeriodoFimSondagemPorBimestreAnoLetivoQueryHandler.cs, src/SME.SR.Application/Queries/Sondagem/ObterDataPeriodoFimSondagemPorSemestreAnoLetivo/ObterDataPeriodoFimSondagemPorSemestreAnoLetivoQuery.cs, src/SME.SR.Application/Queries/Sondagem/ObterDataPeriodoFimSondagemPorSemestreAnoLetivo/ObterDataPeriodoFimSondagemPorSemestreAnoLetivoQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioSondagemComponentesPorTurmaUseCase.cs, src/SME.SR.Application/UseCases/RelatorioSondagemMatConsolidadoAdtMultiUseCase.cs, src/SME.SR.Data/Interfaces/Sondagem/IPeriodoSondagemRepository.cs, src/SME.SR.Data/Repositories/Sondagem/PeriodoSondagemRepository.cs, src/SME.SR.IoC/Dependencias.cs
[AB#122472](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122472)
=> 122472 - Divergência de alunos digitação e relatório

src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs
[AB#122626](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122626)
=> 122626 - O campo sem preenchimento para 2023 duplicado.

src/SME.SR.Application/Services/ServicoAnaliticoSondagemAbstract.cs
[AB#122634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122634)
=> 122634 - tratamento de null para total de turmas

src/SME.SR.Data/Repositories/Sondagem/PerguntasAditMultiNumRepository.cs, src/SME.SR.Infra/Dtos/Relatorios/Sondagem/PerguntasAditMultNumDto.cs
[AB#122490](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122490)
=> 122490 - Erro2 - Relatório Matematica aditivo ou multi não abre para turma 3 ano

src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
[AB#122490](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122490) 
[AB#122688](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122688)
=> 122490 - Ajuste divergência calculo

src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommand.cs, src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommandHandler.cs, src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioNotasEConceitosFinaisUseCase.cs
[AB#121975](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121975) - Ajuste para relatório emitir por Dre quando filtro TODAS
=> 121975 - Ajuste para relatório emitir por Dre quando filtro TODAS

src/SME.SR.Workers.SGP/Views/RelatorioSondagemPortuguesCapacidadeLeituraPorTurma.cshtml
[AB#122601](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122601)
=> 122601 - Reduzindo tam fonte emc aso de resposta sem preenchimento

src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosEscola/ObterDadosAlunosEscolaQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioFrequenciaGlobalUseCase.cs
=> Ajuste performance

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioFrequenciaGlobalUseCase.cs
=> 123262 - Ajuste removendo segregação por dre

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
=> 123262 - Ajuste de qdade threads por var ambiente

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Application/UseCases/RelatorioFrequenciaGlobalUseCase.cs, src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/FiltroFrequenciaGlobalDto.cs
=> Log freq mensal

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Infra/Utilitarios/VariaveisAmbiente.cs
=> Ajuste qdade de threads

src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Infra/Fila/RotasRabbitSR.cs, src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
=> Tratamento aumento timeout consumer

src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
Ajuste na geração do relatório de frequência mensal, alterando a consulta de busca de alunos considerando o código da turma e desconsiderando matrículas com vínculo indevido.
=> Bug: 123368

src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
Ajuste no filtro de validação dos registros retornados pela consulta de pendências ao gerar o relatório, não considerando a flag outras pendências casos os registros sejam do tipo AEE.
=> Bug: 123367

src/SME.SR.Data/Repositories/Sondagem/SondagemRelatorioRepository.cs
[AB#123449](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/123449)
=> 123319 - Ajuste IAD matematica

src/SME.SR.Application/Services/ServicoAnaliticoSondagemLeitura.cs
Ajuste ao relatório analítico de leitura sondagem
=> Ajuste ao relatório analítico de leitura sondagem

src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosEscola/ObterDadosAlunosEscolaQuery.cs, src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosEscola/ObterDadosAlunosEscolaQueryHandler.cs, src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs, src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs, src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs, src/SME.SR.Infra/Dtos/Alunos/DadosMatriculaAlunoDto.cs
Substitui o uso de DadosAlunosEscolaDto por DadosMatriculaAlunoDto em consultas e manipuladores relacionados a dados de matrícula de alunos. Adiciona a classe DadosMatriculaAlunoDto, atualiza as interfaces e implementações do repositório e ajusta a lógica relacionada para melhorar a consistência e oferecer suporte a informações de matrícula mais enxutas.
=> Refatora consulta do rel frequencia mensal
