prefeiturasp/SME-ServidorRelatorios

- src/SME.SR.Infra/Dtos/Relatorios/BoletimEscolar/BoletimEscolarAlunoDto.cs
> Tipo Nota Default

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegencia/ObterComponentesCurricularesRegenciaQueryHandler.cs
- src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs
- src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaFinal/ObterDadosComponenteComNotaFinalQueryHandler.cs
- src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs
- src/SME.SR.Application/Queries/NotaConceito/ObterTipoNota/ObterTipoNotaQuery.cs
- src/SME.SR.Application/Queries/NotaConceito/ObterTipoNota/ObterTipoNotaQueryHandler.cs
- src/SME.SR.Application/Queries/Turma/ObterTurma/ObterTurmaQueryHandler.cs
- src/SME.SR.Data/Models/ComponenteComNota.cs
- src/SME.SR.Data/Models/ComponenteComNotaFinal.cs
- src/SME.SR.Data/Models/ComponenteRegenciaComNota.cs
- src/SME.SR.Data/Models/ComponenteRegenciaComNotaBimestre.cs
- src/SME.SR.Data/Models/ComponenteRegenciaComNotaFinal.cs
- src/SME.SR.Data/Models/DreUe.cs
- src/SME.SR.Data/Models/RelatorioConselhoClasseBase.cs
- src/SME.SR.Data/Models/Turma.cs
- src/SME.SR.Data/Queries/TurmaConsultas.cs
> Ajustes dto conselho classe

- src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs
- src/SME.SR.Data/Models/DreUe.cs
- src/SME.SR.Data/Models/Turma.cs
> Ajustes cabeçalho conselho

- src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaFinal/ObterDadosComponenteComNotaFinalQueryHandler.cs
> Ajuste obter tiponota e eheja relatorio final conselho classe

- src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs
> Ajuste parecer conclusivo conselho aluno

- src/SME.SR.Reports/Sgp/RelatorioHistoricoEscolar/dados.json
> Inclusão do json do relatório de histórico escolar

- src/SME.SR.Application/UseCases/RelatorioConselhoClasseAtaFinalUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseNotaRepository.cs
[AB#19661](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/19661)
> 19661 - Correção da query de carga de notas do conselho de Classe;

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarCodigoCorrelacaoSGP/GerarCodigoCorrelacaoSGPCommand.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarCodigoCorrelacaoSGP/GerarCodigoCorrelacaoSGPCommandHandler.cs
- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
- src/SME.SR.Infra/Fila/RotasRabbit.cs
Adicionando fila no sgp para copiar comando;
> Adicionando command para copiar um código de correlação

- src/SME.SR.Application/UseCases/RelatorioConselhoClasseAtaFinalUseCase.cs
[AB#19926](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/19926)
> 19926 - Corrigido tratamento de erro na emissão do relatório por turma

- src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/RelatorioParecerConclusivoAlunoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/RelatorioParecerConclusivoAnoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/RelatorioParecerConclusivoCicloDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/RelatorioParecerConclusivoDreDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/RelatorioParecerConclusivoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/RelatorioParecerConclusivoUeDto.cs
> Implementação de DTO para o relatório de parecer conclusivo

- src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommandHandler.cs
- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatarioFaltasFrequenciasExcel/ObterRelatorioFaltasFrequenciasExcelQuery.cs
- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatarioFaltasFrequenciasExcel/ObterRelatorioFaltasFrequenciasExcelQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioFaltasFrequenciasUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/Excel/RelatorioFaltasExcelDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/Excel/RelatorioFaltasFrequenciasBaseExcelDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/Excel/RelatorioFaltasFrequenciasExcelDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/Excel/RelatorioFrequenciasExcelDto.cs
> Transformação de dados para relatório de faltas e frequencia excel

- src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs
> Ajuste na exibição do AnoLetivo

- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
> Ajuste na query para considerar alunos ativos

- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFaltasFrequenciaPdf/ObterRelatorioFaltasFrequenciaPdfQueryHandler.cs
- src/SME.SR.Workers.SGP/Views/RelatorioFaltasFrequencias.cshtml
[AB#19981](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19981)
> Ajuste na renderização do relatório

- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
> story/18770 - ajustes

- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQuery.cs
- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/HistoricoEscolarDto.cs
[AB#21521](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21521)
> Adicionado dados data e responsaveis UE Historico Fund/Medio

- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs
- src/SME.SR.Infra/Dtos/Funcionario/FuncionarioDto.cs
[AB#22219](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22219)
> Ajuste formatação documento responsaveis ue

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#22192](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22192)
> Inclusão cidade e estado natal - dados aluno

- src/SME.SR.Application/UseCases/RelatorioNotasEConceitosFinaisUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/NotasEConceitosFinais/FiltroRelatorioNotasEConceitosFinaisDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RetornoNotaConceitoBimestreComponenteDto.cs
- src/SME.SR.Infra/Enumeradores/TipoNota.cs
Ajuste na forma de filtrar notas;
Ajustes nos filtros;
> ajustes relatórios notas e conceitos

- src/SME.SR.Application/UseCases/RelatorioNotasEConceitosFinaisUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseNotaRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RetornoNotaConceitoBimestreComponenteDto.cs
[AB#22397](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22397)
> Ajuste filtro sintese relatório notas/conceitos final

- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/BaseNacionalComumTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/ComponentesCurricularesTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/EnriquecimentoCurricularTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/GrupoComponentesComNotaTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/HistoricoEscolar.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/HistoricoTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/ProjetosAtividadesComplementaresTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/dados.json
- src/SME.SR.Reports/Sgp/HistoricoEscolarFundamental/HistoricoEscolar.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarFundamental/dados.json
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/BaseNacionalComumTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/ComponentesCurricularesTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/EnriquecimentoCurricularTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/GrupoComponentesComNotaTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/HistoricoEscolar.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/HistoricoTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/ProjetosAtividadesComplementaresTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/dados.json
[AB#22445](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22445)
> 22445 - Histórico de tranferência, Eja e Médio

- src/SME.SR.Application/UseCases/RelatorioNotasEConceitosFinaisUseCase.cs
[AB#22966](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22966)
> Ajuste filtro tipo nota

- src/SME.SR.Application/UseCases/RelatorioNotasEConceitosFinaisUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RelatorioNotasEConceitosFinaisDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioNotasEConceitosFinais.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioNotasEConceitosFinais.cshtml
[AB#22965](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22965) [AB#23107](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23107) [AB#23067](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23067)
> 22965 - Notas finais legenda de notas fechamento

- src/SME.SR.Application/UseCases/RelatorioNotasEConceitosFinaisUseCase.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioNotasEConceitosFinais.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioNotasEConceitosFinais.cshtml
[AB#23168](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23168)
> Ajustes layout

- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#23167](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23167)
> Ajuste busca turmas transferencia

- src/SME.SR.Application/Queries/HistoricoEscolar/ObterAlunosETurmasHistoricoEscolar/ObterAlunosETurmasHistoricoEscolarQueryHandler.cs
[AB#23197](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23197)
> Ajuste obter as turmas dos alunos

- src/SME.SR.Application/UseCases/RelatorioRecuperacaoParalelaUseCase.cs
[AB#23180](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23180)
> Correção da ordenação

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterListaComponentesCurriculares/ObterListaComponentesCurricularesQuery.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterListaComponentesCurriculares/ObterListaComponentesCurricularesQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFaltasFrequenciaPdf/ObterRelatorioFaltasFrequenciaPdfQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioConselhoClasseTurmaUseCase.cs
- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#23608](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/23608)
> 23608 - carga de componentes do EOL considerando Componente "Pai"

- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
[AB#23667](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23667)
> Ajuste obter histórico aluno sem parecer

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalExcelCommand/GerarRelatorioAtaFinalExcelCommandHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#24695](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24695)
> Correções ata final

- src/SME.SR.Workers.SGP/Views/RelatorioResumosPAP.cshtml
ajustando tabela frequência [AB#24254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24254)
> ajustando tabela frequencia

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurma/ObterFrequenciasGeralAlunosNaTurmaQuery.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurma/ObterFrequenciasGeralAlunosNaTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#24695](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24695)
> Correções totais frequencia

- src/SME.SR.Application/UseCases/RelatorioResumoPAPUseCase.cs
Verificando quando não há retorno e notificar o usuário no relatóriode pap
> mensagem-relatorio-pap

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalExcelCommand/GerarRelatorioAtaFinalExcelCommandHandler.cs
[AB#25256](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25256)
> Ajustes titulo excel relatorio ata final

- src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioSondagemComponentesPorTurmaPlanilhaQueryDto.cs
[AB#25880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25880)
> Ajustes no endpoint para satisfazer a busca de dados do relatório de matemática por números

- src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IRelatorioSondagemComponentePorTurmaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioSondagemComponentesPorTurmaPlanilhaQueryDto.cs
[AB#25926](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25926)
> Adaptações no código para atender relatório sondagem matemática autoral

- src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/Sondagem/ObterOrdensSondagemPorAnoProficiencia/ObterOrdensSondagemPorAnoProficienciaQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioSondagemComponentesPorTurmaOrdemRespostasDto.cs
[AB#25979](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25979)
> Ajustes finais e correções do relatório

- src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs
[AB#25987](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25987)
> Ajustando para caso a resposta seja nula, informar vazio

- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
[AB#26122](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26122)
> Ajuste query busca sondagem

- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraCabecalhoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraPlanilhaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraPlanilhaLinhaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraRelatorioDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
[AB#26154](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26154) [AB#26153](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26153)
> Criação dos DTOs para o Backend e Frontend juntamente com o mock de dados no MVC

- src/SME.SR.Data/Repositories/Sgp/PlanoAulaRepository.cs
[AB#18013](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/18013)
> 25767 - Ajuste na query de objetivos de aprendizagem da aula

- src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraCabecalhoDto.cs
[AB#26393](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26393)
> Adicionando Turma = Todas no cabeçalho

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#26505](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26505)
> Ajuste timeout busca quantidade alunos dre/sme

- src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQueryHandler.cs
[AB#26597](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26597)
> Ajuste ordenação ordem consolidado matematica adit e mult

- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesConsolidadoRepository.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.Workers.SGP/Controllers/SondagemController.cs
[AB#24778](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24778)
> Alteração de tabela fonte Sondagem Consolidado e correções do merge

- src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesConsolidadoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraPlanilhaRespostaDto.cs
- src/SME.SR.Workers.SGP/Views/RelatorioSondagemPortuguesConsolidadoCapacidadeLeitura.cshtml
[AB#26551](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26551)
> Correção de bugs do relatório para adequar à história

- src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesConsolidadoLeituraQueryHandler.cs
- src/SME.SR.Application/Queries/Sondagem/ObterOrdensSondagemPorGrupo/ObterOrdensSondagemPorGrupoQuery.cs
- src/SME.SR.Application/Queries/Sondagem/ObterOrdensSondagemPorGrupo/ObterOrdensSondagemPorGrupoQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs
- src/SME.SR.Data/Interfaces/Sondagem/ISondagemOrdemRepository.cs
- src/SME.SR.Data/Repositories/Sondagem/SondagemAutoralRepository.cs
- src/SME.SR.Data/Repositories/Sondagem/SondagemOrdemRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/SondagemOrdemDto.cs
- src/SME.SR.IoC/Dependencias.cs
[AB#26159](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26159)
> Adição de totalizadores no relatório AB#26159

- src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesConsolidadoRepository.cs
[AB#26672](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26672)
> Correção de BUG quando DRE ou UE igual a Todas

- src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesPorTurmaQuery.cs
- src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesPorTurmaQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IRelatorioSondagemPortuguesPorTurmaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesPorTurmaRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesPorTurmaFiltroDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesPorTurmaRespostaDto.cs
[AB#26731](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26731)
> Correção de relatório Leitura em Voz Alta AB#26731

- src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeSintetico/GerarRelatorioControleGradeSinteticoCommandHandler.cs
[AB#26700](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26700)
> Correção do Bug, Ajuste no Commam passando o parametro : Relatório Controle de Grade Sintético

- src/SME.SR.Workers.SGP/Views/RelatorioControleGradeSintetico.cshtml
[AB#26836](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26836)
> 26836 - Incluso descrição "Componente" no cabeçalho Rel Controle Grade

- src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesPorTurmaRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesPorTurmaPerguntaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesPorTurmaPlanilhaQueryDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesPorTurmaRespostaDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
[AB#26821](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26821) [AB#26816](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26816)
> Ajuste da fonte de dados para correção do relatório leitura em voz alta

- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesPorTurmaRepository.cs
[AB#26816](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26816)
> Correção do relatório de Leitura e Escrita AB#26821

- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
[AB#26882](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26882)
> Correção de relatórios de matemática sem dados após merge com dev

- src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQueryHandler.cs
[AB#26904](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26904)
> Removido validação para geração do relatório sem dados registrados

- src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeSintetico/GerarRelatorioControleGradeSinteticoCommandHandler.cs
- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
- src/SME.SR.Infra/Dtos/Ue/UeDto.cs
[AB#26901](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26901)
> 26901 - Incluso TipoEscola no header do Rel ControleGrade Sintético

- src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeSintetico/GerarRelatorioControleGradeSinteticoCommandHandler.cs
- src/SME.SR.Application/Queries/Aula/ObterAulasPrevistasDadas/ObterAulasPrevistasDadasQuery.cs
- src/SME.SR.Application/Queries/Aula/ObterAulasPrevistasDadas/ObterAulasPrevistasDadasQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IAulaPrevistaBimestreRepository.cs
- src/SME.SR.Data/Repositories/Sgp/AulaPrevistaBimestreRepository.cs
> 26958 - Corrigido query de aulas previstas x dadas

- src/SME.SR.Application/Queries/Eventos/ObterEventosPorTipoCalendarioIdQuery.cs
[AB#27284](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/27284)
> 27284 - Correção filtro de Eventos da Ue

- src/SME.SR.Data/Repositories/Sondagem/PerguntasAutoralRepository.cs
[AB#27300](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27300) [AB#27142](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27142)
> 27300 - Corrigir ordenação das colunas de respostas do relatorio de capacidade de leitura

- src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesCapLeituraPorTurmaQueryHandler.cs
[AB#27617](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27617) [AB#27577](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27577)
> 27617 - Imprimir alunos com suas situações

- src/SME.SR.Application/Queries/RelatorioSondagemPortugues/ObterRelatorioSondagemPortugues/ObterRelatorioSondagemPortuguesCapLeituraPorTurmaQueryHandler.cs
[AB#27823](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27823)
> Ajuste respostas sem preenchimento

- src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesPorTurmaRelatorioDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/Views/Relatorios/Graficos/GraficoBarras.cshtml
- src/SME.SR.MVC/Views/Relatorios/RelatorioSondagemPortuguesCapacidadeLeituraPorTurma.cshtml
- src/SME.SR.MVC/Views/Relatorios/RelatorioSondagemPortuguesPorTurma.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioSondagemPortuguesPorTurma.cshtml
[AB#27516](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27516)
> 27516 - Impressão gráfico de barras Leitura e Escrita

- src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
[AB#27871](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27871)
> Ajuste sem preenchimento

- src/SME.SR.Data/Repositories/Sondagem/SondagemAutoralRepository.cs
[AB#27882](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27882)
> Ajuste query todas dres

- src/SME.SR.MVC/Views/Relatorios/RelatorioSondagemPortuguesConsolidado.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioSondagemPortuguesConsolidado.cshtml
[AB#28072](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28072) [AB#27990](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27990)
> 28072 - Tirar porcentagem total dos relatorios de produção de texto - impressão

- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesConsolidadoRepository.cs
[AB#28115](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28115) [AB#28139](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28139)
> 28115 - Ajuste query capacidade de leitura consolidado

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#28112](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28112) [AB#28156](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28156)
> 28112 - Correção querry alunos sem preenchimento

- src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesConsolidadoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/SondagemPortugues/RelatorioSondagemPortuguesConsolidadoLeituraRelatorioDto.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioSondagemPortuguesConsolidadoCapacidadeLeitura.cshtml
- src/SME.SR.MVC/Views/Relatorios/RelatorioSondagemPortuguesPorTurma.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioSondagemPortuguesConsolidadoCapacidadeLeitura.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioSondagemPortuguesPorTurma.cshtml
[AB#28070](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28070)
> 28070 - Gráficos por turma leitura e escrita e ajuste capacidade de leitura

- src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs
[AB#28373](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28373) [AB#28387](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28387)
> 28373 - Impressão de opções sem preenchimento para números

- src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioSondagemPortuguesPorTurmaUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/PerguntaRespostaConsolidadoMatematicaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioSondagemComponentesMatematicaNumerosAutoralConsolidadoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioSondagemComponentesPorTurmaOrdemRespostasDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioSondagemComponentesPorTurmaPlanilhaQueryDto.cs
- src/SME.SR.Workers.SGP/Views/RelatorioSondagemComponentesMatematicaNumerosAutoralConsolidado.cshtml
[AB#28477](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28477)
Relatorio Escrita por turma, ordenação ajustada
Números consolidados
Matematica Autoral Consolidado e por turma
> 28477 - Graficos Matemática

- src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs
[AB#28373](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28373)
> 28373 - Ajustes tratamentos de dados

- src/SME.SR.MVC/Views/Relatorios/RelatorioUsuarios.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioUsuarios.cshtml
[AB#28559](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28559)
> correção do bug - Relatório de Usuários - Problemas no leiaute

- src/SME.SR.Application/Commands/Notificacao/GerarRelatorioNotificacao/GerarRelatorioNotificacaoCommandHandler.cs
[AB#28809](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/28809)
> 28809 - Incluso código da UE no relatório

- src/SME.SR.Application/Commands/RelatorioUsuarios/ObterDadosRelatorioUsuarios/ObterDadosRelatorioUsuariosCommandHandler.cs
[AB#28561](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/28561)
> 28561 - Removido perfis DRE/Ue quando usuário selecionar Todas UEs

- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFaltasFrequenciaPdf/ObterRelatorioFaltasFrequenciaPdfQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/FiltroRelatorioFaltasFrequenciasDto.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioFaltasFrequencias.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioFaltasFrequencias.cshtml
… Inclusão de parâmetro no dto e ajuste da verificação da condição para todos os estudantes
> Manutenção no filtro de condições do relatório

- src/SME.SR.Data/Repositories/Sgp/UsuarioRepository.cs
- src/SME.SR.Workers.SGP/Views/RelatorioUsuarios.cshtml
[AB#28913](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28913)
> Correção de query e ajuste no tratamento dos perfis na montagem do layout

- src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQuery.cs
- src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/Turma/ObterTurmasRelatorioBoletim/ObterTurmasRelatorioBoletimQuery.cs
- src/SME.SR.Application/Queries/Turma/ObterTurmasRelatorioBoletim/ObterTurmasRelatorioBoletimQueryHandler.cs
Ajuste na funcionalidade de emitir o boletim considerando a flag de histórico.
> Bug: 28438

- src/SME.SR.Workers.SGP/Views/RelatorioUsuarios.cshtml
[AB#29145](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/29145)
> 29145 - Alterado Header "Data" do Relatório de Usuarios

- src/SME.SR.Application/Queries/Usuarios/UsuarioPossuiSenhaPadrao/UsuarioPossuiSenhaPadraoQueryHandler.cs
[AB#29182](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/29182)
> 29182 - Corrigido senha padrão

- src/SME.SR.Application/Queries/HistoricoReinicioSenhaUsuario/ObterHistoricoReinicioSenhaUsuarioPorDreQueryHandler.cs
[AB#29144](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/29144)
> 29144 - Remoção de perfil vazio do histórico de reinicio de senha

- src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs
- src/SME.SR.Application/Queries/Turma/ObterTurmasPorUeCicloAno/ObterTurmasPorUeCicloAnoQuery.cs
- src/SME.SR.Application/Queries/Turma/ObterTurmasPorUeCicloAno/ObterTurmasPorUeCicloAnoQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ParecerConclusivoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#28445](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28445)
> Ajuste filtro ano letivo busca turmas relatório parecer conclusivo

- src/SME.SR.Application/Queries/HistoricoReinicioSenhaUsuario/ObterHistoricoReinicioSenhaUsuarioPorDreQueryHandler.cs
[AB#29144](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/29144)
> 29144 - Corrigido remoção de usuários sem perfil

- src/SME.SR.Application/Commands/RelatorioUsuarios/ObterDadosRelatorioUsuarios/ObterDadosRelatorioUsuariosCommandHandler.cs
[AB#29393](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/29393)
> 29393 - Correção da listagem de usuarios da UE

- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemPortuguesPorTurmaRepository.cs
[AB#29383](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29383) [AB#29189](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29189)
> 29383 - Ajustes relatório impresso consolidado pt - leitura e escrita

- src/SME.SR.Application/Queries/Alunos/ObterDadosHistoricoAlunosPorCodigos/ObterDadosHistoricoAlunosPorCodigosQuery.cs
- src/SME.SR.Application/Queries/Alunos/ObterDadosHistoricoAlunosPorCodigos/ObterDadosHistoricoAlunosPorCodigosQueryHandler.cs
- src/SME.SR.Application/Queries/Ue/ObterUesConclusao/ObterUesConclusaoQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#29149](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29149)
> Ajuste busca histórico ues conclusão aluno

- src/SME.SR.Application/UseCases/RelatorioGraficoPAPUseCase.cs
[AB#29482](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29482)
> Ajuste geração relatório sem resultados

- src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQueryHandler.cs
- src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs
[AB#29562](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29562)
> Ajuste ordenação respostas multiplicativo e numeros

- src/SME.SR.Application/Queries/HistoricoReinicioSenhaUsuario/ObterHistoricoReinicioSenhaUsuarioPorDreQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/UsuarioRepository.cs
- src/SME.SR.Workers.SGP/Views/RelatorioUsuarios.cshtml
[AB#29401](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/29401)
> 29401 - Ajuste colunas do relatório para aproveitar espaço

- src/SME.SR.Application/Commands/AlteracaoNotas/ObterDadosRelatorioAlteracaoNotas/ObterDadosRelatorioAlteracaoNotasCommandHandler.cs
[AB#29809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29809)
Ajuste gerar mensagem de Nenhuma informação para os filtros informados.
> Relatorio alteração notas 

- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCj/AtribuicaoCjDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCj/AtribuicaoCjProfessorDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCj/AtribuicaoCjTurmaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCj/AtribuicaoEsporadicaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCj/ProfessorAtribuicaoCjPorTurmaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCj/RelatorioAtribuicaoCjDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCj/TurmaAtribuicaoCjPorProfessorDto.cs
[AB#28028](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28028) [AB#29628](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29628)
> 28028/29628 - Dto relatorio atribuicao CJ

- src/SME.SR.Infra/Utilitarios/VariaveisAmbiente.cs
[AB#29901](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29901)
> Adicionando variavel para a Conexão ao AE

- src/SME.SR.MVC/Views/Relatorios/Graficos/GraficoBarras.cshtml
- src/SME.SR.Workers.SGP/Views/Graficos/GraficoBarras.cshtml
> 29909 - Ajuste no gráfico

- src/SME.SR.Application/Commands/AlteracaoNotas/ObterDadosRelatorioAlteracaoNotas/ObterDadosRelatorioAlteracaoNotasCommandHandler.cs
- src/SME.SR.Data/Repositories/Sgp/FechamentoNotaRepository.cs
[AB#29809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29809)
> verificação de lista vazia para retornar mensagem de dados não encontrados

- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCj/AtribuicaoCjAulaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCj/AtribuicaoCjProfessorDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
[AB#28029](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28029)
> Ajuste dto aulas

- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/Views/Relatorios/Graficos/GraficoBarras.cshtml
- src/SME.SR.Workers.SGP/Views/Graficos/GraficoBarras.cshtml
[AB#29974](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29974) [AB#29689](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29689)
> 29974 - Ajustes, troca de span por tag p

- src/SME.SR.Workers.SGP/Views/RelatorioHistoricoAlteracoesNotas.cshtml
[AB#29809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29809)
> Ajuste no layout para contagem de caracteres nos campos de nome

- src/SME.SR.Application/Commands/RelatorioUsuarios/ObterDadosRelatorioUsuarios/ObterDadosRelatorioUsuariosCommandHandler.cs
- src/SME.SR.Data/Repositories/Sgp/UsuarioRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/Usuario/DadosUsuarioDto.cs
- src/SME.SR.Workers.SGP/Views/RelatorioUsuarios.cshtml
[AB#30290](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30290)
> 30290 - Alteração no layout

- src/SME.SR.Workers.SGP/Views/RelatorioUsuarios.cshtml
[AB#30289](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30289)
> Ajuste na quebra de seção, quando é ultimo registro e não é quebra de pagina

- src/SME.SR.Workers.SGP/Views/RelatorioUsuarios.cshtml
[AB#30289](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30289)
> Ajuste no layout para corrigir quebra de linha quando lista somente perfis SME

- src/SME.SR.Application/Queries/AtribuicaoCJ/ObterAtribuicoesCJPorFiltro/ObterAtribuicoesCJPorFiltroQuery.cs
- src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IAtribuicaoCJRepository.cs
- src/SME.SR.Data/Repositories/Sgp/AtribuicaoCJRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/AtribuicaoCJ/FiltroRelatorioAtribuicaoCJDto.cs
[AB#30367](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30367)
> Ajuste modalidade opcional

- src/SME.SR.Data/Repositories/Sgp/AtribuicaoCJRepository.cs
[AB#30365](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30365)
> Ajuste filtros todas dre e ue

- src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioAtribuioesCj.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAtribuioesCj.cshtml
[AB#30407](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30407)
[AB#30408](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30408)
> 30407 - Ajustes RF e Modalidade quando informada

- src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
[AB#30407](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30407) [AB#30408](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30408)
> ajuste retirar rf

- src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
[AB#30421](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30421)
> Ajuste nome professor relatório

- src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
[AB#30481](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30481)
> Ajuste nome professor cj

- src/SME.SR.Application/Queries/Comunicado/ObterDadosLeituraComunicados/ObterDadosLeituraComunicadosQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IComunicadosRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ComunicadosRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/LeituraComunicados/LeituraComunicadoTurmaDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.Workers.SGP/Views/RelatorioEscolaAquiLeituraComunicados.cshtml
[AB#29980](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29980)
> 29980 - Refatorado para adicionar os dados do app

- src/SME.SR.Data/Repositories/Sgp/FechamentoNotaRepository.cs
[AB#30384](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30384)
> 30384 - Ajuste query historico notas para trazer apenas o ultimo aprovador

- src/SME.SR.Infra/Utilitarios/VariaveisAmbiente.cs
- src/SME.SR.Workers.SGP/Views/RelatorioFaltasFrequencias.cshtml
[AB#30965](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30965)
> 30965 - Corrigido Título da Pagina

- src/SME.SR.Application/Queries/Comunicado/ObterDadosLeituraComunicados/ObterDadosLeituraComunicadosQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/ComunicadosRepository.cs
- src/SME.SR.Workers.SGP/Views/RelatorioEscolaAquiLeituraComunicados.cshtml
[AB#30972](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30972)
> 30972 - Corrigido bugs

- src/SME.SR.Application/Queries/Comunicado/ObterDadosLeituraComunicados/ObterDadosLeituraComunicadosQueryHandler.cs
- src/SME.SR.Workers.SGP/Views/RelatorioEscolaAquiLeituraComunicados.cshtml
[AB#30972](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30972) - Quebra de página e relatório sem aluno
> 30972 - Quebra de página e relatório sem aluno

- src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
- src/SME.SR.Infra/Utilitarios/VariaveisAmbiente.cs
[AB#30975](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30975)
> Ajuste nome prof cj

- src/SME.SR.Application/Queries/AE/ObterListaRelatorioAdessaoAE/ObterListaRelatorioAdessaoAEQueryHandler.cs
[AB#30514](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30514) [AB#30916](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30916)
> 30514 - Ajuste estudantes válidos

- src/SME.SR.Application/UseCases/RelatorioAtribuicaoCJUseCase.cs
[AB#31009](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31009)
> Ajuste agrupamento por turma/modalidade

- src/SME.SR.Data/Repositories/Sgp/ComunicadosRepository.cs
[AB#31156](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31156)
> 31156 - Adicionado espaçamento que estava concatenando a query

- src/SME.SR.Workers.SGP/Views/RelatorioEscolaAquiLeituraComunicados.cshtml
[AB#31156](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31156)
> 31156 - Corrigido datas

- src/SME.SR.Application/Commands/RelatorioUsuarios/ObterDadosRelatorioUsuarios/ObterDadosRelatorioUsuariosCommandHandler.cs
[AB#31012](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31012)
> Tratamento na impressão do registro de ultimo acesso quando não tiver registro de acesso ao SPG

- src/SME.SR.Application/UseCases/RelatorioPlanejamentoDiarioUseCase.cs
[AB#31573](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31573)
> 31573 - Corrigido turma no header do relatório

- src/SME.SR.Application/Queries/DiarioBordo/ObterDadosPlanejamentoDiarioBordo/ObterDadosPlanejamentoDiarioBordoQueryHandler.cs
- src/SME.SR.Application/Queries/PlanoAula/ObterPlanejamentoDiario/ObterPlanejamentoDiarioPlanoAulaQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/DiarioBordoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/PlanoAulaRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/AulaDiarioBordoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/AulaPlanoAulaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/PlanejamentoDiarioDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/PlanejamentoDiarioInfantilDto.cs
- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiario.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiarioInfantil.cshtml
[AB#31739](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31739)
> 31739 - Incluso indicativo de AulaCJ no rel planejamento diario

- src/SME.SR.Application/Commands/RelatorioUsuarios/ObterDadosRelatorioUsuarios/ObterDadosRelatorioUsuariosCommandHandler.cs
- src/SME.SR.Data/Repositories/Sgp/UsuarioRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/Usuario/DadosUsuarioDto.cs
[AB#31753](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31753)
> Ajuste dados de ultimo acesso quando vem nulo

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/TipoCalendarioRepository.cs
Complementação do ajuste de remoção de validação de turmas sem conselho no relatório de ata final para capturar a exceção.
> Bug: 29819

- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiario.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiarioInfantil.cshtml
[AB#31736](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31736)
> Ajuste layout correção de quebras

- src/SME.SR.Application/Commands/AlteracaoNotas/ObterDadosRelatorioAlteracaoNotas/ObterDadosRelatorioAlteracaoNotasCommandHandler.cs
- src/SME.SR.Workers.SGP/Properties/launchSettings.json
[AB#32166](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32166)
> Ajuste verificação de informação em aluno e ajuste no launchSettings.json

- src/SME.SR.Workers.SGP/Views/RelatorioHistoricoAlteracoesNotas.cshtml
[AB#32240](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32240)
> Ajuste layout para ambiente de hom

- src/SME.SR.Infra/Dtos/HistoricoAlteracaoNotas/HistoricoAlteracaoNotasDto.cs
[AB#32356](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32356)
> Ajuste atributos de long para double

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
Ajuste na funcionalidade de impressão de boletim, aumentando o timeout da query para obter dados de alunos.
> Bug: 32297

- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
[AB#32700](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32700) - Alterado para utilizar o alunosTodos ao inves do alunosTurmas
> fix/32700 

- src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeSintetico/GerarRelatorioControleGradeSinteticoCommandHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesEolPorIds/ObterComponentesCurricularesEolPorIdsQuery.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesEolPorIds/ObterComponentesCurricularesEolPorIdsQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQuery.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegencia/ObterComponentesCurricularesRegenciaQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegenciaPorCodigosTurma/ObterComponentesCurricularesRegenciaPorCodigosTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioBoletim/ObterComponentesCurricularesTurmasRelatorioBoletimQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioFechamentoPedenciasQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioCompensacaoAusenciaUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioPlanejamentoDiarioUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioPlanoAulaUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IComponenteCurricularRepository.cs
- src/SME.SR.Data/Models/ComponenteCurricular.cs
- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
- src/SME.SR.Infra/Dtos/ComponenteCurricular/DisciplinaDto.cs
[AB#32751](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32751)
Ajuste para buscar os componentes curriculares da base sgp e filtrar com os do eol adicionando o grupo matriz
> Ajuste para buscar os componentes curriculares na base Sgp

- src/SME.SR.Application/Queries/ConselhoClasse/ObterRelatorioConselhoClasseAluno/ObterRelatorioConselhoClasseAlunoQueryHandler.cs
- src/SME.SR.Reports/Sgp/RelatorioConselhoClasse/ConselhoClasse.jrxml
[AB#32987](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32987)
> 32987 - Ajuste da DRE e título do relatório

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
Ajuste no boletim para considerar as notas e frequência de síntese .
> Bug: 33070

- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
[AB#27671](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27671)
> 27671 - Adicionada modalidade que estava faltando

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQuery.cs
- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/ConselhoClasse/AlunoConselhoClasseCadastradoBimestres/AlunoConselhoClasseCadastradoBimestresQuery.cs
- src/SME.SR.Application/Queries/ConselhoClasse/AlunoConselhoClasseCadastradoBimestres/AlunoConselhoClasseCadastradoBimestresQueryHandler.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGlobalRelatorioBoletim/ObterFrequenciaGlobalRelatorioBoletimQuery.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGlobalRelatorioBoletim/ObterFrequenciaGlobalRelatorioBoletimQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseRepository.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Models/Aluno.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/BoletimEscolar/BoletimEscolarCabecalhoDto.cs
- src/SME.SR.Reports/Sgp/BoletimEscolar/RelatorioBoletim.jrxml
- src/SME.SR.Reports/Sgp/BoletimEscolarEja/RelatorioBoletim.jrxml
- src/SME.SR.Reports/Sgp/BoletimEscolarMedio/BoletimPrincipal.jrxml
- src/SME.SR.Reports/Sgp/BoletimEscolarMedio/RelatorioBoletim.jrxml
[AB#36840](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36840)
> 36840 - Implementada correções

- src/SME.SR.Application/Queries/Turma/ObterTurma/ObterTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/Turma/ObterTurmaPorCodigo/ObterTurmaPorCodigoQuery.cs
- src/SME.SR.Application/Queries/Turma/ObterTurmaPorCodigo/ObterTurmaPorCodigoQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioDevolutivasUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#36845](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36845)
> 36845 Corrigido consulta de Turma por Codigo

- src/SME.SR.Data/Repositories/Sgp/ParecerConclusivoRepository.cs
- src/SME.SR.Infra/Enumeradores/TipoTurma.cs
[AB#37195](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37195)
> CM - Adição de filtro de turmas regulares no parecer concluido

- src/SME.SR.Reports/Sgp/BoletimEscolarEja/BoletimPrincipal.jrxml
- src/SME.SR.Reports/Sgp/BoletimEscolarEja/ComponentesRegencia.jrxml
- src/SME.SR.Reports/Sgp/BoletimEscolarEja/GrupoComponenteCurricular.jrxml
- src/SME.SR.Reports/Sgp/BoletimEscolarEja/RelatorioBoletim.jrxml
[AB#36983](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36983)
> 36983 - Alterado relatório

- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
Reverts prefeiturasp/SME-ServidorRelatorios#861
> Revert "teste log"

- src/SME.SR.Application/Interfaces/UseCases/IRelatorioItineranciasUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioItineranciasUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/RegistroItinerancia/AlunoRegistroItineranciaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/RegistroItinerancia/FiltroRelatorioItineranciasDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/RegistroItinerancia/RegistrosRegistroItineranciaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/RegistroItinerancia/RelatorioRegistroItineranciaDto.cs
- src/SME.SR.IoC/Dependencias.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
[AB#37434](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37434)
> 37434 - Estrutura para emissão do Relatório de Itinerâncias

- src/SME.SR.Data/Repositories/Sgp/AulaPrevistaBimestreRepository.cs
Ajuste na query para o relatório de grade, onde alteramos um tipo de conversão feita.
> Bug: 37652

- jasper_server/app-entrypoint.sh
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAssincrono/GerarRelatorioAssincronoCommandHandler.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioHistoricoEscolar/ObterFrequenciasRelatorioHistoricoEscolarQuery.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioHistoricoEscolar/ObterFrequenciasRelatorioHistoricoEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/HistoricoEscolar/ObterAlunosETurmasHistoricoEscolar/ObterAlunosETurmasHistoricoEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioHistoricoEscolar/ObterNotasRelatorioHistoricoEscolarQuery.cs
- src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioHistoricoEscolar/ObterNotasRelatorioHistoricoEscolarQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#37863](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37863)
> CM - Criação de consultas específicas para o histórico e busca de turmas considerando o novo ensino médio.

- src/SME.SR.Workers.SGP/Controllers/RelatoriosSincronosSgpController.cs
[AB#37862](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37862)
> implementação do endpoint do Relatório de Itinerâncias Sincrono

- src/SME.SR.Application/Queries/HistoricoEscolar/ObterAlunosETurmasHistoricoEscolar/ObterAlunosETurmasHistoricoEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/HistoricoEscolar/ObterAlunosETurmasHistoricoEscolarTransferencia/ObterAlunosETurmasHistoricoEscolarTransferenciaQueryHandler.cs
- src/SME.SR.Application/Queries/Ue/ObterUesConclusao/ObterUesConclusaoQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#37982](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37982)
> Cm - Ajuste do histórico escolar para alunos transferidos.

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioHistoricoEscolar/ObterFrequenciasRelatorioHistoricoEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioHistoricoEscolar/ObterNotasRelatorioHistoricoEscolarQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Interfaces/Sgp/INotaConceitoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#37982](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37982)
> CM - Criação de queries específicas para histórico desconsiderando filtros se não forem informados.

- src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommand.cs
- src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommandHandler.cs
- src/SME.SR.Application/UseCases/RelatorioNotasEConceitosFinaisUseCase.cs
[AB#38056](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38056)
> Ajuste impressao nota fechamento relatorio notas e conceitos

- src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisExcel/ObterRelatorioNotasEConceitosFinaisExcelQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs
[AB#38028](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38028)
> Ajuste ordenação relatório notas e conceitos

- src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#38107](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38107)
> Ajuste timeout query e descrição bimestre final

- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/.settings/org.eclipse.core.resources.prefs
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/AreasConhecimento.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/JasperReports_Server/GrupoComponentesComNota.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/dados.json
[AB#38090](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38090)
> 38090 - Layout hisótico Novo Ensino Médio

- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/.settings/org.eclipse.core.resources.prefs
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/BaseNacionalComumTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/ComponentesCurricularesTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/EstudosRealizados.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarEja/dados.json
[AB#38283](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38283)
> CM - Ajustes de layout no relatório de Histórico Eja

- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#38311](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38311)
> CM - Considerar anos anteriores para histórico.

- src/SME.SR.Application/Queries/Ue/ObterUesConclusao/ObterUesConclusaoQueryHandler.cs
[AB#38479](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38479)
> CM - Buscar estudos realizados apenas das turmas regulares.

- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#38618](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38618)
> 38618 - Corrigida query da transferência

- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs
[AB#38773](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38773)
> Ajuste verificação legenda

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQuery.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegenciaPorCodigosTurma/ObterComponentesCurricularesRegenciaPorCodigosTurmaQuery.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegenciaPorCodigosTurma/ObterComponentesCurricularesRegenciaPorCodigosTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesTurmasRelatorioBoletim/ObterComponentesCurricularesTurmasRelatorioBoletimQueryHandler.cs
- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarTransferencia/MontarHistoricoEscolarTransferenciaQuery.cs
- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarTransferencia/MontarHistoricoEscolarTransferenciaQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
- src/SME.SR.Data/Models/ComponenteCurricular.cs
- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#38771](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38771)
> Ajuste listagem componentes transferencia

- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarTransferencia/MontarHistoricoEscolarTransferenciaQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/BaseNacionalComumDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/BaseNacionalComumTransferenciaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/ComponenteCurricularHistoricoEscolarTransferenciaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/GruposComponentesCurricularesDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/GruposComponentesCurricularesTransferenciaDto.cs
[AB#38769](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38769)
> Ajuste somente exibir componentes com nota

- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs
[AB#38769](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38769)
> Ajuste historico escolar

- src/SME.SR.Application/Queries/Turma/ObterTurmasDetalhePorCodigo/ObterTurmasDetalhePorCodigoQuery.cs
- src/SME.SR.Application/Queries/Turma/ObterTurmasDetalhePorCodigo/ObterTurmasDetalhePorCodigoQueryHandler.cs
- src/SME.SR.Application/Queries/Ue/ObterUesConclusao/ObterUesConclusaoQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs
- src/SME.SR.Data/Models/Turma.cs
- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#38797](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38797)
> Ajuste estudos realizados magisterio 4 ano historico medio

- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarEJA/MontarHistoricoEscolarEJAQueryHandler.cs
- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolarTransferencia/MontarHistoricoEscolarTransferenciaQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/BaseNacionalComumEJADto.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/ComponenteCurricularHistoricoEscolarDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/ComponenteCurricularHistoricoEscolarEJADto.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/ComponenteCurricularHistoricoEscolarTransferenciaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/GruposComponentesCurricularesDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/HistoricoEscolar/GruposComponentesCurricularesEJADto.cs
[AB#38816](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38816)
> Ajuste historico escolar EJA

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#38807](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38807)
> 38807 - Correção na ordenação dos componentes

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Infra/Enumeradores/EtapaEnsino.cs
[AB#38808](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38808)
> 38808 - Adicionada checagem se é turma de magistério

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#38986](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38986)
> Corrigida informação de alunos que não possuem edfisica

- src/SME.SR.Application/UseCases/RelatorioConselhoClasseAtaFinalUseCase.cs
- src/SME.SR.Workers.SGP/wwwroot/templates/RelatorioAtasComColunaFinal.html
[AB#38807](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38807)
> Adicionado fluxo para inserir o parecer conclusivo

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#39000](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39000)
> Ajuste notificação erro ata final

- src/SME.SR.Data/Models/FrequenciaAluno.cs
- src/SME.SR.Data/Repositories/Sgp/AulaRepository.cs
[AB#38807](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38807) correção do percentual final de frequência
> 38955 - Sistema não imprime relatório corretamente

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/AcompanhamentoAprendizagemRepository.cs
- src/SME.SR.Infra/Dtos/AcompanhamentoAprendizagem/AcompanhamentoAprendizagemAlunoFotoDto.cs
- src/SME.SR.Infra/Dtos/AcompanhamentoAprendizagem/AcompanhamentoAprendizagemAlunoRetornoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoAprendizagem/RelatorioAcompanhamentoAprendizagemAlunoFotoDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoAprendizagem.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
[AB#39069](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39069)
> 39069 - Criado ajuste para adicionar as fotos dos alunos no relatório

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#38986](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38986)
> Ajuste busca turmas dos alunos

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurma/ObterFrequenciasGeralAlunosNaTurmaQuery.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurma/ObterFrequenciasGeralAlunosNaTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#39056](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39056)
> Ajuste obter frequencia global

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaComponenteGlobalPorTurma/ObterFrequenciaComponenteGlobalPorTurmaQuery.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaComponenteGlobalPorTurma/ObterFrequenciaComponenteGlobalPorTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#39092](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39092)
> Ajuste busca frequencia turma complementar

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#39098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39098)
> Ajuste ordenação componente curricular

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#39100](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39100)
> Ajuste bimestre nota final

- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/GrupoComponentesComNota.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/GrupoComponentesComNotaTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/HistoricoEscolar.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/HistoricoTransferencia.jrxml
- src/SME.SR.Reports/Sgp/HistoricoEscolarMedio/dados.json
[AB#39073](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39073) 
[AB#39116](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39116)
> 39073 - Ajustes quebra layout transferência

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#39092](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39092)
> Ajuste busca indices faltas final

- src/SME.SR.Application/UseCases/RelatorioDevolutivasUseCase.cs
[AB#39042](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39042)
> 39042 - Busca por turma ajustada

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#39098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39098)
> Ajuste ordenação componentes

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#39187](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39187)
> Ajuste filtro turma modalidades fundamental/eja

- src/SME.SR.Infra/Dtos/RegistroIndividual/RegistroIndividualRetornoDto.cs
- src/SME.SR.Infra/Utilitarios/UtilRegex.cs
[AB#39201](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39201)
> Ajuste na formatação do vídeo no campo texto

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalExcel/ObterRelatorioConselhoClasseAtaFinalExcelQueryHandler.cs
[AB#39260](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39260)
> Ajuste titulo grupo matriz excel

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#39319](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39319) - Adicionada verificação para exibir notas de usuário inativo até a data da situação do usuário
> 39319 - Adicionada checagem de data situação do usuário inativo

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#39337](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39337)
> Correção do value cannot be null

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarCodigoCorrelacaoSGP/GerarCodigoCorrelacaoSGPCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAssincrono/GerarRelatorioAssincronoCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalExcelCommand/GerarRelatorioAtaFinalExcelCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalHtmlParaPdf/GerarRelatorioAtaFinalHtmlParaPdfCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlParaPdfCommand/GerarRelatorioHtmlParaPdfCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/InserirFilaRabbit/InserirFilaRabbitCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/RetornarRelatorioPronto/RetornarRelatorioProntoCommandHandler.cs
- src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommandHandler.cs
- src/SME.SR.Application/UseCases/MonitorarStatusRelatorioUseCase.cs
- src/SME.SR.Infra/Dtos/Comum/Fila/PublicaFilaDto.cs
- src/SME.SR.Infra/Fila/FilaRabbit.cs
- src/SME.SR.Infra/Fila/RotasRabbit.cs
- src/SME.SR.Infra/Utilitarios/VariaveisAmbiente.cs
- src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
[AB#39651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39651)
> 39651 Removido rota Sgp.Clients e declarado a fila por Rota

- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioDevolutivas.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioDevolutivas.cshtml
[AB#39285](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39285) [AB#39679](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39679)
> 39285 - Ajuste quebra de layout

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFAcompAprendizagemCommand/GerarRelatorioHtmlPDFAcompAprendizagemCommand.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFAcompAprendizagemCommand/GerarRelatorioHtmlPDFAcompAprendizagemCommandHandler.cs
- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoAprendizagemUseCase.cs
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagemCabecalho.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagemCorpo.cshtml
> 39793 - Quebra utilizando cabecalho e corpo

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
- src/SME.SR.Infra/Dtos/AcompanhamentoAprendizagem/AcompanhamentoAprendizagemAlunoFotoDto.cs
- src/SME.SR.Infra/Utilitarios/VariaveisAmbiente.cs
[AB#39836](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39836)
> 39836 - Criada nova variável e ajustado modo de leitura base64

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
[AB#39836](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39836)
> Adicionada variáveis de ambiente no contrutor

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
[AB#39836](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39836)
> Corrigida pasta para obter as fotos do aluno

- src/SME.SR.Data/Repositories/Sgp/AcompanhamentoAprendizagemRepository.cs
[AB#39836](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39836)
> Corrigida query

- src/SME.SR.Data/Repositories/Sgp/ItineranciaRepository.cs
ajuste na consulta no servidor de relatórios para retirar consultas de itinerancia_ue
> ajuste na consulta

- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagemCorpo.cshtml
[AB#39813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39813)
> Ajuste na quebra de pagina

- src/SME.SR.Infra/Dtos/Alunos/AlunoRetornoDto.cs
[AB#39846](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39846)
> Ajuste formatação de telefone

- src/SME.SR.Application/Commands/Arquivos/TransformarBase64/TransformarArquivoBase64CommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFAcompAprendizagemCommand/GerarRelatorioHtmlPDFAcompAprendizagemCommandHandler.cs
- src/SME.SR.HtmlPdf/PdfGenerator.cs
[AB#39954](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39954)
> 39954 - Correção do garbage collector

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
- src/SME.SR.Application/Queries/Alunos/ObterAlunosPorTurmaAcompanhamentoApredizagem/ObterAlunosPorTurmaAcompanhamentoApredizagemQuery.cs
- src/SME.SR.Application/Queries/Alunos/ObterAlunosPorTurmaAcompanhamentoApredizagem/ObterAlunosPorTurmaAcompanhamentoApredizagemQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoAprendizagemUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoAprendizagem/FiltroRelatorioAcompanhamentoAprendizagemDto.cs
- src/SME.SR.IoC/Dependencias.cs
[AB#39954](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39954)
> Ajuste ao gerar relatório quando não tem acompanhamento e para ano anteriores

- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagemCorpo.cshtml
[AB#39949](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39949)
> Ajuste quebra de layout

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
- src/SME.SR.Infra/Dtos/AcompanhamentoAprendizagem/AcompanhamentoAprendizagemTurmaDto.cs
Correção do negrito que não estava pegando quando tinha mais de 1 aluno, refatoração do percurso.
> correção negrito

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
Ajuste na consulta de obter dados dos alunos por código, alterando a forma de implementação da lista de código de aluno por parâmetro que ocorria timeout, por sobrescrever um texto chave de identificação por uma lista texto.
> Bug: 39107

- src/SME.SR.Infra/Fila/RotasRabbit.cs
- src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
Normalizado Exchanges e queues com durables
Criado Exchange para Deadletter SGP Workers Relatorio
> Adicionando deadletter para todas as queues

- src/SME.SR.Workers.SGP/Dockerfile
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCabecalho.cshtml
> 41522 - ajustes no dockerfile para incluir a nova font

- src/SME.SR.Workers.SGP/SME.SR.Workers.SGP.csproj
> ajustado para adicionar as fonts

- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCabecalho.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCorpo.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoEJACorpo.cshtml
> Correção do layout nota-conceito

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#41561](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41561)
> Verificação existencia conselho classe

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
[AB#41529](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41529)
> Ajuste verificação componentes

- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCorpo.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoEJACorpo.cshtml
> ajuste na legenda

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFBoletimDetalhadoCommand/GerarRelatorioHtmlPDFBoletimDetalhadoCommandHandler.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#41604](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41604)
> Correção na ordenação dos alunos e numeração

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#41595](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41595)
> Ajuste busca alunos turma

- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCorpo.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoEJACorpo.cshtml
[AB#41614](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41614)
> Ajuste no tamanho para ler

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#41598](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41598)
> Ajuste montagem boletim nota sem conselho

- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#41583](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41583)
> Ajuste componente nao controla frequencia

- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCabecalho.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCorpo.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoEJACorpo.cshtml
[AB#41614](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41614)
> 41614 - ajustes nas recomendações

- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#41585](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41585)
> Ajuste bimestre futuro

- src/SME.SR.Workers.SGP/Dockerfile
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCabecalho.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCorpo.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoEJACorpo.cshtml
[AB#41614](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41614)
> 41614 - ajuste no layout

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAssincrono/GerarRelatorioAssincronoCommandHandler.cs
Ajuste na definição de exchange de relatórios ao montar os dados para publicação do item de requisição de geração na fila.
> Bug: 41526

- src/SME.SR.Data/Repositories/Sgp/PeriodoFechamentoRepository.cs
[AB#41585](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41585)
> Ordenacao periodo fechamento

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#41683](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41683)
> Ajuste busca alunos

- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#41680](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41680)
> Ajuste verificação conselho nota final

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFBoletimDetalhadoCommand/GerarRelatorioHtmlPDFBoletimDetalhadoCommandHandler.cs
- src/SME.SR.Workers.SGP/Dockerfile
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCabecalho.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoCorpo.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarDetalhadoEJACorpo.cshtml
- src/SME.SR.Workers.SGP/assets/fonts/fonts.css
> Corrigida quebra

- src/SME.SR.Application/UseCases/RelatorioControleGradeUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioPlanejamentoDiarioUseCase.cs
Inclusão da captura de exceção para o sentry nos relatórios de controle de grade e controle de planejamento diário.
> Bug: 42324

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterAcompanhamentoAprendizagemPorTurmaESemestre/ObterAcompanhamentoAprendizagemPorTurmaESemestreQueryHandler.cs
- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
- src/SME.SR.Application/Queries/ParametrosSistema/ObterParametroSistemaPorTipoAno/ObterParametroSistemaPorTipoAnoQuery.cs
- src/SME.SR.Application/Queries/ParametrosSistema/ObterParametroSistemaPorTipoAno/ObterParametroSistemaPorTipoAnoQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IParametroSistemaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/AcompanhamentoAprendizagemRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ParametroSistemaRepository.cs
- src/SME.SR.Infra/Dtos/AcompanhamentoAprendizagem/AcompanhamentoAprendizagemTurmaDto.cs
- src/SME.SR.Infra/Enumeradores/TipoParametroSistema.cs
- src/SME.SR.Infra/Utilitarios/UtilRegex.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/SME.SR.MVC.csproj
- src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoAprendizagem.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagemCorpo.cshtml
[AB#42072](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42072)
> 42072 - Ajustes Layout

- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoFechamento.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoFechamento.cshtml
[AB#41703](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41703) Leiaute html
> Feautre/41703 

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFAcompAprendizagemCommand/GerarRelatorioHtmlPDFAcompAprendizagemCommandHandler.cs
[AB#42812](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42812)
> Correção para geração de notificação de relatório pronto

- src/SME.SR.Data/Repositories/Sgp/AcompanhamentoAprendizagemRepository.cs
[AB#42923](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42923) [AB#42927](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42927)
> 42923 - correção impressão de percurso individual da criança

- src/SME.SR.Application/Queries/Turma/ObterTurmasPorAbrangenciaTiposFiltros/ObterTurmasPorAbrangenciaTiposFiltrosQuery.cs
- src/SME.SR.Application/Queries/Turma/ObterTurmasPorAbrangenciaTiposFiltros/ObterTurmasPorAbrangenciaTiposFiltrosQueryHandler.cs
- src/SME.SR.Application/Queries/Turma/ObterTurmasRelatorioAcompanhamentoFechamento/ObterTurmasRelatorioAcompanhamentoFechamentoQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/ITurmaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/TurmaRepository.cs
[AB#43210](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43210)
> Ajuste busca turmas relatorio acompanhamento fechamento

- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatarioFaltasFrequenciasExcel/ObterRelatorioFaltasFrequenciasExcelQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFaltasFrequenciaPdf/ObterRelatorioFaltasFrequenciaPdfQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioFaltasFrequenciasUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/FiltroRelatorioFaltasFrequenciasDto.cs
- src/SME.SR.Infra/Enumeradores/TipoRelatorioFaltasFrequencia.cs
[AB#43474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43474)
> Ajustes no DTO e UseCases para geração de relátorios

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFAcompAprendizagemCommand/GerarRelatorioHtmlPDFAcompAprendizagemCommandHandler.cs
- src/SME.SR.Data/Repositories/Sgp/AcompanhamentoAprendizagemRepository.cs
- src/SME.SR.Infra/Dtos/Arquivo/ArquivoDto.cs
[AB#43711](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43711)
> Fix:43711 master 2 - Ajustar id dto arquivo de Guid para Long

- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
Reformulação da consulta para obter notas dos alunos na impressão do boletim, pois anteriormente estava demorando para retornar o resultado causando timeout.
[AB#43043](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43043)
> Fix:43043 - [Back-SR] - Master

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
Ajuste na funcionalidade para gerar ata final de resultados alimentando os dados para o cálculo específico de 2020.
[AB#42223](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42223)
> Bug:42223 [Back-SR] - master

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFAcompAprendizagemCommand/GerarRelatorioHtmlPDFAcompAprendizagemCommandHandler.cs
[AB#44048](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44048)
> 44048 - Captura de erro

- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/Pdf/RelatorioFaltaFrequenciaAlunoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/Pdf/RelatorioFaltasFrequenciaDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
> Criadod Mock de RelatorioFaltasFrequencias

- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
Reformulação da consulta para obter notas dos alunos na impressão do boletim, pois anteriormente estava demorando para retornar o resultado causando timeout.
[AB#43043](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43043)
> Bug: 43043

- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatarioFaltasFrequenciasExcel/ObterRelatorioFaltasFrequenciasExcelQueryHandler.cs
[AB#43476](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43476)
> removido ifs não utilizados

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarCodigoCorrelacaoSGP/GerarCodigoCorrelacaoSGPCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAssincrono/GerarRelatorioAssincronoCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalExcelCommand/GerarRelatorioAtaFinalExcelCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalHtmlParaPdf/GerarRelatorioAtaFinalHtmlParaPdfCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFAcompAprendizagemCommand/GerarRelatorioHtmlPDFAcompAprendizagemCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFRegistroIndividualCommand/GerarRelatorioHtmlPDFRegistroIndividualCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlParaPdfCommand/GerarRelatorioHtmlParaPdfCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/RetornarRelatorioPronto/RetornarRelatorioProntoCommandHandler.cs
- src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommandHandler.cs
- src/SME.SR.Application/UseCases/MonitorarStatusRelatorioUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoAprendizagemUseCase.cs
- src/SME.SR.Infra/Fila/FilaRabbit.cs
- src/SME.SR.Infra/Interfaces/IServicoFila.cs
- src/SME.SR.Infra/Politicas/PoliticaPolly.cs
- src/SME.SR.Infra/SME.SR.Infra.csproj
- src/SME.SR.IoC/RegistrarPolicies.cs
- src/SME.SR.IoC/SME.SR.IoC.csproj
- src/SME.SR.Workers.SGP/Startup.cs
Aplicar resiliência para filas rabbit de relatório
[AB#43711](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43711) [AB#44048](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44048)
> Fix:44048 [Back SR] - master

- src/SME.SR.Data/Models/FrequenciaAluno.cs
[AB#44473](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44473)
> Ajuste no Relatório Ata final de resultado

- src/SME.SR.Application/Queries/Aula/ObterTotalAulasTurmaEBimestreEComponenteCurricular/ObterTotalAulasTurmaEBimestreEComponenteCurricularQuery.cs
- src/SME.SR.Application/Queries/Aula/ObterTotalAulasTurmaEBimestreEComponenteCurricular/ObterTotalAulasTurmaEBimestreEComponenteCurricularQueryHandler.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaComponenteGlobalPorTurma/ObterFrequenciaComponenteGlobalPorTurmaQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IRegistroFrequenciaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/RegistroFrequenciaRepository.cs
- src/SME.SR.IoC/Dependencias.cs
[AB#44473](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44473)
> Alteração no formato de obter as aulas

- src/SME.SR.Infra/Dtos/Relatorios/RegistroFrequencia/TurmaComponenteQtdAulasDto.cs
[AB#44473](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44473)
> classe não foi inserida

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaAluno/ObterFrequenciaAlunoQueryHandler.cs
[AB#44474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44474)
> adicionado total de aulas no relatório

- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatarioFaltasFrequenciasExcel/ObterRelatorioFaltasFrequenciasExcelQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/Excel/RelatorioFaltasExcelDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/Excel/RelatorioFaltasFrequenciasExcelDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FaltasFrequencia/Excel/RelatorioFrequenciasExcelDto.cs
[AB#45070](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/45070)
> Ajuste na Description do Dto

- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs
[AB#45082](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/45082)
> Ajuste no DefinirNomeBimestre

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/RegistroFrequenciaRepository.cs
[AB#44459](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44459)
> Alterado para obter os percentuais

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorTurma/ObterComponentesCurricularesPorTurmaQueryHandler.cs
[AB#44474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44474)
> atualizado componente curricular

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
[AB#44453](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44453)
> Correção de bimestres futuros

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQuery.cs
- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
- src/SME.SR.Application/Queries/ConselhoClasse/ObterDadosComponenteComNotaBimestre/ObterDadosComponenteComNotaBimestreQueryHandler.cs
- src/SME.SR.Application/Queries/Frequencia/ExisteFrequenciaRegistradaPorTurmaComponenteCurricular/ExisteFrequenciaRegistradaPorTurmaComponenteCurricularQuery.cs
- src/SME.SR.Application/Queries/Frequencia/ExisteFrequenciaRegistradaPorTurmaComponenteCurricular/ExisteFrequenciaRegistradaPorTurmaComponenteCurricularQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoAprendizagemUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#44501](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44501)
> Alterado para exibir em branco na frenquencia do relatório

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAssincrono/GerarRelatorioAssincronoCommand.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAssincrono/GerarRelatorioAssincronoCommandHandler.cs
- src/SME.SR.Application/UseCases/MonitorarStatusRelatorioUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioBoletimEscolarUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioConselhoClasseAlunoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioConselhoClasseTurmaUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioGamesUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/FiltroRelatorioDto.cs
- src/SME.SR.Infra/Fila/RotasRabbit.cs
[AB#44983](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44983)
> Ajustada filas de processamento para relatórios jasper

- src/SME.SR.Application/UseCases/RelatorioBoletimEscolarDetalhadoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioBoletimEscolarUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioConselhoClasseAlunoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioConselhoClasseAtaFinalUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioConselhoClasseTurmaUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioFrequenciasUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioNotasEConceitosFinaisUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioParecerConclusivoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioRegistroIndividualUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/FiltroRelatorioDto.cs
- src/SME.SR.Infra/Fila/RotasRabbit.cs
- src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
[AB#44983](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44983)
> Criado fila de erro

- src/SME.SR.Application/UseCases/RelatorioConselhoClasseAlunoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioConselhoClasseTurmaUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioGamesUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioResumoPAPUseCase.cs
[AB#44982](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44982)
> Adicionado Rotas de erro

- src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
[AB#46375](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46375)
> Alterações para funcionamento das rotas deadletter

- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoFechamentoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioLeituraComunicadosUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/ComunicadosRepository.cs
- src/SME.SR.Infra/Enumeradores/TipoEscola.cs
[AB#46391](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46391)
> ajustes na fila de relatorios

- src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#47262](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47262)
> Ajustes SQL

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IPendenciaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/FechamentoPendencias/FiltroRelatorioPendenciasDto.cs
[AB#47824](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47824)
> Ajustes criadorRf

- src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#47824](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47824)
> Ajustes no nome

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#47842](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47842)
> ajuste na chamada para notas das turmas

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
Ajuste no relatório de ata final para alunos com as situações "Ativo" ou "Concluído" serem exibidos como "Sem Parecer".
> Bug: 46878

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalExcelCommand/GerarRelatorioAtaFinalExcelCommandHandler.cs
[AB#47933](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47933)
> Ajuste nas cores cinzas para relatório

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
[AB#47940](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47940)
[AB#47938](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47938)
> Correção no relatório com informações divergentes no campo Turma

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalExcelCommand/GerarRelatorioAtaFinalExcelCommandHandler.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
[AB#47933](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47933)
> correção para alunos desistentes

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
[AB#47938](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47938)
[AB#47940](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47940)
> Ajustes no nome da Turma quando for todas as turmas

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaComponenteGlobalPorTurma/ObterFrequenciaComponenteGlobalPorTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#47923](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47923)
> ajuste do percentual e faltas

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#47971](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47971)
[AB#47968](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47968)
> Correção de Erro ao filtrar com RF especifico

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
Ajuste na impressão de boletim para considerar somente os alunos que possuem conselho de classe para não gerar em branco.
Ajuste na ordenação alfabética de nome das disciplinas impressas no boletim.
> Bug: 48001

- src/SME.SR.Data/Interfaces/Sgp/IPendenciaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#48372](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48372)
[AB#48152](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48152)
> Filtro por DRE UE outras pendencias

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
[AB#48408](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48408)
> Ajustes no nome da modalidade

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
[AB#48408](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48408)
> Ajustes para mais de uma modalidade

- src/SME.SR.Application/Commands/Arquivos/TransformarBase64/TransformarArquivoBase64CommandHandler.cs
- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/AcompanhamentoAprendizagemRepository.cs
Ajuste no relatório de acompanhamento de aprendizagen retornando o acompanhamento da turma independente dos  registros existentes de acompanhamento para os alunos.
> Bug: 47622

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#48426](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48426)
> Ajustes para outras pendencias

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
- src/SME.SR.Workers.SGP/Views/RelatorioPendencias.cshtml
> 37029 Removido instrução fixa

- src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#48534](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48534)
> Ajuste na query

- src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RetornoNotaConceitoBimestreComponenteDto.cs
Ajuste no relatório de notas e conceitos ajustando a observação se o aluno possui conselho de classe verificando se possui id de conselho no DTO de retorno.
> Bug: 48210

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/FechamentoPendencias/RelatorioPendenciasQueryRetornoDto.cs
[AB#48665](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48665)
> ajuste no agrupamento do detalhamento

- src/SME.SR.Workers.SGP/Views/RelatorioParecerConclusivo.cshtml
[AB#48936](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48936)
> Ajustes de quebra de linha

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaBimestralHtmlParaPdf/GerarRelatorioAtaBimestralHtmlParaPdfCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAtaFinalHtmlParaPdf/GerarRelatorioAtaFinalHtmlParaPdfCommandHandler.cs
- src/SME.SR.Application/Queries/ConselhoClasse/ObterAtaBimestralCabecalho/ObterAtaBimestralCabecalhoQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioConselhoClasseAtaBimestralUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/ConselhoClasseAtaBimestral/ConselhoClasseAtaBimestralCabecalhoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/ConselhoClasseAtaBimestral/FiltroConselhoClasseAtaBimestralDto.cs
- src/SME.SR.Workers.SGP/SME.SR.Workers.SGP.csproj
- src/SME.SR.Workers.SGP/wwwroot/templates/RelatorioAtaBimestralComColunaFinal.html
[AB#48013](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48013)
> Ajustes no layout

- src/SME.SR.Workers.SGP/Views/RelatorioPendencias.cshtml
[AB#26184](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26184)
> Rel Pendências

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
- src/SME.SR.Infra/Fila/RotasRabbitSGP.cs
- src/SME.SR.Workers.SGP/wwwroot/templates/RelatorioAtaBimestralComColunaFinal.html
[AB#48013](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48013)
> Ajustes no formato de geração

- src/SME.SR.Application/UseCases/RelatorioHistoricoEscolarUseCase.cs
> Bug: 48227

- src/SME.SR.Application/Queries/AcompanhamentoFechamento/MontasRelatorioAcompanhamentoFechamentoConselhoClasseConsolidado/MontasRelatorioAcompanhamentoFechamentoConselhoClasseConsolidadoQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FechamentoConsolidadoRepository.cs
- src/SME.SR.Infra/Dtos/FechamentoTurmaConsolidado/ConselhoClasseConsolidadoTurmaDto.cs
- src/SME.SR.Infra/Dtos/FechamentoTurmaConsolidado/FechamentoConsolidadoTurmaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFechamentoConsolidadoPorUe/RelatorioAcompanhamentoFechamentoConselhoClasseConsolidadoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFechamentoConsolidadoPorUe/RelatorioAcompanhamentoFechamentoConsolidadoBimestresDto.cs
[AB#49305](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49305)
> Ajustes dto

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
Correção Componentes que não lançam nota deve sair um hífen no campo
> Correção Componentes que não lançam nota deve sair um hífen no campo

- src/SME.SR.Application/Queries/AcompanhamentoFechamento/ObterRelatorioAcompanhamentoFechamentoConselhoClasseConsolidado/ObterRelatorioAcompanhamentoFechamentoConselhoClasseConsolidadoQueryHandler.cs
- src/SME.SR.Application/Queries/ConselhoClasse/ObterConselhosClasseConsolidadoPorTurmasBimestre/ObterConselhoClasseConsolidadoTurmaQuery.cs
- src/SME.SR.Application/Queries/ConselhoClasse/ObterConselhosClasseConsolidadoPorTurmasBimestre/ObterConselhoClasseConsolidadoTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/Fechamento/ObterFechamentoConsolidadoPorTurmasBimestre/ObterFechamentoConsolidadoTurmaQuery.cs
- src/SME.SR.Application/Queries/Fechamento/ObterFechamentoConsolidadoPorTurmasBimestre/ObterFechamentoConsolidadoTurmaQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseConsolidadoRepository.cs
- src/SME.SR.Data/Interfaces/Sgp/IFechamentoConsolidadoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FechamentoConsolidadoRepository.cs
[AB#49470](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49470)
> Adicionado modalidade como parâmetro

- src/SME.SR.Application/Queries/AcompanhamentoFechamento/MontasRelatorioAcompanhamentoFechamentoConselhoClasseConsolidado/MontasRelatorioAcompanhamentoFechamentoConselhoClasseConsolidadoQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FechamentoConsolidadoRepository.cs
[AB#49470](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49470)
> ajustes nome da UE

- src/SME.SR.Application/Queries/AcompanhamentoFechamento/ObterRelatorioAcompanhamentoFechamentoConselhoClasseConsolidado/ObterRelatorioAcompanhamentoFechamentoConselhoClasseConsolidadoQueryHandler.cs
- src/SME.SR.Application/Queries/ConselhoClasse/ObterConselhosClasseConsolidadoPorTurmasBimestre/ObterConselhoClasseConsolidadoTurmaQuery.cs
- src/SME.SR.Application/Queries/ConselhoClasse/ObterConselhosClasseConsolidadoPorTurmasBimestre/ObterConselhoClasseConsolidadoTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/Fechamento/ObterFechamentoConsolidadoPorTurmasBimestre/ObterFechamentoConsolidadoTurmaQuery.cs
- src/SME.SR.Application/Queries/Fechamento/ObterFechamentoConsolidadoPorTurmasBimestre/ObterFechamentoConsolidadoTurmaQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseConsolidadoRepository.cs
- src/SME.SR.Data/Interfaces/Sgp/IFechamentoConsolidadoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FechamentoConsolidadoRepository.cs
[AB#49951](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49951)
> Inclusão de semestre

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
- src/SME.SR.Infra/Dtos/AcompanhamentoAprendizagem/AcompanhamentoAprendizagemTurmaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoAprendizagem/RelatorioAcompanhamentoAprendizagemAlunoDto.cs
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagemCorpo.cshtml
[AB#49935](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49935)
> 49935 removendo a validaçao de imagem e deixando a formatação html

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFBoletimDetalhadoAppCommand/GerarRelatorioHtmlPDFBoletimDetalhadoAppCommand.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFBoletimDetalhadoAppCommand/GerarRelatorioHtmlPDFBoletimDetalhadoAppCommandHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoEscolaAqui/ObterRelatorioBoletimEscolarDetalhadoEscolaAquiQuery.cs
- src/SME.SR.Application/UseCases/RelatorioBoletimEscolarDetalhadoEscolaAquiUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/ComunicadosRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/MensagemRelatorioProntoDto.cs
[AB#49999](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49999)
[AB#50000](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50000)
> Ajustes no boletim

- src/SME.SR.Infra/Dtos/Relatorios/MensagemRelatorioProntoAppDto.cs
[AB#50003](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50003)
> Add MensagemRelatorioProntoAppDto

- src/SME.SR.Application/Commands/AlteracaoNotas/ObterDadosRelatorioAlteracaoNotas/ObterDadosRelatorioAlteracaoNotasCommandHandler.cs
- src/SME.SR.Application/Queries/NotaConceito/ObterNotaConceitoEmAprovacao/ObterNotaConceitoEmAprovacaoQuery.cs
- src/SME.SR.Application/Queries/NotaConceito/ObterNotaConceitoEmAprovacao/ObterNotaConceitoEmAprovacaoQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisExcel/ObterRelatorioNotasEConceitosFinaisExcelQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/INotaConceitoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseNotaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FechamentoNotaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
- src/SME.SR.Infra/Dtos/HistoricoAlteracaoNotas/HistoricoAlteracaoNotasDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AlteracaoNotas/AlunosAlteracaoNotasDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RelatorioNotasEConceitosFinaisDoAlunoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/RelatorioNotasEConceitosFinais/RelatorioNotasEConceitosFinaisExcelDto.cs
[AB#49948](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49948)
> 49948 - Ajustar os relatórios de alteração de notas e notas e conceitos finais

- src/SME.SR.Application/Queries/ParecerConclusivo/ObterDescricaoParecerEmAprovacao/ObterDescricaoParecerEmAprovacaoQuery.cs
- src/SME.SR.Application/Queries/ParecerConclusivo/ObterDescricaoParecerEmAprovacao/ObterDescricaoParecerEmAprovacaoQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivo/ObterRelatorioParecerConclusivoQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivoExcel/ObterRelatorioParecerConclusivoExcelQuery.cs
- src/SME.SR.Application/Queries/RelatorioParecerConclusivo/ObterRelatorioParecerConclusivoExcel/ObterRelatorioParecerConclusivoExcelQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioParecerConclusivoUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IParecerConclusivoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ParecerConclusivoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/RelatorioParecerConclusivoAlunoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/ParecerConclusivo/RelatorioParecerConclusivoExcelDto.cs
[AB#49953](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49953)
> 49953 - Ajuste relatórios de parecer conclusivo (Excel e PDF)

- src/SME.SR.Application/Commands/Arquivos/SalvarArquivoFisico/SalvarArquivoFisicoCommandHandler.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/SalvarRelatorioJasperLocal/SalvarRelatorioJasperLocalCommandHandler.cs
- src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
- Configurado Heartbeat 
- Melhoria na gestão de threads no salvamento de arquivo fisico do relatório
> Melhorias SR

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterDadosPedagogicosComponenteCurriculares/ObterDadosPedagogicosComponenteCurricularesQueryHandler.cs
- src/SME.SR.Application/Queries/Turma/ObterDadosPedagogicosTurma/ObterDadosPedagogicosTurmaQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoRegistrosPedagogicos/Infantil/RelatorioAcompanhamentoRegistrosPedagogicosTurmaInfantilDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoRegistrosPedagogicos/RelatorioAcompanhamentoRegistrosPedagogicosCompCurricularesDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
[AB#52544](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52544)
> 52544 - [44029 - Relatório de acompanhamento dos registros pedagógicos] - Datas do relatório no formato MM/DD/AAAA

- src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoAprendizagem.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
[AB#52085](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52085)
> 49612 - Layout MVC RelatorioAcompanhamentoAprendizagem

- src/SME.SR.Data/Repositories/Sgp/RegistrosPedagogicosRepository.cs
[AB#52604](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52604)
> 52604 - Verificação da query - trazendo informações duplicadas

- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoRegistrosPedagogicos.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoRegistrosPedagogicosInfantil.cshtml
[AB#52449](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52449) Ajuste quebra de pagina
> fix/52449 

- src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoAprendizagem.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
- testes/SME.SR.Testes.QueryHandlers/RelatorioFaltasFrequenciaTeste.cs
[AB#52891](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52891)
> r2 - fix/52891 RAA

- src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommand.cs
- src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoFrequenciaUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/DreRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FiltroAcompanhamentoFrequenciaJustificativaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FrequenciaAlunoConsolidadoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaIndividual/RelatorioFrequenciaIndividualAlunosDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaIndividual/RelatorioFrequenciaIndividualBimestresDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaIndividual/RelatorioFrequenciaIndividualDto.cs
[AB#46917](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46917)
> UseCase de geração relatório no SR

- src/SME.SR.Workers.SGP/Views/RelatorioUsuarios.cshtml
[AB#51784](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51784)
> SR Fix/51784 rel r2

- src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
- src/SME.SR.Application/Queries/RelatorioAcompanhamentoFrequência/ObterFrequenciaAlunoPorCodigoBimestre/ObterFrequenciaAlunoPorCodigoBimestreQuery.cs
- src/SME.SR.Application/Queries/RelatorioAcompanhamentoFrequência/ObterFrequenciaAlunoPorCodigoBimestre/ObterFrequenciaAlunoPorCodigoBimestreQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FrequenciaAlunoConsolidadoDto.cs
Alterações na consulta de frequência e ausências
[AB#53100](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53100)
> Alterações na consulta de frequencia e ausencias

- src/SME.SR.Workers.SGP/Views/RelatorioFrequenciaIndividual.cshtml
> Adicionado quebra de pagina

- src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
[AB#53310](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53310)
> SR Bugfix - ordenar lista e impressão

- src/SME.SR.Application/Interfaces/UseCases/IRelatorioOcorrenciasUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioOcorrenciasUseCase.cs
- src/SME.SR.Infra/Fila/RotasRabbitSR.cs
- src/SME.SR.IoC/Dependencias.cs
- src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
[AB#46906](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46906)
> SR - Endpoint chamada do relatório

- src/SME.SR.Application/Queries/Ocorrencia/ObterOcorenciasPorCodigoETurma/ObterOcorenciasPorCodigoETurmaQuery.cs
- src/SME.SR.Application/Queries/Ocorrencia/ObterOcorenciasPorCodigoETurma/ObterOcorenciasPorCodigoETurmaQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IOcorrenciaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/OcorrenciaRepository.cs
- src/SME.SR.Infra/Dtos/Ocorrencias/OcorrenciasPorCodigoTurmaDto.cs
- src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
[AB#46908](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46908)
> SR - Query de consulta dos dados de Ocorrências

- src/SME.SR.Application/Queries/RelatorioOcorrencias/ObterDadosRelatorioOcorrenciaCommandHandler.cs
- src/SME.SR.Infra/Dtos/Ocorrencias/OcorrenciasPorCodigoTurmaDto.cs
[AB#53750](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53750)
> Ajuste no Formato da Data da Ocorrência e Código Eol no nome do Aluno

- src/SME.SR.Application/Queries/RelatorioOcorrencias/ObterDadosRelatorioOcorrenciaCommandHandler.cs
- src/SME.SR.Data/Repositories/Sgp/OcorrenciaRepository.cs
- src/SME.SR.Infra/Dtos/Ocorrencias/OcorrenciasPorCodigoTurmaDto.cs
[AB#53992](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53992)
> Alterado a propriedade OcorrenciaData e realizado formatação nela

- src/SME.SR.Application/Queries/HistoricoEscolar/MontarHistoricoEscolar/MontarHistoricoEscolarQueryHandler.cs
[AB#51265](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51265)
> Ajsute na montagem dos componentes de regência

- src/SME.SR.Data/Repositories/Sgp/OcorrenciaRepository.cs
[AB#53992](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53992)
> ajustes na formatação de hora

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAcompanhamentoFrequencia/GerarRelatorioAcompanhamentoFrequenciaCommandHandler.cs
[AB#53332](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53332)
> Ajuste da quantidade de caracteres no relatório

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAcompanhamentoFrequencia/GerarRelatorioAcompanhamentoFrequenciaCommandHandler.cs
- src/SME.SR.Workers.SGP/Views/RelatorioFrequenciaIndividualNovo.cshtml
[AB#53332](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53332)
> Correção do cabeçalho, adicionando turma e componente curricular - Fonte Roboto

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAcompanhamentoFrequencia/GerarRelatorioAcompanhamentoFrequenciaCommandHandler.cs
[AB#53339](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53339)
> Ajuste da paginação por aluno

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAcompanhamentoFrequencia/GerarRelatorioAcompanhamentoFrequenciaCommandHandler.cs
[AB#53332](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53332)
> Ajuste do tamanho de caracteres da página

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioAcompanhamentoFrequencia/GerarRelatorioAcompanhamentoFrequenciaCommandHandler.cs
- src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
- src/SME.SR.Infra/Extensions/StringExtension.cs
[AB#53963](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53963)
> Adicionando a situação e a data

- src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
- src/SME.SR.Application/Queries/Alunos/ObterAlunosPorTurmaEDataMatriculaQuery/ObterAlunosPorTurmaEDataMatriculaQuery.cs
- src/SME.SR.Application/Queries/Alunos/ObterAlunosPorTurmaEDataMatriculaQuery/ObterAlunosPorTurmaEDataMatriculaQueryHandler.cs
- src/SME.SR.Application/Queries/TipoCalendario/ObterTipoCalendarioIdPorTurmaQuery/ObterTipoCalendarioIdPorTurmaQuery.cs
- src/SME.SR.Application/Queries/TipoCalendario/ObterTipoCalendarioIdPorTurmaQuery/ObterTipoCalendarioIdPorTurmaQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoFrequenciaUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs
- src/SME.SR.Data/Interfaces/Sgp/ITipoCalendarioRepository.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/TipoCalendarioRepository.cs
- src/SME.SR.Infra/Dtos/Alunos/AlunoPorTurmaRespostaDto.cs
- src/SME.SR.Infra/Dtos/Alunos/AlunoRetornoDto.cs
- src/SME.SR.Infra/Dtos/Turma/AlunoNaTurmaDto.cs
[AB#53963](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53963)
> Correção da situação do aluno conforme a tela

- src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs
Ajuste na impressão de relatório de acompanhamento desconsiderando arquivo não localizado em qualquer formato.
> Bug: 54269

- src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs
- src/SME.SR.Application/Queries/Arquivos/ObterHtmlComImagensBase64/ObterHtmlComImagensBase64QueryHandler.cs
Ajustes na rotina de obter os arquivos ao imprimir o relatório de acompanhamento, verificando se é possível obter remoto primeiramente e posteriormente local.
> Bug: 54937

- src/SME.SR.Application/Queries/PlanoAula/ObterPlanejamentoDiario/ObterPlanejamentoDiarioPlanoAulaQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioPlanoAulaUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/PlanoAulaRepository.cs
- src/SME.SR.Infra/Dtos/PlanoAula/PlanoAulaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/AulaPlanoAulaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/PlanejamentoDiarioDto.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioControlePlanejamentoDiario.cshtml
- src/SME.SR.MVC/Views/Relatorios/RelatorioPlanoAula.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiario.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPlanoAula.cshtml
[AB#54406](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54406)
> SR - 54406 Ajuste Relatórios

- src/SME.SR.Data/Repositories/Sgp/PendenciaRepository.cs
[AB#48182](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48182)
> Ajuste na query do relatório

- src/SME.SR.Application/UseCases/RelatorioPlanoAulaUseCase.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioControlePlanejamentoDiario.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiario.cshtml
[AB#54958](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54958)
> Ajuste Quebra de pagina Relatório de controle do planejamento diário

- src/SME.SR.MVC/Views/Relatorios/RelatorioControlePlanejamentoDiario.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiario.cshtml
[AB#55191](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55191)
[AB#55192](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55192)
> Correção na quebra de pagina

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlParaPdfCommand/GerarRelatorioHtmlParaPdfCommand.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlParaPdfCommand/GerarRelatorioHtmlParaPdfCommandHandler.cs
- src/SME.SR.Application/Interfaces/UseCases/IDownloadRelatorioUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioDevolutivasSincronoUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioDevolutivasUseCase.cs
- src/SME.SR.Application/UseCases/DownloadRelatorioUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioDevolutivasSincronoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioDevolutivasUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IDevolutivaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/DevolutivaRepository.cs
- src/SME.SR.Infra/Dtos/Devolutivas/DevolutivaSincronoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/FiltroRelatorioDevolutivasSincronoDto.cs
- src/SME.SR.IoC/Dependencias.cs
- src/SME.SR.Workers.SGP/Controllers/RelatoriosSincronosSgpController.cs
- src/SME.SR.Workers.SGP/Controllers/SgpDownloadController.cs
- src/SME.SR.Workers.SGP/Views/RelatorioDevolutivaSincrono.cshtml
[AB#55657](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55657)
> SR - Feature/55657 - Relatório de Devolutiva (SR)

- src/SME.SR.Application/UseCases/RelatorioPlanejamentoDiarioUseCase.cs
[AB#55742](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55742) - Cria Controle de Impressão Relatório Diário de Bordo 2021-2022
> AB#55742 - Cria Controle de Impressão Relatório Diário de Bordo 2021-2022

- src/SME.SR.Application/UseCases/RelatorioPlanejamentoDiarioUseCase.cs
[AB#55742](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55742) - Altera condição para atender os anos posteriores a 2022.
> AB#55742 - Altera condição para atender os anos posteriores a 2022

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlParaPdfCommand/GerarRelatorioHtmlParaPdfCommand.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlParaPdfCommand/GerarRelatorioHtmlParaPdfCommandHandler.cs
- src/SME.SR.Application/Interfaces/UseCases/IDownloadRelatorioUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioDevolutivasSincronoUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioDevolutivasUseCase.cs
- src/SME.SR.Application/UseCases/DownloadRelatorioUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioDevolutivasSincronoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioDevolutivasUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IDevolutivaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/DevolutivaRepository.cs
- src/SME.SR.Infra/Dtos/Devolutivas/DevolutivaSincronoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/FiltroRelatorioDevolutivasSincronoDto.cs
- src/SME.SR.IoC/Dependencias.cs
- src/SME.SR.Workers.SGP/Controllers/RelatoriosSincronosSgpController.cs
- src/SME.SR.Workers.SGP/Controllers/SgpDownloadController.cs
- src/SME.SR.Workers.SGP/Views/RelatorioDevolutivaSincrono.cshtml
[AB#51776](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51776)
> SR  - Separação de diários de bordo - Devolutivas

- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/BimestreDevolutivaSincronoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/DevolutivaRelatorioSincronoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/RelatorioDevolutivasSincronoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/TurmaDevolutivaSincronoDto.cs
Adicionado Arquivos que ficaram ocultos no projeto
> Adicionado Arquivos que ficaram ocultos no projeto

- src/SME.SR.Application/Interfaces/UseCases/IRelatorioDevolutivasSincronoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioDevolutivasSincronoUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/FiltroRelatorioDevolutivasSincronoDto.cs
- src/SME.SR.Workers.SGP/Controllers/RelatoriosSincronosSgpController.cs
[AB#56108](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56108)
[AB#56122](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56122)
> SR - Erro interno ao fazer download do Relatório de Devolutivas

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlParaPdfCommand/GerarRelatorioHtmlParaPdfCommandHandler.cs
> Alterado pasta do relatório

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
[AB#55761](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55761)
> 55761 - ajuste relatório (aba frequências) RAA

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/AcompanhamentoAprendizagem/RelatorioAcompanhamentoAprendizagemAlunoDto.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioAcompanhamentoAprendizagem.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioAcompanhamentoAprendizagem.cshtml
[AB#55764](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55764)
> 55764 - ajuste development - relatório parte frequências RAA

- docker-compose.dcproj
- src/SME.SR.Workers.SGP/Views/RelatorioDevolutivaSincrono.cshtml
Texto saindo da área limitada
[AB#56377](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56377)
> Texto saindo da área limitada

- src/SME.SR.Application/UseCases/RelatorioPlanejamentoDiarioUseCase.cs
- src/SME.SR.Infra/Extensions/DateTimeExtension.cs
- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiarioInfantilComComponente.cshtml
[AB#56483](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56483)
[AB#56484](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56484)
> Componente Curricular fixo para o ano de 2022

- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#56538](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56538)
> 56538 Corrigido tratativa de histórico na consulta de componentes para o boletim

- src/SME.SR.Application/Queries/ParametrosSistema/VerificarSeParametroEstaAtivo/VerificarSeParametroEstaAtivoQuery.cs
- src/SME.SR.Application/Queries/ParametrosSistema/VerificarSeParametroEstaAtivo/VerificarSeParametroEstaAtivoQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioPlanejamentoDiarioUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IParametroSistemaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ParametroSistemaRepository.cs
- src/SME.SR.Infra/Dtos/ParametroSistemaAnoSituacaoDto.cs
- src/SME.SR.Infra/Enumeradores/TipoParametroSistema.cs
[AB#56553](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56553)
> SR - Implementado parametro para utilização de novo Layout

- src/SME.SR.Application/Queries/Turma/ObterTurmaPorId/ObterTurmaPorIdQueryHandler.cs
- src/SME.SR.Application/Queries/Ue/ObterUePorId/ObterUePorIdQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioDevolutivasSincronoUseCase.cs
- src/SME.SR.Workers.SGP/Views/RelatorioDevolutivaSincrono.cshtml
[AB#56642](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56642)
[AB#56271](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56271)
> Correção do Texto saindo fora da Área Limitada

- src/SME.SR.Workers.SGP/Dockerfile
Adicionado novas fontes devido a um bug reportado.
> adicionado roboto e opensans

- src/SME.SR.Workers.SGP/Views/RelatorioPlanoAula.cshtml
[AB#57237](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57237)
> 57237 - validação de objetivos antes de montar o relatório

- src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
[AB#57258](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57258)
> Notificar usuario mesmo com erro não tratado

- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
[AB#57266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57266)
> Remoção do campo que foi removido da tabela

- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#57266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57266)
> Remover campo

- src/SME.SR.Application/Queries/RelatorioFechamentoPendencias/ObterRelatorioFechamentoPedencias/ObterRelatorioPedenciasQueryHandler.cs
[AB#57315](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57315)
[AB#57314](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57314)
> realizado tratamento de retorno para objeto null

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
[AB#57266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57266)
> Tratamento de exceção para componentes curriculares

- src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
- src/SME.SR.Application/Queries/RelatorioAcompanhamentoFrequência/ObterFrequenciaAlunoPorCodigoBimestre/ObterFrequenciaAlunoPorCodigoBimestreQuery.cs
- src/SME.SR.Application/Queries/RelatorioAcompanhamentoFrequência/ObterFrequenciaAlunoPorCodigoBimestre/ObterFrequenciaAlunoPorCodigoBimestreQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoFrequenciaUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaIndividual/RelatorioFrequenciaIndividualDadosFrequenciasDto.cs
[AB#57365](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57365)
> Ajuste no obter frequência para o relatório

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
[AB#57359](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57359)
> Adicionado tratamento de exceção no boletim para identifica rproblema em HOM

- src/SME.SR.Application/Queries/AcompanhamentoFechamento/ObterRelatorioAcompanhamentoFechamento/ObterRelatorioAcompanhamentoFechamentoQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesEolPorIds/ObterComponentesCurricularesEolPorIdsQuery.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesEolPorIds/ObterComponentesCurricularesEolPorIdsQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IComponenteCurricularRepository.cs
- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#57354](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57354)
> 57354 - Erro ao gerar o Relatório de Acompanhamento do Fechamento 

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Data/Queries/ComponenteCurricularConsultas.cs
[AB#57597](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57597)
> Correção dos componentes curriculares itinerário

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
[AB#57597](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57597)
> Correção dos componentes curriculares itinerários

- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/AulaPlanejamentoDiarioDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/BimestrePlanejamentoDiarioInfantilDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/TurmaPlanejamentoDiarioInfantilDto.cs
[AB#51798](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51798)
> Adicionando arquivos que forma ignorados

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesEolPorIds/ObterComponentesCurricularesEolPorIdsQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegencia/ObterComponentesCurricularesRegenciaQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegenciaPorCodigosTurma/ObterComponentesCurricularesRegenciaPorCodigosTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioNotasEConceitosFinais/ObterRelatorioNotasEConceitosFinaisPdf/ObterRelatorioNotasEConceitosFinaisPdfQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioCompensacaoAusenciaUseCase.cs
- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#57588](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57588)
> Fazer a pesquisa de componentes do território saber somente se tiver turma também

- src/SME.SR.Data/Repositories/Sgp/ParecerConclusivoRepository.cs
Ajuste na consulta de parecer conclusivo para desconsiderar registro de conselho aluno marcado como excluido.
> Bug: 56596

- src/SME.SR.Workers.SGP/Filters/FiltroIntegracao.cs
Ajuste no filtro de integração ajustando a nomenclatura da chave.
> Bug: 57193

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#56902](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56902)
> Ajuste na consulta de frequência na turma de regência

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#56698](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56698)
> Ajuste na validação de alunos ativos

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Data/Queries/TurmaConsultas.cs
[AB#56698](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56698)
> Ajuste no filtro de alunos ativos

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesEolPorIds/ObterComponentesCurricularesEolPorIdsQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioPlanejamentoDiarioUseCase.cs
- src/SME.SR.Data/Models/ComponenteCurricular.cs
- src/SME.SR.Data/Models/ComponenteCurricularPorTurma.cs
- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#58152](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58152)
> Retornando o nome do componente infantil cadastrado

- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiarioInfantilComComponente.cshtml
[AB#58156](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58156)
[AB#58456](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58456)
> Rel. Controle plan. diário - quebra de seção na impressão.

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
Ajuste na definição de parecer conclusivo, considerando o registro relacionado ao parecer final.
> Bug: 58792

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#58791](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58791)
> Retirada de validação de alunos sem numero de chamada

- src/SME.SR.Data/Models/Aluno.cs
Ajuste na exibição do nome do aluno do boletim considerando concluído como uma situação ativa e não considerar exibição.
> Bug: 58655

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Data/Models/Aluno.cs
- src/SME.SR.Data/Repositories/Sgp/UsuarioRepository.cs
[AB#58988](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58988)
> 58988 - ajuste relatórios não estão sendo gerados (sondagem)

- src/SME.SR.Application/Queries/Devolutivas/ObterDevolutivas/ObterDevolutivasQuery.cs
- src/SME.SR.Application/Queries/Devolutivas/ObterDevolutivas/ObterDevolutivasQueryHandler.cs
- src/SME.SR.Application/SME.SR.Application.csproj
- src/SME.SR.Application/UseCases/RelatorioDevolutivasUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IDevolutivaRepository.cs
- src/SME.SR.Data/Repositories/Sgp/DevolutivaRepository.cs
- src/SME.SR.Infra/Dtos/Devolutivas/DevolutivaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/BimestresComponentesCurricularesDevolutivasDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/FiltroRelatorioDevolutivasDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Devolutivas/TurmasDevolutivasDto.cs
- src/SME.SR.Infra/Enumeradores/TipoParametroSistema.cs
- src/SME.SR.MVC/Controllers/RelatoriosController.cs
- src/SME.SR.MVC/Views/Relatorios/RelatorioDevolutivas.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioDevolutivas.cshtml
[AB#56796](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56796)
> Separação de diário de bordo - relatório de devolutiva

- src/SME.SR.Application/SME.SR.Application.csproj
- src/SME.SR.Data/Repositories/Sgp/UeRepository.cs
Adicionado a extensão windows extensions e ajustando filtros de UE´s
> Adicionado a extensão windows extensions e ajustando filtros de UE´s

- src/SME.SR.Application/Queries/Devolutivas/ObterDevolutivas/ObterDevolutivasQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/UeRepository.cs
Correção do cabeçalho da UE e informação do componente
> Correção do cabeçalho da UE e informação do componente

- src/SME.SR.Infra/Dtos/Relatorios/Frequencia/Pdf/RelatorioFrequenciaAlunoDto.cs
[AB#59556](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59556)
> Ajuste na visualização do percentual de frequência

- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs
Ajuste no montagem do relatório de frequência atribuindo zero caso o aluno não tenha número de chamada.
> Bug: 59065

- src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQuery.cs
- src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQueryHandler.cs
- src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioSondagemMatConsolidadoAdtMultiUseCase.cs
- src/SME.SR.Data/Interfaces/Sondagem/IPerguntasAditMultiNumRepository.cs
- src/SME.SR.Data/Repositories/Sondagem/PerguntasAditMultiNumRepository.cs
- src/SME.SR.Data/Repositories/Sondagem/PerguntasAutoralRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/ConsolidadoMatematicaAditivoMultiplicativo/RelatorioSondagemComponentesMatematicaAditMulConsolidadoPerguntaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/ConsolidadoMatematicaAditivoMultiplicativo/RelatorioSondagemComponentesMatematicaAditMulConsolidadoPerguntasRespostasDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/ConsolidadoMatematicaAditivoMultiplicativo/RelatorioSondagemComponentesMatematicaAditMulConsolidadoRespostaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/FiltroRelatorioSondagemComponentesMatematicaAditivoMultiplicativoConsolidadoDto.cs
- src/SME.SR.IoC/Dependencias.cs
- src/SME.SR.Workers.SGP/Views/RelatorioSondagemComponentesMatematicaAditivoMultiplicativoConsolidado.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioSondagemComponentesMatematicaNumerosAutoralConsolidado.cshtml
[AB#59474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59474)
> Feature/59474 - ajuste para relatório do 1 ao 3 ano (matemática consolidado sondagem)

- src/SME.SR.Workers.SGP/Properties/launchSettings.json
- src/SME.SR.Workers.SGP/Views/RelatorioSondagemComponentesMatematicaAditivoMultiplicativoConsolidado.cshtml
[AB#60469](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60469)
> 60469 Corrigido percentual

- src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQueryHandler.cs
- src/SME.SR.Application/Queries/Sondagem/MatematicaNumerosAutoralConsolidado/ObterSondagemMatematicaNumerosAutoralConsolidado/ObterSondagemMatNumAutoralConsolidadoQueryHandler.cs
[AB#60411](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60411)
> 60411 Corrigido percentual de repostas por opção nos rel. Mat.

- src/SME.SR.Workers.SGP/Views/RelatorioSondagemComponentesMatematicaNumerosAutoralConsolidado.cshtml
[AB#60463](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60463)
> 60463 - ajuste de quebra de perguntas do layout consolidado sondagem

- src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQueryHandler.cs
[AB#60481](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60481)
> 60481 Não carregar valores negativos

- src/SME.SR.Workers.SGP/Views/RelatorioSondagemComponentesMatematicaAditivoMultiplicativoConsolidado.cshtml
[AB#60423](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60423)
> 60423 Corrigido montagem das colunas no relatório quando não possui valor

- src/SME.SR.Application/Queries/Turma/ObterDadosPedagogicosTurma/ObterDadosPedagogicosTurmaComponenteQueryHandler.cs
Correção para trazer a data do diário de bordo
> Correção para trazer a data do diário de bordo

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
Correção do bug 59041, para recuperar todos os alunos no relatório de ata final, independente de estarem ativos, inativos  desistentes.
> Fix do bug 59041

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#59041](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59041)
> Correção do bug 59041, para recuperar todos os alunos no relatório de ata final, independente de estarem ativos, inativos  desistentes.

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasAlunosConsolidado/ObterFrequenciasAlunosConsolidadoQuery.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasAlunosConsolidado/ObterFrequenciasAlunosConsolidadoQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Infra/Dtos/Frequencia/FrequenciaAlunoConsolidadoRelatorioDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Frequencia/Pdf/RelatorioFrequenciaAlunoDto.cs
> Ajuste nas frequencias do relatório

- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoAprendizagemUseCase.cs
[AB#60138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60138)
> remoção de verificação de semestre

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/ParecerConclusivo/ObterPareceresFinaisConsolidado/ObterPareceresFinaisConsolidadoQuery.cs
- src/SME.SR.Application/Queries/ParecerConclusivo/ObterPareceresFinaisConsolidado/ObterPareceresFinaisConsolidadoQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IParecerConclusivoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ParecerConclusivoRepository.cs
- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
Correções do parecer conclusivo
> Correções do parecer conclusivo

- src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQuery.cs
- src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs
Correção de parâmetro de usuário inativos
> Correção de parâmetro de usuário inativos

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
Correção de turmas diferentes do ensino médio
> Correção de turmas diferentes do ensino médio

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
Correção da ordenação dos componentes curriculares, boletim EJA
> Correção da ordenação dos componentes curriculares, boletim EJA

- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
Exibir componentes da regência somente para regência de classe
> Exibir componentes da regência somente para regência de classe

- src/SME.SR.Infra/RelatorioPaginado/Coluna.cs
- src/SME.SR.Infra/RelatorioPaginado/Dtos/CabecalhoDto.cs
- src/SME.SR.Infra/RelatorioPaginado/Dtos/RelatorioPaginadoDto.cs
- src/SME.SR.Infra/RelatorioPaginado/EnumTipoDePapel.cs
- src/SME.SR.Infra/RelatorioPaginado/Interfaces/IColuna.cs
- src/SME.SR.Infra/RelatorioPaginado/Interfaces/IRelatorioPaginado.cs
- src/SME.SR.Infra/RelatorioPaginado/Pagina.cs
- src/SME.SR.Infra/RelatorioPaginado/ParametroRelatorioPaginado.cs
- src/SME.SR.Infra/RelatorioPaginado/ParametroRelatorioPaginadoPorColuna.cs
- src/SME.SR.Infra/RelatorioPaginado/ParametroRelatorioPaginadoQuantitativo.cs
- src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginado.cs
- src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoPorColuna.cs
- src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoQuantitativo.cs
- src/SME.SR.Infra/RelatorioPaginado/TipoPapel.cs
- src/SME.SR.MVC/Views/RelatorioPaginado/ConteudoDefault.cshtml
- src/SME.SR.MVC/Views/RelatorioPaginado/Index.cshtml
- src/SME.SR.MVC/Views/RelatorioPaginado/ParametroCabecalhoDefault.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/ConteudoDefault.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/Index.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/ParametroCabecalhoDefault.cshtml
> Montar estrutura de quebra do relatório

- src/SME.SR.Application/Commands/Frequencia/AcompanhamentoFrequencia/ObterDadosRelatorioAcompanhamentoFrequenciaCommandHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaIndividual/RelatorioFrequenciaIndividualDadosFrequenciasDto.cs
> Ajuste na regra de frequência

- src/SME.SR.Workers.SGP/Controllers/SondagemController.cs
> voltando anotação key

- src/SME.SR.Infra/RelatorioPaginado/Dtos/RelatorioPaginadoDto.cs
- src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoSondagemPorTurmaMatematica.cs
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/CssDefault.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/Grafico.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/Index.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/RegistradorDeGrafico.cshtml
> Registros dos graficos

- src/SME.SR.Data/Repositories/Sgp/RelatorioSondagemComponentePorTurmaRepository.cs
> Ajustada query de consulta da perguntas.

- src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/Comuns/GraficoBarrasVerticalDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioSondagemComponentesPorTurmaPlanilhaDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/Sondagem/RelatorioSondagemComponentesPorTurmaRelatorioDto.cs
> Ajustado agrupamento do gráfico de proficiência.

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlPDFBoletimDetalhadoCommand/GerarRelatorioHtmlPDFBoletimDetalhadoCommandHandler.cs
- src/SME.SR.Application/Queries/Alunos/ObterAlunosTurmasRelatorioBoletim/ObterAlunosTurmasRelatorioBoletimQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQuery.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioBoletimEscolarDetalhadoUseCase.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
> [58989 - Boletim simples] O filtro "imprimir estudantes inativos" não funciona quando seleciona a opção "boletim detalhado"

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQuery.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegenciaPorCodigosTurma/ObterComponentesCurricularesRegenciaPorCodigosTurmaQuery.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegenciaPorCodigosTurma/ObterComponentesCurricularesRegenciaPorCodigosTurmaQueryHandler.cs
> Correção dos componentes curriculares

- src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
>  Impressão de boletim filtrando TODAS as turmas não gera a notificação 

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
> carregar as sínteses para os componentes sem nota no boletim impresso

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
Correção de Erro no build
AB#62189
> ajustes erro build no build

- src/SME.SR.Data/Queries/ComponenteCurricularConsultas.cs
> Correção dos componentes curriculares - excluir os tipo 3

- src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoSondagemPorTurmaMatematica.cs
> Quebras de linhas e de páginas incorreta no 5º, 6º, 7º ano 

- src/SME.SR.Workers.SGP/Views/Graficos/GraficoBarras.cshtml
> Correção Legenda invadindo o gráfico

- src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoSondagemPorTurmaMatematica.cs
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/CssDefault.cshtml
> Sem espaçamento do texto de algumas colunas de resposta 

- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
> Correção no layout do relatório de boletim

- src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoGrafico.cs
> Quebra de página desnecessária nos gráficos

- src/SME.SR.MVC/Models/CriadorDeMockRelatorioPaginadoSondagemTurmaModel.cs
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/Grafico.cshtml
> Titulo invadindo o gráfico

- src/SME.SR.Application/Queries/BoletimEscolar/MontarBoletinsQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/BoletimEscolar/BoletimEscolarCabecalhoDto.cs
> Correção da ordenação das turmas no boletim

- src/SME.SR.Workers.SGP/Views/RelatorioBoletimEscolarSimples.cshtml
> Correção da observação do boletim

- src/SME.SR.Application/Interfaces/UseCases/IRelatorioFrequenciaMensalUseCase.cs
- src/SME.SR.Infra/Fila/RotasRabbitSGP.cs
- src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
> Adicionado EndPoint para o relatório.

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs
- src/SME.SR.Data/Models/ComponenteCurricularPorTurmaRegencia.cs
> Correção dos componentes curriculares Território do Saber

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurma/ObterFrequenciasGeralAlunosNaTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
> ajuste no calculo de frequência final

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioFrequenciaGlobal/Excel/GerarRelatorioFrequenciaGlobalExcelCommand.cs
- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioFrequenciaGlobal/Excel/GerarRelatorioFrequenciaGlobalExcelCommandHandler.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioFrequenciaGlobalUseCase.cs
- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/Excel/ObterRelatorioDeFrequenciaGlobalExcelQuery.cs
- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/Excel/ObterRelatorioDeFrequenciaGlobalExcelQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQuery.cs
- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
- src/SME.SR.Application/SME.SR.Application.csproj
- src/SME.SR.Application/UseCases/RelatorioFrequenciaGlobalUseCase.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/FiltroFrequenciaGlobalDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/FrequenciaGlobalDto.cs
- src/SME.SR.IoC/Dependencias.cs
- src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
> UseCase geração do relatório

- src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosEscola/ObterDadosAlunosEscolaQuery.cs
- src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosEscola/ObterDadosAlunosEscolaQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs
- src/SME.SR.Data/Repositories/Cache/RepositorioCache.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
- src/SME.SR.Infra/Dtos/Alunos/DadosAlunosEscolaDto.cs
- src/SME.SR.Infra/Interfaces/IRepositorioCache.cs
- src/SME.SR.Infra/Utilitarios/UtilGZip.cs
- src/SME.SR.IoC/Dependencias.cs
> Query de dados dos alunos da escola com Cache por escola

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurma/ObterFrequenciasGeralAlunosNaTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
> ajuste no calculo de frequencia final

- src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
> Correção do bug 62503

- src/SME.SR.Data/Models/ComponenteCurricularPorTurmaRegencia.cs
> Ajuste na exibição do componente curricular

- src/SME.SR.Application/Queries/ConselhoClasse/ObterRecomendacoesPorAlunosTurmas/ObterRecomendacoesPorAlunosTurmasQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseAlunoRepository.cs
- src/SME.SR.Infra/Dtos/ConselhoClasse/RecomendacoesAlunoFamiliaDto.cs
- src/SME.SR.Infra/Utilitarios/VariaveisAmbiente.cs
- src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
> fix/63464 - ajuste para exibir recomendações selecionadas na tela de conselho de classe e texto livre

- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/MontarBoletinsDetalhados/MontarBoletinsDetalhadosQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
> [BUG] Fix/63357 - Boletim Detalhado - Não está gerando o boletim para o Ensino Médio

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorAlunos/ObterComponentesCurricularesPorAlunosQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQuery.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigosTurmaLoginEPerfilQueryHandler.cs
- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesRegenciaPorCodigosTurma/ObterComponentesCurricularesRegenciaPorCodigosTurmaQueryHandler.cs
> Remoção do componente Ed. Fisica para EJA

- src/SME.SR.Application/Queries/RelatorioSondagemComponentes/ObterRelatorioSondagemComponentes/ObterRelatorioSondagemComponentesPorTurmaQueryHandler.cs
> fix/64100 - ajustes para exibição correta do gráfico sondagem - matemática aditivo

- src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoSondagemPorTurmaMatematica.cs
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/CssDefault.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/SondagemTurma/Cabecalho.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/SondagemTurma/ConteudoSubColuna.cshtml
> fix/64166 - ajustes para manter o padrão de relatório aditivo ao antigo

- src/SME.SR.Application/Queries/DiarioBordo/ObterDadosPlanejamentoDiarioBordo/ObterDadosPlanejamentoDiarioBordoQueryHandler.cs
- src/SME.SR.Application/Queries/DiarioBordo/ObterDadosPlanejamentoDiarioBordoComComponente/ObterDadosPlanejamentoDiarioBordoComComponenteQueryHandler.cs
- src/SME.SR.Data/Repositories/Sgp/DiarioBordoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/PlanejamentoDiario/AulaDiarioBordoDto.cs
> Correção do bug 64086

- src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosEscola/ObterDadosAlunosEscolaQuery.cs
- src/SME.SR.Application/Queries/Alunos/ObterDadosAlunosEscola/ObterDadosAlunosEscolaQueryHandler.cs
- src/SME.SR.Application/Queries/Dre/ObterDreUePorTurmaCodigo/ObterDreUePorDreCodigoQuery.cs
- src/SME.SR.Application/Queries/Dre/ObterDreUePorTurmaCodigo/ObterDreUePorDreCodigoQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioFrequenciaGlobalUseCase.cs
- src/SME.SR.Data/Interfaces/Sgp/IAlunoRepository.cs
- src/SME.SR.Data/Interfaces/Sgp/IDreRepository.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/DreRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/FiltroFrequenciaGlobalDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/FrequenciaAlunoMensalConsolidadoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/FrequenciaGlobalDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/FrequenciaMensalCabecalhoDto.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/FrequenciaMensalDto.cs
- src/SME.SR.Infra/Enumeradores/Mes.cs
- src/SME.SR.Infra/RelatorioPaginado/Dtos/CabecalhoPaginadoDto.cs
- src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoFrequenciaGlobalMensal.cs
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/FrequenciaGlobalMensal/Cabecalho.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/FrequenciaGlobalMensal/Conteudo.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/FrequenciaGlobalMensal/ConteudoCSS.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/FrequenciaGlobalMensal/ConteudoColuna.cshtml
[AB#62274](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62274)
[AB#62216](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62216)
> Servidor Relatórios - Story/62216

- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiarioInfantilComComponente.cshtml
> Correção do bug 64230

- src/SME.SR.Data/Queries/AlunoConsultas.cs
- src/SME.SR.Data/Queries/TurmaConsultas.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
- src/SME.SR.Infra/Enumeradores/SituacaoMatriculaAluno.cs
> Correção do bug 64190

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
> Ajustada consulta SQL ao receber os valores para o "IN" dos alunos.

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
> fix/62213 - ajustes da porcentagem de frequência no RAA

- src/SME.SR.Data/Models/NotasAlunoBimestre.cs
- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
> ajuste na query de notas

- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioFrequenciaGlobalUseCase.cs
> Método de Validação de Situação do Aluno

- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/UltimaSituacaoAlunoRelatorioFrequenciaGlobalDto.cs
> Adicionado arquivo  ignorado no git

- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
> buscar dados do aluno , quando não existir nada no mês selecionado

- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
[AB#64986](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64986)
[AB#64995](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64995)
> Ajustada descrição da UE no relatório.

- src/SME.SR.Application/Interfaces/IMonitorarStatusRelatorioUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IDownloadRelatorioUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioAdesaoAppUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioAtribuicaoCJUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioBoletimEscolarDetalhadoUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioBoletimEscolarUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioCompensacaoAusenciaUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioConselhoClasseAtaBimestralUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioConselhoClasseAtaFinalUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioFrequenciasUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioGamesUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioGraficoPAPUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioHistoricoEscolarUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioImpressaoCalendarioUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioNotasEConceitosFinaisUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioParecerConclusivoUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioPendenciasUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioPlanoAulaUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioRecuperacaoParalelaUseCase.cs
- src/SME.SR.Application/Interfaces/UseCases/IRelatorioResumoPAPUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioAcompanhamentoAprendizagemUseCase.cs
- src/SME.SR.Data/Interceptors/DapperExtensionMethods.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
- src/SME.SR.Infra/Telemetria/IServicoTelemetria.cs
- src/SME.SR.Infra/Telemetria/ServicoTelemetria.cs
- src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
- src/SME.SR.Workers.SGP/Startup.cs
[AB#65023](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65023)
[AB#65024](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65024)
> Fix_65023 -> Release

- src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoFrequenciaGlobalMensal.cs
- src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginado.cs
- src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoPorColuna.cs
[AB#65037](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65037)
> Quebra de página incorreta no pDF com agrupamento

- src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommand.cs
- src/SME.SR.Application/Commands/ExportacaoExcel/GerarExcelGenerico/GerarExcelGenericoCommandHandler.cs
- src/SME.SR.Application/UseCases/RelatorioFrequenciaGlobalUseCase.cs
[AB#65205](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65205)
[AB#64446](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64446)
> Criar Tratativa para Manter o Zero no CodigoUE

- src/SME.SR.Infra/Telemetria/ServicoTelemetria.cs
[AB#65023](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65023)
> Ajustado tipo e sub tipo para HTTP no APM.

- src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
[AB#64927](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64927)
> fix/64927 - Ajuste para seguir ordenação correta da proficiência escrita - sondagem português

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlParaPdfCommand/GerarRelatorioHtmlParaPdfCommandHandler.cs
Inclusção do log para obter o caminho do relatório de itinerância.
> Bug: 64191

- src/SME.SR.Application/Queries/Alunos/ObterAlunosSituacaoPorTurma/ObterAlunosSituacaoPorTurmaQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioConselhoClasseAtaFinalUseCase.cs
[AB#65746](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65746)
> Ajuste na ordenação e no filtro de alunos pela situação da matricula

- src/SME.SR.Application/Queries/DiarioBordo/ObterDadosPlanejamentoDiarioBordo/ObterDadosPlanejamentoDiarioBordoQueryHandler.cs
- src/SME.SR.Application/Queries/DiarioBordo/ObterDadosPlanejamentoDiarioBordoComComponente/ObterDadosPlanejamentoDiarioBordoComComponenteQueryHandler.cs
- src/SME.SR.Workers.SGP/Views/RelatorioControlePlanejamentoDiarioInfantilComComponente.cshtml
[AB#64230](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64230)
> Ajuste na ordenação das datas e na quebra de linhas

- src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeAnalitico/GerarRelatorioControleGradeAnaliticoCommandHandler.cs
- src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeSintetico/GerarRelatorioControleGradeSinteticoCommandHandler.cs
- src/SME.SR.Infra/Dtos/ControleGrade/FiltroControleGrade.cs
- src/SME.SR.Workers.SGP/Views/RelatorioControleGradeAnalitico.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioControleGradeSintetico.cshtml
[AB#65584](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65584)
> Omitir colunas quando modalidade infantil

- src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
[AB#65504](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65504)
> R2 - Adequação da chamada dos relatórios que não herdam de IUseCase

- src/SME.SR.Application/Interfaces/UseCases/IRelatorioBoletimEscolarDetalhadoUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioBoletimEscolarDetalhadoUseCase.cs
- src/SME.SR.Workers.SGP/Controllers/WorkerSGPController.cs
- src/SME.SR.Workers.SGP/Listeners/RabbitBackgroundListener.cs
[AB#65504](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65504)
> PROD - RelatorioBoletimEscolarDetalhadoUseCase herdando de IUseCase

- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
- src/SME.SR.Infra/Dtos/Relatorios/FrequenciaGlobal/FrequenciaGlobalDto.cs
[AB#65157](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65157)
> Fix/65157 -> Master

- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
[AB#66416](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66416)
> Ajuste na query do consolidado de conselho de classe

- src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeAnalitico/GerarRelatorioControleGradeAnaliticoCommandHandler.cs
- src/SME.SR.Application/Commands/ControleGrade/GerarRelatorioControleGradeSintetico/GerarRelatorioControleGradeSinteticoCommandHandler.cs
- src/SME.SR.Infra/Dtos/ControleGrade/FiltroControleGrade.cs
- src/SME.SR.Workers.SGP/Views/RelatorioControleGradeAnalitico.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioControleGradeSintetico.cshtml
[AB#65584](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65584)
> PROD - fix/65584 - Omitir colunas quando modalidade infantil

- src/SME.SR.Application/Commands/ComunsRelatorio/GerarRelatorioHtmlParaPdfCommand/GerarRelatorioHtmlParaPdfCommandHandler.cs
- src/SME.SR.Application/Queries/Devolutivas/ObterDevolutivas/ObterDevolutivasQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioDevolutivasUseCase.cs
- src/SME.SR.Data/Repositories/Sgp/DevolutivaRepository.cs
[AB#66710](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66710)
> Ajuste no tratamento de erro interno

- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
- src/SME.SR.Application/UseCases/RelatorioFrequenciaGlobalUseCase.cs
[AB#67093](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67093)
> Ajuste na condição de exibição de alunos inativos

- src/SME.SR.Infra/RelatorioPaginado/PaginaFrenquenciaMensal.cs
- src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoFrequenciaGlobalMensal.cs
- src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginado.cs
- src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoColuna.cs
- src/SME.SR.Infra/RelatorioPaginado/RelatorioPaginadoFrequenciaMensal.cs
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/FrequenciaGlobalMensal/ConteudoCSS.cshtml
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/FrequenciaGlobalMensal/ConteudoColuna.cshtml
[AB#65965](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65965)
[AB#65966](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65966)
> Seção não deve mostrar DRE e UE / Melhoria na visualização do relatório PDF

- src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioBoletimSimples/ObterNotasRelatorioBoletimSimplesQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseConsolidadoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
[AB#65541](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65541)
> BUG 65541 -> release-r2

- src/SME.SR.Infra/RelatorioPaginado/Coluna.cs
- src/SME.SR.Infra/RelatorioPaginado/Interfaces/IColuna.cs
- src/SME.SR.Infra/RelatorioPaginado/Preparador/PreparadorDeRelatorioPaginadoFrequenciaGlobalMensal.cs
- src/SME.SR.Workers.SGP/Views/RelatorioPaginado/FrequenciaGlobalMensal/ConteudoColuna.cshtml
[AB#65966](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65966)
> Alinha titulo coluna nome

- src/SME.SR.Application/Commands/Log/SalvarLogViaRabbit/SalvarLogViaRabbitCommandHandler.cs
[AB#67917](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67917)
> Correção do bug 67917

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#69052](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69052)
> Fix/69052 - ajuste para correção de frequência no relatório de ata bimestral

- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralPorAnoEAlunos/ObterFrequenciasGeralPorAnoEAlunosQuery.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasGeralPorAnoEAlunos/ObterFrequenciasGeralPorAnoEAlunosQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#58667](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58667)
> fix/58667 -> master

- src/SME.SR.Workers.SGP/Middlewares/ExcecaoMiddleware.cs
[AB#66710](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66710)
> Exibir os detalhes do erro interno.

- src/SME.SR.Workers.SGP/Views/RelatorioRegistroIndividualCorpo.cshtml
[AB#69551](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69551)
> Correção do bug 69551

- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#62186](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62186)
> fix/62186_SR -> release-r2

- src/SME.SR.Application/UseCases/DownloadRelatorioUseCase.cs
- src/SME.SR.Application/UseCases/RelatorioDevolutivasSincronoUseCase.cs
[AB#70100](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70100)
> Ajuste na geração do relatório de devolutivas

- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#66651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66651)
> fix/66651 -> r2

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
[AB#70418](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70418)
> Fix/70418 -> r2

- src/SME.SR.Application/Queries/AcompanhamentoAprendizagem/ObterRelatorioAcompanhamentoAprendizagemQueryHandler.cs
[AB#70418](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70418)
> fix/70418 -> master

- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#62186](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62186)
> fix/62186 -> master

- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#66651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66651)
> fix/66651 -> master

- src/SME.SR.Application/Commands/Arquivos/ObterArquivoRemotoBase64/ObterArquivoRemotoBase64CommandHandler.cs
> Fix/70496 -> r2  - (ajuste de orientação de imagem ao gerar relatório)

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorTurma/ObterComponentesCurricularesPorTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/GrupoMatriz/ObterGrupoMatrizIdPorComponenteCurricularId/ObterGrupoMatrizIdPorComponenteCurricularIdQuery.cs
- src/SME.SR.Application/Queries/GrupoMatriz/ObterGrupoMatrizIdPorComponenteCurricularId/ObterGrupoMatrizIdPorComponenteCurricularIdQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IComponenteCurricularRepository.cs
- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#70102](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70102)
> Fix/70102 -> r2

- src/SME.SR.Data/Repositories/Sgp/RegistrosPedagogicosRepository.cs
> Master -> R2

- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
Ajuste paliativo na consulta, onde há um subselect para um campo que está retornando mais de um registro e remoção de um tratamento de erro incoerente.
> Ajuste do erro ao gerar boletim consequentemente a notificação.

- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
This reverts commit b1361ae1cc83890bb384d489b2b5a077cd861437.
> Revert "Ajuste do erro ao gerar boletim consequentemente a notificação."

- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseNotaRepository.cs
[AB#71379](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71379)
> Correção do bug 71379

- src/SME.SR.Application/Queries/Sondagem/MatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatematicaAditivoMultiplicativoConsolidado/ObterSondagemMatAditMultiConsolidadoQueryHandler.cs
- src/SME.SR.Data/Repositories/Sondagem/SondagemAutoralRepository.cs
[AB#71548](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71548)
> Correção do bug 71548

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Infra/Dtos/Relatorios/ConselhoClasseAtaFinal/FiltroConselhoClasseAtaFinalDto.cs
[AB#71545](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71545)
> Correção do bug 71545

- src/SME.SR.Application/Queries/ComponenteCurricular/ObterComponentesCurricularesPorTurma/ObterComponentesCurricularesPorTurmaQueryHandler.cs
- src/SME.SR.Application/Queries/GrupoMatriz/ObterGrupoMatrizIdPorComponenteCurricularId/ObterGrupoMatrizIdPorComponenteCurricularIdQuery.cs
- src/SME.SR.Application/Queries/GrupoMatriz/ObterGrupoMatrizIdPorComponenteCurricularId/ObterGrupoMatrizIdPorComponenteCurricularIdQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IComponenteCurricularRepository.cs
- src/SME.SR.Data/Repositories/Eol/ComponenteCurricularRepository.cs
[AB#70102](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70102)
> fix/70102 -> master

- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#71865](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71865)
> Fix/71865_v1 -> release-r2

- src/SME.SR.Application/UseCases/RelatorioPlanejamentoDiarioUseCase.cs
Inclusão de tratamento de erro para inclusão no log.
> Bug: 64230

- src/SME.SR.Data/Queries/TipoCalendarioConsultas.cs
> Bug: 71709

- src/SME.SR.Application/Queries/BoletimEscolar/ObterRelatorioBoletimEscolarQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoQueryHandler.cs
- src/SME.SR.Application/Queries/BoletimEscolarDetalhado/ObterRelatorioBoletimEscolarDetalhadoEscolaAqui/ObterDadosMensagemEscolaAquiQueryHendler.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioBoletim/ObterFrequenciasRelatorioBoletimQuery.cs
- src/SME.SR.Application/Queries/Frequencia/ObterFrequenciasRelatorioBoletim/ObterFrequenciasRelatorioBoletimQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IFrequenciaAlunoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/FrequenciaAlunoRepository.cs
[AB#71865](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71865)
> Fix/71865 -> master

- src/SME.SR.Application/Queries/RelatorioFaltasFrequencia/ObterRelatorioFrequenciaPdf/ObterRelatorioFrequenciaPdfQueryHandler.cs
[AB#70007](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70007)
> fix/70007 -> master

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#73928](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73928)
> Fix/73928 -> r2

- src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioAtaFinal/ObterNotasRelatorioAtaFinalQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/INotaConceitoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#72770](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72770)
> Fix/72770 -> r2

- src/SME.SR.Data/Queries/TurmaConsultas.cs
[AB#72281](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72281)
> Correção do bug 72281

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
[AB#73928](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73928)
> fix/73928 -> master

- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
[AB#73215](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73215)
> Correção do bug 73215

- src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioAtaFinal/ObterNotasRelatorioAtaFinalQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/INotaConceitoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#72770](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72770)
> Fix/72770 -> master

- src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioAtaFinal/ObterNotasRelatorioAtaFinalQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
- src/SME.SR.Application/Queries/RelatorioFrequenciaGlobal/ObterRelatorioDeFrequenciaGlobalQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/INotaConceitoRepository.cs
- src/SME.SR.Data/Queries/TurmaConsultas.cs
- src/SME.SR.Data/Repositories/Sgp/NotaConceitoRepository.cs
[AB#73513](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73513)
> Fix/73513 -> r2

- src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaFinal/ObterRelatorioConselhoClasseAtaFinalPdf/ObterRelatorioConselhoClasseAtaFinalPdfQueryHandler.cs
[AB#73513](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73513)
> fix/73513 -> master

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#74201](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74201)
> Fix/74201 -> r2

- src/SME.SR.Data/Repositories/Eol/AlunoRepository.cs
[AB#74201](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74201)
> Fix/74201 -> master

- src/SME.SR.Data/Repositories/Sgp/FechamentoConsolidadoRepository.cs
[AB#75188](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75188)
> Correção do bug 75188

- src/SME.SR.Application/Queries/NotaConceito/ObterNotasRelatorioBoletimSimples/ObterNotasRelatorioBoletimSimplesQueryHandler.cs
- src/SME.SR.Data/Interfaces/Sgp/IConselhoClasseConsolidadoRepository.cs
- src/SME.SR.Data/Repositories/Sgp/ConselhoClasseConsolidadoRepository.cs
Desfizemos o ajuste do bug 65541, pois identificamos melhorias e um refact a serem feitas nos ajustes realizados.
> Bug: 75220

- src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
[AB#75270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75270)
> Fix/75270 -> r2

- src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
[AB#75270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75270)
> fix/75270 pt.2 -> r2

- src/SME.SR.Application/UseCases/RelatorioSondagemPtConsolidadoLeitEscProdUseCase.cs
[AB#75270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75270)
> Fix/75270 -> master
